---
title: "cluster_new"
author: "Ryan Peterson"
date: "2025-04-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library}
#libraries
suppressMessages(library(adespatial)) #for constr.hclust
suppressMessages( library(cluster)) #for general cluster/diana
suppressMessages(library(dendextend)) 
suppressMessages( library(factoextra))

suppressMessages(library(scales))

#for constr.hclust example and correct linkages
library(spData) 
library(spdep)

suppressMessages( library(fields))
```

```{r data_import}
# data and functions
setwd("~/CO_AUS/Aus_CO-main/Interactions")

load( "Data/ne_data.rda")
load( "Data/se_data.rda")
load( "Data/bounded_data.rda")
load( "Data/data_matrix.rda")
load( "Data/lag_list.rda")

```

```{r setup}
season_weeks <- c(35:52, 1:14)
season_years <- unique(bounded_resp_df$year)

seasons <- c()
for (i in 1:(length(season_years)-1)) {
  temp_season <- paste0(season_years[i], "-", season_years[i+1])
  #print(temp_season)  
  seasons <- c(seasons, temp_season)
}
rm(i, temp_season)

#center response data
NEbase_matrix <- scale(resp_matrix[ ,1:32], center = TRUE, scale = FALSE)
SEbase_matrix <- scale(resp_matrix[ ,33:64], center = TRUE, scale = FALSE)
```


# New Clustering


```{r clustering_setup}
#brief test on removing 35-37
#NEbase_matrix <- NEbase_matrix[ ,-c(1:3)]
#SEbase_matrix <- SEbase_matrix[ ,-c(1:3)]
#season_weeks <- c(38:52, 1:14)

#manhattan distance
NE_d1 <- dist(t(NEbase_matrix), method = "manhattan")
SE_d1 <- dist(t(SEbase_matrix), method = "manhattan")

#euclidean distance
NE_d2 <- dist(t(NEbase_matrix), method = "euclidean")
SE_d2 <- dist(t(SEbase_matrix), method = "euclidean")

#squared euclidean
NE_d22 <- NE_d2^2
SE_d22 <- SE_d2^2

#correlation
NE_rho <- as.dist(1-cor(NEbase_matrix))
SE_rho <- as.dist(1-cor(SEbase_matrix))
#NE_rho <- cor(NEbase_matrix)
#SE_rho <- cor(SEbase_matrix)

hclust_methods <- c("single", "complete", "average", "ward.D2", "ward.D", "centroid")
```


```{r d1}

NE_man2 <- c()
NE_man3 <- c()
NE_man4 <- c()
SE_man2 <- c()
SE_man3 <- c()
SE_man4 <- c()

for (i in 1:6) {
  NEhc_man <- constr.hclust(NE_d1, method = hclust_methods[i], chron = TRUE)
  NEsc_man2 <- mean(silhouette(cutree(NEhc_man, k = 2), NE_d1)[, 3])
  NEsc_man3 <- mean(silhouette(cutree(NEhc_man, k = 3), NE_d1)[, 3])
  NEsc_man4 <- mean(silhouette(cutree(NEhc_man, k = 4), NE_d1)[, 3])
  NE_man2 <- c(NE_man2, NEsc_man2)
  NE_man3 <- c(NE_man3, NEsc_man3)
  NE_man4 <- c(NE_man4, NEsc_man4)
  
  SEhc_man <- constr.hclust(SE_d1, method = hclust_methods[i], chron = TRUE)
  SEsc_man2 <- mean(silhouette(cutree(SEhc_man, k = 2), SE_d1)[, 3])
  SE_man2 <- c(SE_man2, SEsc_man2)
  SEsc_man3 <- mean(silhouette(cutree(SEhc_man, k = 3), SE_d1)[, 3])
  SE_man3 <- c(SE_man3, SEsc_man3)  
  SEsc_man4 <- mean(silhouette(cutree(SEhc_man, k = 4), SE_d1)[, 3])
  SE_man4 <- c(SE_man4, SEsc_man4)  
}


man_df <- data.frame(linkage = hclust_methods, NE_k2 = NE_man2, SE_k2 = SE_man2,
                     NE_k3 = NE_man3, SE_k3 = SE_man3,
                     NE_k4 = NE_man4, SE_k4 = SE_man4)


```

```{r d2}
NE_euc2 <- c()
NE_euc3 <- c()
NE_euc4 <- c()
SE_euc2 <- c()
SE_euc3 <- c()
SE_euc4 <- c()

for (i in 1:6) {
  NEhc_euc <- constr.hclust(NE_d2, method = hclust_methods[i], chron = TRUE)
  NEsc_euc2 <- mean(silhouette(cutree(NEhc_euc, k = 2), NE_d2)[, 3])
  NEsc_euc3 <- mean(silhouette(cutree(NEhc_euc, k = 3), NE_d2)[, 3])
  NEsc_euc4 <- mean(silhouette(cutree(NEhc_euc, k = 4), NE_d2)[, 3])
  NE_euc2 <- c(NE_euc2, NEsc_euc2)
  NE_euc3 <- c(NE_euc3, NEsc_euc3)
  NE_euc4 <- c(NE_euc4, NEsc_euc4)
  
  SEhc_euc <- constr.hclust(SE_d2, method = hclust_methods[i], chron = TRUE)
  SEsc_euc2 <- mean(silhouette(cutree(SEhc_euc, k = 2), SE_d2)[, 3])
  SEsc_euc3 <- mean(silhouette(cutree(SEhc_euc, k = 3), SE_d2)[, 3])
  SE_euc2 <- c(SE_euc2, SEsc_euc2)
  SE_euc3 <- c(SE_euc3, SEsc_euc3) 
  SEsc_euc4 <- mean(silhouette(cutree(SEhc_euc, k = 4), SE_d2)[, 3])
  SE_euc4 <- c(SE_euc4, SEsc_euc4)
}

euc_df <- data.frame(linkage = hclust_methods, NE_k2 = NE_euc2, SE_k2 = SE_euc2,
                     NE_k3 = NE_euc3, SE_k3 = SE_euc3,
                     NE_k4 = NE_euc4, SE_k4 = SE_euc4)
```


```{r d22}
NE_euc2 <- c()
NE_euc3 <- c()
NE_euc4 <- c()
SE_euc2 <- c()
SE_euc3 <- c()
SE_euc4 <- c()

for (i in 1:6) {
  NEhc_euc <- constr.hclust(NE_d22, method = hclust_methods[i], chron = TRUE)
  NEsc_euc2 <- mean(silhouette(cutree(NEhc_euc, k = 2), NE_d22)[, 3])
  NEsc_euc3 <- mean(silhouette(cutree(NEhc_euc, k = 3), NE_d22)[, 3])
  NEsc_euc4 <- mean(silhouette(cutree(NEhc_euc, k = 4), NE_d22)[, 3])
  NE_euc2 <- c(NE_euc2, NEsc_euc2)
  NE_euc3 <- c(NE_euc3, NEsc_euc3)
  NE_euc4 <- c(NE_euc4, NEsc_euc4)
  
  SEhc_euc <- constr.hclust(SE_d22, method = hclust_methods[i], chron = TRUE)
  SEsc_euc2 <- mean(silhouette(cutree(SEhc_euc, k = 2), SE_d22)[, 3])
  SEsc_euc3 <- mean(silhouette(cutree(SEhc_euc, k = 3), SE_d22)[, 3])
  SE_euc2 <- c(SE_euc2, SEsc_euc2)
  SE_euc3 <- c(SE_euc3, SEsc_euc3) 
  SEsc_euc4 <- mean(silhouette(cutree(SEhc_euc, k = 4), SE_d22)[, 3])
  SE_euc4 <- c(SE_euc4, SEsc_euc4)
}


sqeuc_df <- data.frame(linkage = hclust_methods, NE_k2 = NE_euc2, SE_k2 = SE_euc2,
                     NE_k3 = NE_euc3, SE_k3 = SE_euc3, 
                     NE_k4 = NE_euc4, SE_k4 = SE_euc4)
                    
```


```{r rho}
NE_cor2 <- c()
NE_cor3 <- c()
NE_cor4 <- c()
SE_cor2 <- c()
SE_cor3 <- c()
SE_cor4 <- c()

for (i in 1:6) {
  NEhc_cor <- constr.hclust(NE_rho, method = hclust_methods[i], chron = TRUE)
  NEsc_cor2 <- mean(silhouette(cutree(NEhc_cor, k = 2), NE_rho)[, 3])
  NEsc_cor3 <- mean(silhouette(cutree(NEhc_cor, k = 3), NE_rho)[, 3])
  NEsc_cor4 <- mean(silhouette(cutree(NEhc_cor, k = 4), NE_rho)[, 3])
  NE_cor2 <- c(NE_cor2, NEsc_cor2)
  NE_cor3 <- c(NE_cor3, NEsc_cor3)
  NE_cor4 <- c(NE_cor4, NEsc_cor4)
  
  SEhc_cor <- constr.hclust(SE_rho, method = hclust_methods[i], chron = TRUE)
  SEsc_cor2 <- mean(silhouette(cutree(SEhc_cor, k = 2), SE_rho)[, 3])
  SEsc_cor3 <- mean(silhouette(cutree(SEhc_cor, k = 3), SE_rho)[, 3])
  SEsc_cor4 <- mean(silhouette(cutree(SEhc_cor, k = 4), SE_rho)[, 3])  
  SE_cor2 <- c(SE_cor2, SEsc_cor2)
  SE_cor3 <- c(SE_cor3, SEsc_cor3)  
  SE_cor4 <- c(SE_cor4, SEsc_cor4)    
}


cor_df <- data.frame(linkage = hclust_methods, NE_k2 = NE_cor2, SE_k2 = SE_cor2,
                     NE_k3 = NE_cor3, SE_k3 = SE_cor3,
                     NE_k4 = NE_cor4, SE_k4 = SE_cor4)
```


```{r cophenetic}

NE_coph <- c()
SE_coph <- c()
for (i in 1:6) {
  NEhc_man <- constr.hclust(NE_d2, method = hclust_methods[i], chron = TRUE)
  NE_ccc <- cor(NE_d2, cophenetic(NEhc_man))
  NE_coph <- c(NE_coph, NE_ccc)
  
  SEhc_man <- constr.hclust(SE_d2, method = hclust_methods[i], chron = TRUE)
  SE_ccc <- cor(SE_d2, cophenetic(SEhc_man))
  SE_coph <- c(SE_coph, SE_ccc)
}




coph_df <- data.frame(linkage = hclust_methods, NEman_coph = NE_coph, SEman_coph = SE_coph)

```

```{r}
#test 

NEhc_man <- constr.hclust(NE_d2, method = "ward.D2", chron = TRUE)

cor(NE_d22, cophenetic(NEhc_man))

SEhc_man <- constr.hclust(SE_d2, method = "ward.D2", chron = TRUE)

cor(SE_d22, cophenetic(SEhc_man))
```


## Further Work

TODO: compare Ward.D and Ward.D2 for euclidean and squared euclidean (just to make sure)

```{r wardD_compare}
#ward.D2 with euclidean dist
NEhc_test1 <- constr.hclust(NE_d2, method = "average", chron = TRUE)
SEhc_test1 <- constr.hclust(SE_d2, method = "average", chron = TRUE)

#ward.D with euclidean dist
NEhc_test2 <- constr.hclust(NE_d2, method = "complete", chron = TRUE)
SEhc_test2 <- constr.hclust(SE_d2, method = "complete", chron = TRUE)

#ward.D2 with sq. euclidean dist
NEhc_test3 <- constr.hclust(NE_d22, method = "average", chron = TRUE)
SEhc_test3 <- constr.hclust(SE_d22, method = "average", chron = TRUE)

#ward.D2 with sq. euclidean dist
NEhc_test4 <- constr.hclust(NE_d22, method = "single", chron = TRUE)
SEhc_test4 <- constr.hclust(SE_d22, method = "single", chron = TRUE)



NEhc_test3 <- constr.hclust(NE_d22, method = "average", chron = TRUE)
SEhc_test4 <- constr.hclust(SE_d22, method = "average", chron = TRUE)

NEhc_test1$order <- c(1:32)
SEhc_test1$order <- c(1:32)

NEhc_test2$order <- c(1:32)
SEhc_test2$order <- c(1:32)

NEhc_test3$order <- c(1:32)
SEhc_test3$order <- c(1:32)

NEhc_test4$order <- c(1:32)
SEhc_test4$order <- c(1:32)


set.panel(2,2)
stats:::plot.hclust(NEhc_test1, hang = -1, main = "NE Aus : Cluster Dendrogram")
rect.hclust(NEhc_test1, k = 3, border = 2:5)
stats:::plot.hclust(NEhc_test2, hang = -1, main = "NE Aus : Cluster Dendrogram")
rect.hclust(NEhc_test2, k = 3, border = 2:5)
stats:::plot.hclust(NEhc_test3, hang = -1, main = "NE Aus : Cluster Dendrogram")
rect.hclust(NEhc_test3, k = 3, border = 2:5)
stats:::plot.hclust(NEhc_test4, hang = -1, main = "NE Aus : Cluster Dendrogram")
rect.hclust(NEhc_test4, k = 3, border = 2:5)


set.panel(2,2)
stats:::plot.hclust(SEhc_test1, hang = -1, main = "SE Aus : Cluster Dendrogram")
rect.hclust(SEhc_test1, k = 3, border = 2:5)
stats:::plot.hclust(SEhc_test2, hang = -1, main = "SE Aus : Cluster Dendrogram")
rect.hclust(SEhc_test2, k = 3, border = 2:5)
stats:::plot.hclust(SEhc_test3, hang = -1, main = "SE Aus : Cluster Dendrogram")
rect.hclust(SEhc_test3, k = 3, border = 2:5)
stats:::plot.hclust(SEhc_test4, hang = -1, main = "SE Aus : Cluster Dendrogram")
rect.hclust(SEhc_test4, k = 3, border = 2:5)

set.panel(1,2)
stats:::plot.hclust(NEhc_test3, hang = -1, main = "NE Aus : Cluster Dendrogram")
rect.hclust(NEhc_test3, k = 2, border = 2:5)
stats:::plot.hclust(SEhc_test4, hang = -1, main = "SE Aus : Cluster Dendrogram")
rect.hclust(SEhc_test4, k = 2, border = 2:5)

```


```{r}
NEhc_agg3 <- constr.hclust(NE_d22, method = "average", chron = TRUE)
NEcut_agg2 <- cutree(NEhc_agg3, k = 2)

NEagg2_sil <- silhouette(NEcut_agg2, NE_d22)
plot(NEagg2_sil, main = "")
pNE <- fviz_silhouette(NEagg2_sil, label = TRUE, print.summary = FALSE)

pNE + scale_x_discrete(
      breaks = pNE$data$name,
      labels = season_weeks[as.integer(as.character(pNE$data$name))]
  ) +
  theme(axis.text.x = element_text(angle = 90, size = 6)) +
  xlab("Weeks")


SEhc_agg3 <- constr.hclust(SE_d22, method = "average", chron = TRUE)
SEcut_agg2 <- cutree(SEhc_agg3, k = 2) 

SEagg2_sil <- silhouette(SEcut_agg2, SE_d22)
plot(SEagg2_sil)
pSE <- fviz_silhouette(SEagg2_sil, label = TRUE, print.summary = FALSE)

pSE + scale_x_discrete(
      breaks = pSE$data$name,
      labels = season_weeks[as.integer(as.character(pSE$data$name))]
  ) +
  theme(axis.text.x = element_text(angle = 90, size = 6)) +
  xlab("Weeks")
```


```{r }

```



```{r}
cor_base <- cor(NEbase_matrix)
image(cor_base[,1:3])
```

```{r sil_coef}
dist_1 <- dist(t(SEbase_matrix), method = "manhattan")
dist_2 <- dist(t(SEbase_matrix), method = "euclidean")
dist_cor <- as.dist(1-cor(SEbase_matrix))

#iterate through k values
complete_hc <- matrix(NA, nrow = 3)
for (j in 2:7) {
  hc_man <- hclust(dist_1)
  sc_man <- mean(silhouette(cutree(hc_man, k = j), dist_1)[, 3])
  
  hc_euc <- hclust(dist_2)
  sc_euc <- mean(silhouette(cutree(hc_euc, k = j), dist_2)[, 3])
  
  hc_cor <- hclust(dist_cor)
  sc_cor <- mean(silhouette(cutree(hc_cor, k = j), dist_cor)[, 3])
  
  complete_hc <- cbind(complete_hc, c(sc_man, sc_euc, sc_cor))
}

complete_hc <- complete_hc[ ,-1]

plot(1:6, complete_hc[1,], type = "b", ylim = range(complete_hc))
points(1:6, complete_hc[2,], type = "b", col = "red")
points(1:6, complete_hc[3,], type = "b", col = "blue")

```





# All Years Clustering

```{r baseline_cluster}
#using default values 
NEconst_clust <- constr.hclust(dist(t(NEbase_matrix)), chron = TRUE) #default with ward.d2 method
SEconst_clust <- constr.hclust(dist(t(SEbase_matrix)), chron = TRUE) #default with ward.d2 method

cutree(NEconst_clust, k =2)
cutree(SEconst_clust, k =2)

SEconst_clust$order <- 1:32
NEconst_clust$order <- 1:32

stats:::plot.hclust(NEconst_clust, hang = -1, labels = FALSE, bty = "n", sub = "", ylab = "",
                    xlab = "Week", main = "NE Aus : Response Clustering", axes = FALSE, cex.main = 2.0,
                    cex.lab = 1.5)
axis(2)
axis(1, at = 1:32, labels = c(season_weeks[1:32]), 
     las = 3, gap.axis = 0, tck = 0.5, lty = 0, cex.axis = 1.6)


stats:::plot.hclust(SEconst_clust, hang = -1, labels = FALSE, bty = "n", sub = "", ylab = "",
                    xlab = "Week", main = "SE Aus : Response Clustering", axes = FALSE, cex.main = 2.0,
                    cex.lab = 1.5)
axis(2)
axis(1, at = 1:32, labels = c(season_weeks[1:32]), 
     las = 3, gap.axis = 0, tck = 0.5, lty = 0, cex.axis = 1.6)

#TODO: change from manual to something else later
NE_splits <- list(c(46,47))
SE_splits <- list(c(50,51))
```


```{r function}

#we can replace this with dendlist()

cluster_matrix <- function(NEbase_matrix, SEbase_matrix, temporal = TRUE){

  NEclust_matrix <- matrix(NA, ncol = 32)
  SEclust_matrix <- matrix(NA, ncol = 32)
  
  NE_clust <- constr.hclust(dist(t(NEbase_matrix)), chron = temporal) #default with ward.d2 method
  SE_clust <- constr.hclust(dist(t(SEbase_matrix)), chron = temporal) #default with ward.d2 method
  
  NEclust_matrix <- rbind(NEclust_matrix, cutree(NE_clust, k =2))
  SEclust_matrix <- rbind(SEclust_matrix, cutree(SE_clust, k =2))
  
  #ward.D
  NE_clust1 <- constr.hclust(dist(t(NEbase_matrix)), chron = temporal, method = "ward.D") # ward.D method
  SE_clust1 <- constr.hclust(dist(t(SEbase_matrix)), chron = temporal, method = "ward.D") # ward.D method
  
  NEclust_matrix <- rbind(NEclust_matrix, cutree(NE_clust1, k =2))
  SEclust_matrix <- rbind(SEclust_matrix, cutree(SE_clust1, k =2))
  
  #single linkage
  NE_clust2 <- constr.hclust(dist(t(NEbase_matrix)), chron = temporal, method = "single")
  SE_clust2 <- constr.hclust(dist(t(SEbase_matrix)), chron = temporal, method = "single") 
  
  NEclust_matrix <- rbind(NEclust_matrix, cutree(NE_clust2, k =2))
  SEclust_matrix <- rbind(SEclust_matrix, cutree(SE_clust2, k =2))
  
  #complete linkage
  NE_clust3 <- constr.hclust(dist(t(NEbase_matrix)), chron = temporal, method = "complete") 
  SE_clust3 <- constr.hclust(dist(t(SEbase_matrix)), chron = temporal, method = "complete")
  
  NEclust_matrix <- rbind(NEclust_matrix, cutree(NE_clust3, k =2))
  SEclust_matrix <- rbind(SEclust_matrix, cutree(SE_clust3, k =2))
  
  #flexible w/  beta = -0.25
  NE_clust4 <- constr.hclust(dist(t(NEbase_matrix)), chron = temporal, method = "flexible", beta = -0.5) 
  SE_clust4 <- constr.hclust(dist(t(SEbase_matrix)), chron = temporal, method = "flexible", beta = -0.5) 
  
  NEclust_matrix <- rbind(NEclust_matrix, cutree(NE_clust4, k =2))
  SEclust_matrix <- rbind(SEclust_matrix, cutree(SE_clust4, k =2))
  
  #"average" (UPGMA)
  NE_clust5 <- constr.hclust(dist(t(NEbase_matrix)), chron = temporal, method = "average")
  SE_clust5 <- constr.hclust(dist(t(SEbase_matrix)), chron = temporal, method = "average")
  
  NEclust_matrix <- rbind(NEclust_matrix, cutree(NE_clust5, k =2))
  SEclust_matrix <- rbind(SEclust_matrix, cutree(SE_clust5, k =2))
  
  #"mcquitty" (WPGMA)
  NE_clust6 <- constr.hclust(dist(t(NEbase_matrix)), chron = temporal, method = "mcquitty")
  SE_clust6 <- constr.hclust(dist(t(SEbase_matrix)), chron = temporal, method = "mcquitty")
  
  NEclust_matrix <- rbind(NEclust_matrix, cutree(NE_clust6, k =2))
  SEclust_matrix <- rbind(SEclust_matrix, cutree(SE_clust6, k =2))
  
  #"centroid" (UPGMC)a
  NE_clust7 <- constr.hclust(dist(t(NEbase_matrix)), chron = temporal, method = "centroid")
  SE_clust7 <- constr.hclust(dist(t(SEbase_matrix)), chron = temporal, method = "centroid")
  
  NEclust_matrix <- rbind(NEclust_matrix, cutree(NE_clust7, k =2))
  SEclust_matrix <- rbind(SEclust_matrix, cutree(SE_clust7, k =2))
  
  #"median" (WPGMC)
  NE_clust8 <- constr.hclust(dist(t(NEbase_matrix)), chron = temporal, method = "median")
  SE_clust8 <- constr.hclust(dist(t(SEbase_matrix)), chron = temporal, method = "median")
  
  NEclust_matrix <- rbind(NEclust_matrix, cutree(NE_clust8, k =2))
  SEclust_matrix <- rbind(SEclust_matrix, cutree(SE_clust8, k =2))
  
  method_names <- c("ward.d2", "ward.D", "single", "complete", "flexible", 
                    "average", "mcquitty", "centroid", "median")
  
  NEclust_matrix <- NEclust_matrix[-1, ]
  SEclust_matrix <- SEclust_matrix[-1, ]
  
  rownames(NEclust_matrix) <- method_names
  rownames(SEclust_matrix) <- method_names

  return(list(NEclust_matrix, SEclust_matrix))
}
```


```{r}
full_cluster <- cluster_matrix(NEbase_matrix, SEbase_matrix, temporal = TRUE)

NEcluster_list <- list()
SEcluster_list <- list()
for (j in 1:19) {
  NEmatrix_new <- scale(resp_matrix[-c(j), 1:32], center = TRUE, scale = FALSE)
  SEmatrix_new <- scale(resp_matrix[-c(j), 33:64], center = TRUE, scale = FALSE)
  
  part_cluster <- cluster_matrix(NEmatrix_new, SEmatrix_new, temporal = FALSE)
  
  NEcluster_list[[paste0("without:", seasons[j])]] <- part_cluster[[1]]
  SEcluster_list[[paste0("without:", seasons[j])]] <- part_cluster[[2]]
}



#cluster_matrix(NEbase_matrix, SEbase_matrix, temporal = FALSE)
```

```{r}
Reduce("+", NEcluster_list) / length(NEcluster_list)

Reduce("+", SEcluster_list) / length(SEcluster_list)
```


Repeat all of this with the dendextend package 

# Agg/Time Analysis

```{r}
hclust_methods <- c("ward.D", "single", "complete", "average", "mcquitty", 
        "median", "centroid", "ward.D2")

NE_dendlist <- dendlist()
SE_dendlist <- dendlist()

for(i in seq_along(hclust_methods)) {
   hc_NEAus <- constr.hclust(dist(t(NEbase_matrix)), method = hclust_methods[i],  chron = TRUE)
   hc_SEAus <- constr.hclust(dist(t(SEbase_matrix)), method = hclust_methods[i],  chron = TRUE)
   
   NE_dendlist <- dendlist(NE_dendlist, as.dendrogram(hc_NEAus))
   SE_dendlist <- dendlist(SE_dendlist, as.dendrogram(hc_SEAus))
}

names(NE_dendlist) <- hclust_methods
names(SE_dendlist) <- hclust_methods

NE_dendlist
SE_dendlist
```

```{r}
NE_dendlist_cor <- cor.dendlist(NE_dendlist)

corrplot::corrplot(NE_dendlist_cor, "pie", "lower")
```

```{r}
NE_dendlist %>% dendlist(which = c(2,7)) %>% ladderize %>% 
   set("branches_k_color", k=2) %>% 
   # untangle(method = "step1side", k_seq = 3:20) %>%
   tanglegram(faster = TRUE)
```


```{r}
get_ordered_2_clusters <- function(dend) {
   cutree(dend, k = 2)[order.dendrogram(dend)]
}

compare_clusters_to <- function(clus) {FM_index(clus, rep(1:2, each = 16), assume_sorted_vectors = TRUE)}

dend_2_clusters <- lapply(NE_dendlist, get_ordered_2_clusters)

clusters_performance <- sapply(dend_2_clusters, compare_clusters_to)
clusters_performance
dotchart(sort(clusters_performance), xlim = c(0.6, 1),
         xlab = "Fowlkes-Mallows Index (from 0 to 1)",
         main = "Perormance of clustering algorithms \n in detecting the 2 species",
         pch = 19)

dend_2_clusters <- lapply(SE_dendlist, get_ordered_2_clusters)

clusters_performance <- sapply(dend_2_clusters, compare_clusters_to)
clusters_performance
dotchart(sort(clusters_performance), xlim = c(0.6, 1),
         xlab = "Fowlkes-Mallows Index (from 0 to 1)",
         main = "Perormance of clustering algorithms \n in detecting the 2 species",
         pch = 19)

```

```{r}
cutree(NE_dendlist$complete, k = 2)
cutree(SE_dendlist$complete, k = 2)
```

## Train/Test 2019

TODO: build in hclust with chron = TRUE, then do some work to comparison between methods.

```{r}
#train data
NEtrain_matrix <- scale(resp_matrix[-c(16:19) ,1:32], center = TRUE, scale = FALSE)
SEtrain_matrix <- scale(resp_matrix[-c(16:19) ,33:64], center = TRUE, scale = FALSE)

#test data
NEtest_matrix <- scale(resp_matrix[16:19 ,1:32], center = TRUE, scale = FALSE)
SEtest_matrix <- scale(resp_matrix[16:19 ,33:64], center = TRUE, scale = FALSE)

NE_train <- dist(t(NEtrain_matrix))
SE_train <- dist(t(SEtrain_matrix))

NE_test <- dist(t(NEtest_matrix))
SE_test <- dist(t(SEtest_matrix))


hclust_methods <- c("ward.D", "single", "complete", "average", "mcquitty", 
        "median", "centroid", "ward.D2")

i <- 2
NEhc_train <- constr.hclust(NE_train, method = hclust_methods[i],  chron = FALSE)
NEhc_test  <- constr.hclust(NE_test, method = hclust_methods[i],  chron = FALSE)

NEd_train <- as.dendrogram(NEhc_train)
NEd_test <-  as.dendrogram(NEhc_test)
NEd_train_test <- dendlist(train = NEd_train, test = NEd_test)

SEhc_train <- constr.hclust(SE_train, method = hclust_methods[i],  chron = FALSE)
SEhc_test  <- constr.hclust(SE_test, method = hclust_methods[i],  chron = FALSE)

SEd_train <- as.dendrogram(SEhc_train)
SEd_test <- as.dendrogram(SEhc_test)
SEd_train_test <- dendlist(train = SEd_train, test = SEd_test)
```

```{r}
Bk_plot(NEd_test, NEd_train, k = 2:16, xlim = c(2,16))
Bk_plot(SEd_test, SEd_train, k = 2:16, xlim = c(2,16))
```

```{r}
pre_tang_d_train_test <- SEd_train_test %>% ladderize %>% # untangle %>%
   set("branches_k_color", k = 7)
train_branches_colors <- get_leaves_branches_col(pre_tang_d_train_test$train)
pre_tang_d_train_test %>% tanglegram(fast = TRUE, color_lines = train_branches_colors)
```



```{r}
#center response data
NEbase_matrix <- scale(resp_matrix[-c(17) ,1:32], center = TRUE, scale = FALSE)
SEbase_matrix <- scale(resp_matrix[-c(17) ,33:64], center = TRUE, scale = FALSE)

hclust_methods <- c("ward.D", "single", "complete", "average", "mcquitty", 
        "median", "centroid", "ward.D2")

NE_dendlist <- dendlist()
SE_dendlist <- dendlist()

for(i in seq_along(hclust_methods)) {
   hc_NEAus <- constr.hclust(dist(t(NEbase_matrix)), method = hclust_methods[i],  chron = FALSE)
   hc_SEAus <- constr.hclust(dist(t(SEbase_matrix)), method = hclust_methods[i],  chron = FALSE)
   
   NE_dendlist <- dendlist(NE_dendlist, as.dendrogram(hc_NEAus))
   SE_dendlist <- dendlist(SE_dendlist, as.dendrogram(hc_SEAus))
}

names(NE_dendlist) <- hclust_methods
names(SE_dendlist) <- hclust_methods

get_ordered_2_clusters <- function(dend) {
   cutree(dend, k = 2)[order.dendrogram(dend)]
}

compare_clusters_to <- function(clus) {FM_index(clus, rep(1:2, each = 16), assume_sorted_vectors = TRUE)}

dend_2_clusters <- lapply(NE_dendlist, get_ordered_2_clusters)

clusters_performance <- sapply(dend_2_clusters, compare_clusters_to)
which.max( clusters_performance)
dotchart(sort(clusters_performance), xlim = c(0.6, 1),
         xlab = "Fowlkes-Mallows Index (from 0 to 1)",
         main = "Perormance of clustering algorithms \n in detecting the 2 species",
         pch = 19)

dend_2_clusters <- lapply(SE_dendlist, get_ordered_2_clusters)

clusters_performance <- sapply(dend_2_clusters, compare_clusters_to)
which.max( clusters_performance)
dotchart(sort(clusters_performance), xlim = c(0.6, 1),
         xlab = "Fowlkes-Mallows Index (from 0 to 1)",
         main = "Perormance of clustering algorithms \n in detecting the 2 species",
         pch = 19)
```




```{r diana}
#top-down clustering
NEyear_div <- diana(NEbase_matrix,  metric = "manhattan")
plot(NEyear_div)
SEyear_div <- diana(SEbase_matrix,  metric = "manhattan")
plot(SEyear_div)


NEweek_div <- diana(t(NEbase_matrix))
plot(NEweek_div, adj = 0)

SEweek_div <- diana(t(SEbase_matrix))
plot(SEweek_div)

NEweek_agg <- agnes(t(NEbase_matrix))
plot(NEweek_agg)

SEweek_agg <- agnes(t(SEbase_matrix))
plot(SEweek_agg)

summary(SEweek_agg)

clusplot(t(SEbase_matrix), )
```

```{r}
NEtest_matrix <- scale(resp_matrix[ ,1:32], center = TRUE, scale = FALSE)
SEtest_matrix <- scale(resp_matrix[ ,33:64], center = TRUE, scale = FALSE)

NE_test <- dist(t(NEtest_matrix))
SE_test <- dist(t(SEtest_matrix))


hclust_methods <- c("ward.D", "single", "complete", "average", "mcquitty", 
        "median", "centroid", "ward.D2")

i <- 1
NEhc <- constr.hclust(NE_test, method = hclust_methods[i],  chron = TRUE)
coefHier(NEhc)

fviz_nbclust(t(NEtest_matrix), FUN = hcut, method = "wss")
fviz_nbclust(t(SEtest_matrix), FUN = hcut, method = "wss")


#note use this
fviz_nbclust(t(NEtest_matrix), FUN = hcut, method = "gap_stat")
fviz_nbclust(t(SEtest_matrix), FUN = hcut, method = "gap_stat")

dend_plot <- fviz_dend(NEhc)
dend_data <- attr(dend_plot, "dendrogram")
```


```{r test_links}
dat <- c(41,42,25,38,50,30,41,43,43,41,30,50,38,25,42,41)
coord.dat <- matrix(c(1,3,5,7,2,4,6,8,1,3,5,7,2,4,6,8,
4.4,4.4,4.4,4.4,3.3,3.3,3.3,3.3,
2.2,2.2,2.2,2.2,1.1,1.1,1.1,1.1),16,2)

listW <- nb2listw(tri2nb(coord.dat), style="B")
links.mat.dat <- listw2mat(listW)
neighbors <- listw2sn(listW)[,1:2]

plot(coord.dat, type='n',asp=1)
text(coord.dat, labels=as.character(as.matrix(dat)), pos=3)
for(i in 1:nrow(neighbors))
  lines(rbind(coord.dat[neighbors[i,1],],
  coord.dat[neighbors[i,2],]))

D.dat <- dist(dat)

grpWD2cst_constr_hclust <- constr.hclust(
  D.dat, method="ward.D2",
  neighbors, coord.dat)

grpWD2cst_constr_hclust$coords
```

```{r method_checks}
NEtest_matrix <- scale(resp_matrix[ ,4:32], center = TRUE, scale = FALSE)
SEtest_matrix <- scale(resp_matrix[ ,36:64], center = TRUE, scale = FALSE)

NE_test <- dist(t(NEtest_matrix), method = "manhattan")
SE_test <- dist(t(SEtest_matrix), method = "manhattan")

hclust_methods <- c("ward.D", "centroid", "complete", "average")

i <- 3
NEhc1 <- constr.hclust(NE_test, method = hclust_methods[i],  chron = TRUE)
SEhc1 <- constr.hclust(SE_test, method = hclust_methods[i],  chron = TRUE)



NEhc_test <- constr.hclust(NE_test, method = hclust_methods[i],  coords = hc_links)

NE_cut <- cutree(NEhc1, k =2)
NEcut_test <- cutree(NEhc_test, k =2)

SE_cut <- cutree(SEhc1, k =2)

sil_NE <- silhouette(NE_cut, NE_test)
fviz_silhouette(sil_NE, label = TRUE, print.summary = FALSE)

sil_SE <- silhouette(SE_cut, SE_test)
fviz_silhouette(sil_SE, label = TRUE, print.summary = FALSE)

which(sil_NE[, "sil_width"] < 0)
which(sil_SE[, "sil_width"] < 0)

#TODO: when chron false include a circular plot with ordered hclust
#NEhc1$order <- 1:32
#SEhc1$order <- 1:32

coef.hclust(NEhc1)

stats:::plot.hclust(NEhc1, hang = -1, bty = "n", sub = "", ylab = "",
                    xlab = "Week", main = "NE Aus : ward.D")
rect.hclust(NEhc1, k = 2, border = 2:3)

stats:::plot.hclust(SEhc1, hang = -1, bty = "n", sub = "", ylab = "",
                    xlab = "Week", main = "SE Aus : ward.D")
rect.hclust(SEhc1, k = 2, border = 2:3)
```


```{r messy_neighbors}
#very messy 
hc_coord <- NEhc1[["coords"]]
test_old <- cell2nb(32, 1, type="rook", torus=TRUE)
test_test <- cell2nb(32, 1, type="rook", torus=FALSE)
test_test[[1]] <- as.integer(c(2,32))
test_test[[32]] <- as.integer(c(31, 1))

testL <-  nb2listw(test_test, style = "B")
week_neighbor <- listw2sn(testL)[,1:2]

NE_hclust <- constr.hclust(
  NE_test, method ="ward.D",
  week_neighbor, hc_coord)


NE_cut <- cutree(NE_hclust, k =3)

sil_NE <- silhouette(NE_cut, NE_test)
fviz_silhouette(sil_NE, label = TRUE, print.summary = FALSE)


SE_hclust <- constr.hclust(
  SE_test, method ="ward.D",
  week_neighbor, hc_coord)

SE_cut <- cutree(SE_hclust, k =3)

sil_SE <- silhouette(SE_cut, SE_test)
fviz_silhouette(sil_SE, label = TRUE, print.summary = FALSE)

```


```{r diana}
NE_test <- dist(t(NEtest_matrix), method = "manhattan")
SE_test <- dist(t(SEtest_matrix), method = "manhattan")

NEyear_div <- diana(t(NEbase_matrix),  metric = "manhattan")
SEyear_div <- diana(t(SEbase_matrix),  metric = "manhattan")

NEcut_div <- cutree(NEyear_div, k = 2)
SEcut_div <- cutree(SEyear_div, k = 2)


NEsil_div <- silhouette(NEcut_div, NE_test)
fviz_silhouette(NEsil_div, label = TRUE, print.summary = FALSE)

SEsil_div <- silhouette(SEcut_div, SE_test)
fviz_silhouette(SEsil_div, label = TRUE, print.summary = FALSE)

```


```{r coeffs}
#div coefs
NEyear_divM <- diana(t(NEbase_matrix),  metric = "manhattan")
SEyear_divM <- diana(t(SEbase_matrix),  metric = "manhattan")

NEyear_divM$dc
SEyear_divM$dc

NEyear_div <- diana(t(NEbase_matrix),  metric = "euclidian")
SEyear_div <- diana(t(SEbase_matrix),  metric = "euclidian")

NEyear_div$dc
SEyear_div$dc


#agglomerative coefs to compare methods
NE_test <- dist(t(NEtest_matrix), method = "manhattan")
SE_test <- dist(t(SEtest_matrix), method = "manhattan")

hclust_methods <- c("ward.D", "single", "complete", "average")

#chron FALSE

agg_coefM <- matrix(NA, nrow = 2)
for (i in 1:4) {
  NEhc_test <- constr.hclust(NE_test, method = hclust_methods[i],  chron = FALSE)
  SEhc_test <- constr.hclust(SE_test, method = hclust_methods[i],  chron = FALSE)
  agg_coefM <- cbind(agg_coefM, c(coef.hclust(NEhc_test), coef.hclust(SEhc_test)))
}

agg_coefM <- agg_coefM[,-1]
colnames(agg_coefM) <- hclust_methods


#chron "TRUE" (using torus)
#NOTE: agg coef does not work for the other method


#chron TRUE

agg_chronM <- matrix(NA, nrow = 2)
for (i in 1:4) {
  NEhc_test <- constr.hclust(NE_test, method = hclust_methods[i],  chron = TRUE)
  SEhc_test <- constr.hclust(SE_test, method = hclust_methods[i],  chron = TRUE)
  agg_chronM <- cbind(agg_chronM, c(coef.hclust(NEhc_test), coef.hclust(SEhc_test)))
}

agg_chronM <- agg_chronM[,-1]
colnames(agg_chronM) <- hclust_methods

```

# LOO Testing

```{r diana_loo}
NE_diana <- matrix(NA, ncol = 32) 
SE_diana <- matrix(NA, ncol = 32) 
  
for (j in 1:19) {
  NEtest_matrix <- scale(resp_matrix[-c(j) ,1:32], center = TRUE, scale = FALSE)
  SEtest_matrix <- scale(resp_matrix[-c(j) ,33:64], center = TRUE, scale = FALSE)

  NE_test <- dist(t(NEtest_matrix), method = "manhattan")
  SE_test <- dist(t(SEtest_matrix), method = "manhattan")
  
  NEyear_div <- diana(t(NEtest_matrix),  metric = "manhattan")
  SEyear_div <- diana(t(SEtest_matrix),  metric = "manhattan")
  
  NEcut_div <- cutree(NEyear_div, k = 2)
  SEcut_div <- cutree(SEyear_div, k = 2)
  
  NE_diana <- rbind(NE_diana, NEcut_div)
  SE_diana <- rbind(SE_diana, SEcut_div)
}

NE_diana <- NE_diana[-1, ]
SE_diana <- SE_diana[-1, ]

NE_means <- colMeans(NE_diana)
SE_means <- colMeans(SE_diana)


plot(1:32, NE_means, pch = 16, ylim = c(0,3), main = "NE Aus - LOO Diana Cluster")
abline(h = c(1,2), lty =2)


plot(1:32, SE_means, pch = 16, ylim = c(0,3), main = "SE Aus - LOO Diana Cluster")
abline(h = c(1,2), lty =2)
```

```{r agg_loo}
#agg chron FALSE
#using Manhattan/ward.D (based on agg coefs)

NE_agg <- matrix(NA, ncol = 32) 
SE_agg <- matrix(NA, ncol = 32) 

NE_agg2 <- matrix(NA, ncol = 32) 
SE_agg2 <- matrix(NA, ncol = 32) 
  
for (j in 1:19) {
  NEtest_matrix <- scale(resp_matrix[-c(j) ,1:32], center = TRUE, scale = FALSE)
  SEtest_matrix <- scale(resp_matrix[-c(j) ,33:64], center = TRUE, scale = FALSE)

  NE_test <- dist(t(NEtest_matrix), method = "manhattan")
  SE_test <- dist(t(SEtest_matrix), method = "manhattan")

  NEhc_agg <- constr.hclust(NE_test, method ="ward.D", chron = FALSE)
  SEhc_agg <- constr.hclust(SE_test, method ="ward.D", chron = FALSE)
  
  NEhc_agg2 <- constr.hclust(NE_test, method ="ward.D", week_neighbor, hc_coord)
  SEhc_agg2 <- constr.hclust(SE_test, method ="ward.D", week_neighbor, hc_coord)
  
  NEcut_agg <- cutree(NEhc_agg, k = 2)
  SEcut_agg <- cutree(SEhc_agg, k = 2)
  
  NEcut_agg2 <- cutree(NEhc_agg2, k = 2)
  SEcut_agg2 <- cutree(SEhc_agg2, k = 2)
  
  NE_agg <- rbind(NE_agg, NEcut_agg)
  SE_agg <- rbind(SE_agg, SEcut_agg)
  
  NE_agg2 <- rbind(NE_agg2, NEcut_agg2)
  SE_agg2 <- rbind(SE_agg2, SEcut_agg2)
}

NE_agg <- NE_agg[-1, ]
SE_agg <- SE_agg[-1, ]

NE_agg2 <- NE_agg2[-1, ]
SE_agg2 <- SE_agg2[-1, ]

NE_agg[16,]
NE_agg2[16,]

SE_agg[19,]
SE_agg2[19,]

plot(1:32, SE_agg[19,])

NEagg_means <- colMeans(NE_agg)
SEagg_means <- colMeans(SE_agg)

NEagg2_means <- colMeans(NE_agg2)
SEagg2_means <- colMeans(SE_agg2)

set.panel(1,2)
plot(1:32, NEagg_means, pch = 16, ylim = c(0,3), main = "NE Aus - LOO Agg Cluster")
abline(h = c(1,2), lty =2)
points(1:32, NEagg2_means, pch = 16, col = "red3")

plot(1:32, NE_means, pch = 16, ylim = c(0,3), main = "NE Aus - LOO Diana Cluster")
abline(h = c(1,2), lty =2)


set.panel(1,2)
plot(1:32, SEagg_means, pch = 16, ylim = c(0,3), main = "SE Aus - LOO Agg Cluster")
abline(h = c(1,2), lty =2)
points(1:32, SEagg2_means, pch = 16, col = "red3")

plot(1:32, SE_means, pch = 16, ylim = c(0,3), main = "SE Aus - LOO Diana Cluster")
abline(h = c(1,2), lty =2)
```


```{r full_loo_compare}
NE_matrix <- scale(resp_matrix[ ,1:32], center = TRUE, scale = FALSE)
SE_matrix <- scale(resp_matrix[ ,33:64], center = TRUE, scale = FALSE)

NEtest_matrix <- scale(resp_matrix[ ,1:32], center = TRUE, scale = FALSE)
SEtest_matrix <- scale(resp_matrix[ ,33:64], center = TRUE, scale = FALSE)


NE_test <- dist(t(NE_matrix), method = "euclidian")
SE_test <- dist(t(SE_matrix), method = "euclidian")

NEyear_div <- diana(t(NEtest_matrix),  metric = "manhattan")
SEyear_div <- diana(t(SEtest_matrix),  metric = "manhattan")
  
NEcut_div <- cutree(NEyear_div, k = 2)
SEcut_div <- cutree(SEyear_div, k = 2)

NEhc_agg <- constr.hclust(NE_test, method ="ward.D", chron = TRUE)
SEhc_agg <- constr.hclust(SE_test, method ="ward.D", chron = TRUE)

NEhc_agg2 <- constr.hclust(NE_test, method ="ward.D", week_neighbor, hc_coord)
SEhc_agg2 <- constr.hclust(SE_test, method ="ward.D", week_neighbor, hc_coord)

NEhc_agg3 <- constr.hclust(NE_test, method ="ward.D", chron = TRUE)
SEhc_agg3 <- constr.hclust(SE_test, method ="ward.D", chron = TRUE)

NEcut_agg <- cutree(NEhc_agg, k = 3)
SEcut_agg <- cutree(SEhc_agg, k = 3)

NEcut_agg2 <- cutree(NEhc_agg2, k = 2)
SEcut_agg2 <- cutree(SEhc_agg2, k = 2)

NEcut_agg3 <- cutree(NEhc_agg3, k = 2)
SEcut_agg3 <- cutree(SEhc_agg3, k = 2)

plot(1:32, SEcut_agg3)

set.panel(2,2)
plot(1:32, NEcut_agg, pch = 16, ylim = c(0,3), main = "NE Aus - Base Agg Cluster")
abline(h = c(1,2), lty =2)
points(1:32, NEcut_agg2, pch = 16, col = "red3")

plot(1:32, NEcut_div, pch = 16, ylim = c(0,3), main = "NE Aus - Base Diana Cluster")
abline(h = c(1,2), lty =2)

plot(1:32, NEagg_means, pch = 16, ylim = c(0,3), main = "NE Aus - LOO Agg Cluster")
abline(h = c(1,2), lty =2)
points(1:32, NEagg2_means, pch = 16, col = "red3")

plot(1:32, NE_means, pch = 16, ylim = c(0,3), main = "NE Aus - LOO Diana Cluster")
abline(h = c(1,2), lty =2)



set.panel(2,2)
plot(1:32, SEcut_agg, pch = 16, ylim = c(0,3), main = "SE Aus - Base Agg Cluster")
abline(h = c(1,2), lty =2)
points(1:32, SEcut_agg2, pch = 16, col = "red3")

plot(1:32, SEcut_div, pch = 16, ylim = c(0,3), main = "SE Aus - Base Diana Cluster")
abline(h = c(1,2), lty =2)

plot(1:32, SEagg_means, pch = 16, ylim = c(0,3), main = "SE Aus - LOO Agg Cluster")
abline(h = c(1,2), lty =2)
points(1:32, SEagg2_means, pch = 16, col = "red3")

plot(1:32, SE_means, pch = 16, ylim = c(0,3), main = "SE Aus - LOO Diana Cluster")
abline(h = c(1,2), lty =2)

```


```{r compare_sil}
#TODO: relable the xlab so that it gives the weeks and not index

NEcut_div <- cutree(NEyear_div, k = 2)
SEcut_div <- cutree(SEyear_div, k = 2)

NEdiv_sil <- silhouette(NEcut_div, NE_test)
plot(NEdiv_sil)
fviz_silhouette(NEdiv_sil, label = TRUE, print.summary = FALSE)

SEdiv_sil <- silhouette(SEcut_div, SE_test)
plot(SEdiv_sil)
fviz_silhouette(SEdiv_sil, label = TRUE, print.summary = FALSE)


NEagg_sil <- silhouette(NEcut_agg, NE_test)
fviz_silhouette(NEagg_sil, label = TRUE, print.summary = FALSE)


SEagg_sil <- silhouette(SEcut_agg, SE_test)
fviz_silhouette(SEagg_sil, label = TRUE, print.summary = FALSE)

#Optimal 2 clusters is here
NEcut_agg2 <- cutree(NEhc_agg2, k = 2)

NEagg2_sil <- silhouette(NEcut_agg2, NE_test)
plot(NEagg2_sil, main = "")
fviz_silhouette(NEagg2_sil, label = TRUE, print.summary = FALSE)

SEcut_agg2 <- cutree(SEhc_agg2, k = 3) #k=3 is better than 2 (run this if we have time)

SEagg2_sil <- silhouette(SEcut_agg2, SE_test)
plot(SEagg2_sil)
fviz_silhouette(SEagg2_sil, label = TRUE, print.summary = FALSE)

#old version of time constrained
NEcut_agg3 <- cutree(NEhc_agg3, k = 3)

NEagg3_sil <- silhouette(NEcut_agg3, NE_test)
fviz_silhouette(NEagg3_sil, label = TRUE, print.summary = FALSE)

SEcut_agg3 <- cutree(SEhc_agg3, k = 3)

SEagg3_sil <- silhouette(SEcut_agg3, SE_test)
plot(SEagg3_sil)
fviz_silhouette(SEagg3_sil, label = TRUE, print.summary = FALSE)

```


```{r groupings}
#Optimal 2 clusters is here
NEcut_agg2 <- cutree(NEhc_agg3, k = 3)

NEagg2_sil <- silhouette(NEcut_agg2, NE_test)
plot(NEagg2_sil, main = "")
pNE <- fviz_silhouette(NEagg2_sil, label = TRUE, print.summary = FALSE)

pNE + scale_x_discrete(
      breaks = pNE$data$name,
      labels = season_weeks[as.integer(as.character(pNE$data$name))]
  ) +
  theme(axis.text.x = element_text(angle = 90, size = 6)) +
  xlab("Weeks")

SEcut_agg2 <- cutree(SEhc_agg3, k = 3) #k=3 is better than 2 (run this if we have time)

SEagg2_sil <- silhouette(SEcut_agg2, SE_test)
plot(SEagg2_sil)
pSE <- fviz_silhouette(SEagg2_sil, label = TRUE, print.summary = FALSE)

pSE + scale_x_discrete(
      breaks = pSE$data$name,
      labels = season_weeks[as.integer(as.character(pSE$data$name))]
  ) +
  theme(axis.text.x = element_text(angle = 90, size = 6)) +
  xlab("Weeks")

stats:::plot.hclust(NEhc_agg3, hang = -1, main = "NE Aus : Cluster Dendrogram")
rect.hclust(NEhc_agg3, k = 3, border = 2:5)

stats:::plot.hclust(SEhc_agg3, hang = -1, main = "SE Aus : Cluster Dendrogram")
rect.hclust(SEhc_agg3, k = 3, border = 2:5)

```



```{r final_plots}
#TODO: work on this later

#Optimal 2 clusters is here
NEcut_agg2 <- cutree(NEhc_agg2, k = 2)

NEagg2_sil <- silhouette(NEcut_agg2, NE_test)

plot(NEagg2_sil)

p <- fviz_silhouette(NEagg2_sil, label = TRUE, print.summary = FALSE)

factor_names <- p$data$name
season_weeks[as.integer(as.character(factor_names))]


setwd("~/CO_AUS/Aus_CO-main/Interactions/Figures")
png(filename = "NE_sil.png", width = 3000, height = 1500, res = 300)
p + scale_x_discrete(
      breaks = p$data$name,
      labels = season_weeks[as.integer(as.character(factor_names))]
  ) +
  theme(axis.text.x = element_text(angle = 90, size = 6)) +
  xlab("Weeks") +
  labs(subtitle = "NE Aus")
dev.off()



SEcut_agg2 <- cutree(SEhc_agg2, k = 3) #k=3 is better than 2 (run this if we have time)

SEagg2_sil <- silhouette(SEcut_agg2, SE_test, Ordered = TRUE)

plot(SEagg2_sil)

p2 <- fviz_silhouette(SEagg2_sil, label = TRUE, print.summary = FALSE)

setwd("~/CO_AUS/Aus_CO-main/Interactions/Figures")
png(filename = "SE_sil2.png", width = 3000, height = 1500, res = 300)
p2 + scale_x_discrete(
      breaks = p2$data$name,
      labels = season_weeks[as.integer(as.character(p2$data$name))]
  ) +
  theme(axis.text.x = element_text(angle = 90, size = 6)) +
  xlab("Weeks")+
  labs(subtitle = "SE Aus")
dev.off()


#old version of time constrained
NEcut_agg3 <- cutree(NEhc_agg3, k = 4)

NEagg3_sil <- silhouette(NEcut_agg3, NE_test)
p3 <- fviz_silhouette(NEagg3_sil, label = TRUE, print.summary = FALSE)
setwd("~/CO_AUS/Aus_CO-main/Interactions/Figures")
png(filename = "NE_silold.png", width = 3000, height = 1500, res = 300)
p3 + scale_x_discrete(
      breaks = p3$data$name,
      labels = season_weeks[as.integer(as.character(p3$data$name))]
  ) +
  theme(axis.text.x = element_text(angle = 90, size = 6)) +
  xlab("Weeks")+
  labs(subtitle = "NE Aus")
dev.off()

SEcut_agg3 <- cutree(SEhc_agg3, k = 4)

SEagg3_sil <- silhouette(SEcut_agg3, SE_test)
plot(SEagg3_sil)


p4 <- fviz_silhouette(SEagg3_sil, label = TRUE, print.summary = FALSE)
setwd("~/CO_AUS/Aus_CO-main/Interactions/Figures")
png(filename = "SE_silold.png", width = 3000, height = 1500, res = 300)
p4 + scale_x_discrete(
      breaks = p4$data$name,
      labels = season_weeks[as.integer(as.character(p4$data$name))]
  ) +
  theme(axis.text.x = element_text(angle = 90, size = 6)) +
  xlab("Weeks")+
  labs(subtitle = "SE Aus")
dev.off()
```


```{r}
NEhc_agg2$order <- c(4:32, 1:3)
SEhc_agg2$order <- c(4:32, 1:3)

#TODO: adjust ordering so that it kinda makes sense

setwd("~/CO_AUS/Aus_CO-main/Interactions/Figures")
png(filename = "NE_dend.png", width = 3000, height = 1500, res = 300)
stats:::plot.hclust(NEhc_agg2,  hang = -1, labels = FALSE, bty = "n", sub = "", ylab = "",
                    xlab = "Week", main = "NE Aus : Response Clustering", axes = FALSE, cex.main = 1.33,
                    cex.lab = 1.33)
axis(2)
axis(1, at = 1:32, labels = c(season_weeks[c(4:32, 1:3)]), 
     las = 3, gap.axis = 0, tck = 0.5, lty = 0, cex.axis = 1.33)
rect(xleft = 0.5, xright = 9.5, ybottom = 0, ytop = 375, col = rgb(1, 0, 0, 0.2), border = NA)
rect(xleft = 9.5, xright = 32.5, ybottom = 0, ytop = 375, col = rgb(0, 1, 0, 0.2), border = NA)
text(5, -25, "Group 2", col = "black", cex = 1.3, xpd = TRUE)
text(20.5, -25, "Group 1", col = "black", cex = 1.3, xpd = TRUE)
#rect.hclust(NEhc_agg2, k = 2, border = 2:3)
dev.off()

setwd("~/CO_AUS/Aus_CO-main/Interactions/Figures")
png(filename = "SE_dend.png", width = 3000, height = 1500, res = 300)
stats:::plot.hclust(SEhc_agg2, hang = -1, labels = FALSE, bty = "n", sub = "", ylab = "",
                    xlab = "Week", main = "SE Aus : Response Clustering", axes = FALSE, cex.main = 1.33,
                    cex.lab = 1.33)
axis(2)
axis(1, at = 1:32, labels = c(season_weeks[c(4:32, 1:3)]), 
     las = 3, gap.axis = 0, tck = 0.5, lty = 0, cex.axis = 1.33)
rect(xleft = 0.5, xright = 13.5, ybottom = 0, ytop = 375, col = rgb(1, 0, 0, 0.2), border = NA)
rect(xleft = 13.5, xright = 32.5, ybottom = 0, ytop = 375, col = rgb(0, 1, 0, 0.2), border = NA)
text(6, -25, "Group 2", col = "black", cex = 1.3, xpd = TRUE)
text(22.5, -25, "Group 1", col = "black", cex = 1.3, xpd = TRUE)
#rect.hclust(SEhc_agg2, k = 2, border = 2:5)
dev.off()


```


```{r}

#using default values 
NEconst_clust <- constr.hclust(dist(t(NEbase_matrix)), chron = FALSE) #default with ward.d2 method
SEconst_clust <- constr.hclust(dist(t(SEbase_matrix)), chron = FALSE) #default with ward.d2 method

cutree(NEconst_clust, k =2)
cutree(SEconst_clust, k =2)
#SEconst_clust$order <- 1:32
#NEconst_clust$order <- 1:32

stats:::plot.hclust(NEconst_clust, hang = -1, bty = "n", sub = "", ylab = "",
                    xlab = "Week", main = "NE Aus : Response Clustering")

stats:::plot.hclust(NEconst_clust, hang = -1, labels = FALSE, bty = "n", sub = "", ylab = "",
                    xlab = "Week", main = "NE Aus : Response Clustering", axes = FALSE, cex.main = 2.0,
                    cex.lab = 1.5)
axis(2)
axis(1, at = 1:32, labels = c(season_weeks[1:32]), 
     las = 3, gap.axis = 0, tck = 0.5, lty = 0, cex.axis = 1.6)


stats:::plot.hclust(SEconst_clust, hang = -1, labels = FALSE, bty = "n", sub = "", ylab = "",
                    xlab = "Week", main = "SE Aus : Response Clustering", axes = FALSE, cex.main = 2.0,
                    cex.lab = 1.5)
axis(2)
axis(1, at = 1:32, labels = c(season_weeks[1:32]), 
     las = 3, gap.axis = 0, tck = 0.5, lty = 0, cex.axis = 1.6)

```


```{r}
#try pam from cluster
test_pam <- pam(t(SEbase_matrix), k =3, diss = TRUE)
clusplot(t(SEbase_matrix), test_pam$clustering, labels = 3)

summary(test_pam)
```



```{r test_fpd}
suppressMessages( library(FPDclustering))

temp_pdc <- PDC(data = t(NEbase_matrix), k = 2)
summary(temp_pdc)
temp_pdc$centers
temp_pdc$probability

temp_pdc$label

plot(temp_pdc)
```



