---
title: "cluster_work"
author: "Ryan Peterson"
date: "2024-10-18"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
suppressMessages(library(adespatial)) #for constr.hclust
suppressMessages(library(dendextend)) 

suppressMessages(library(scales))
```


```{r data_import}
setwd("~/CO_AUS/Aus_CO-main")

load( "ne_data.rda")
load( "se_data.rda")

load( "bounded_data.rda")
load( "data_matrix.rda")

load( "lag_list.rda")
```

```{r setup}
season_weeks <- c(35:52, 1:14)

season_weeks[21]
```


```{r 2019/2020_plots}
#plot for 2019/2020 wildfire season
neresp_new <- NEbase_matrix[19,]
seresp_new <- SEbase_matrix[19,]

#single season (2019/2020)
setwd("~/CO_AUS/Aus_CO-main/Interactions/Figures")

x_vals <- 1:32
y_lim <- range(neresp_new, seresp_new)

png(filename = "20192020Season.png",  width = 2600, height = 1800, res = 200)
set.panel(2,1)
plot(x_vals, neresp_new, type = "l", lwd = 2, ylim = y_lim, 
     ylab = "Atmospheric CO",
     xlab = "Week",  main = "NE Aus 2019/2020 Wildfire Season", axes = FALSE, 
     cex.main = 1.5, cex.lab = 1.5, cex.axis = 1.5)
box()
axis(2)
axis(1, at = 1:32, labels = c(season_weeks),
     las = 3, cex.axis = 1.5)
abline(h = 0, lty = 2)
abline(v = c(12.5, 17.5, 21.5), lty = 2, col = "red" )
text(5.5, -13, "Group 1", col = "red", cex = 1)
text(15, -13, "Group 2", col = "red", cex = 1)
text(19.5, -13, "Group 3", col = "red", cex = 1)
text(24.5, -13, "Group 4", col = "red", cex = 1)

plot(x_vals, seresp_new, type = "l", lwd = 2, ylim = y_lim, 
     ylab = "Atmospheric CO",
     xlab = "Week",  main = "SE Aus 2019/2020 Wildfire Season", axes = FALSE, 
     cex.main = 1.5, cex.lab = 1.5, cex.axis = 1.5)
box()
axis(2)
axis(1, at = 1:32, labels = c(season_weeks),
     las = 3, cex.axis = 1.5)
abline(h = 0, lty = 2)
abline(v = c(7.5, 16.5, 20.5), lty = 2, col = "red" )
text(3.5, -13, "Group 1", col = "red", cex = 1)
text(12, -13, "Group 2", col = "red", cex = 1)
text(18.5, -13, "Group 3", col = "red", cex = 1)
text(24.5, -13, "Group 4", col = "red", cex = 1)
dev.off()

```


```{r histograms}
#creating histograms
NE_resp <- resp_matrix[,1:32]
SE_resp <- resp_matrix[,33:64]

NEbase_matrix <- scale(resp_matrix[, 1:32], center = TRUE, scale = FALSE)
SEbase_matrix <- scale(resp_matrix[,33:64], center = TRUE, scale = FALSE)

setwd("~/CO_AUS/Aus_CO-main/Interactions/Figures")


#NE Aus hist
png(filename = "nehist.png",  width = 2600, height = 1800, res = 200)
set.panel(2,2)
hist(NEbase_matrix, breaks = 25, xlab = "Atmospheric CO", main = "")
hist(NEbase_matrix[,1:12], col = rgb(1, 0, 0, 0.2), breaks = 20, add=TRUE)
legend("topright", legend = c("Full Response", "Group 1"),
       fill = c(gray(0.9),  rgb(1, 0, 0, 0.3)))
title("NE Aus", adj = 0, cex.main = 1.5)

hist(NEbase_matrix, breaks = 20, xlab = "Atmospheric CO", main = "")
hist(NEbase_matrix[,13:17], col = rgb(0, 1, 0, 0.2), breaks = 20, add=TRUE)
legend("topright", legend = c("Full Response", "Group 2"),
       fill = c(gray(0.9),  rgb(0, 1, 0, 0.3)))

hist(NEbase_matrix, breaks = 20, xlab = "Atmospheric CO", main = "")
hist(NEbase_matrix[,18:21], col = rgb(0, 0, 1, 0.2), breaks = 20, add=TRUE)
legend("topright", legend = c("Full Response", "Group 3"),
       fill = c(gray(0.9),  rgb(0, 0, 1, 0.3)))

hist(NEbase_matrix, breaks = 20, xlab = "Atmospheric CO", main = "")
hist(NEbase_matrix[,22:32], col = rgb(1, 0.5, 0, 0.2), breaks = 18, add=TRUE)
legend("topright", legend = c("Full Response", "Group 4"),
       fill = c(gray(0.9),  rgb(1, 0.5, 0, 0.3)))
dev.off()


#SE Aus hist
png(filename = "sehist.png",  width = 2600, height = 1800, res = 200)
set.panel(2,2)
hist(SEbase_matrix, breaks = 24, xlab = "Atmospheric CO", main = "")
hist(SEbase_matrix[,1:7], col = rgb(1, 0, 0, 0.2), breaks = 20, add=TRUE)
legend("topright", legend = c("Full Response", "Group 1"),
       fill = c(gray(0.9),  rgb(1, 0, 0, 0.3)))
title("SE Aus", adj = 0, cex.main = 1.5)

hist(SEbase_matrix, breaks = 24, xlab = "Atmospheric CO", main = "")
hist(SEbase_matrix[,8:16], col = rgb(0, 1, 0, 0.2), breaks = 20, add=TRUE)
legend("topright", legend = c("Full Response", "Group 2"),
       fill = c(gray(0.9),  rgb(0, 1, 0, 0.3)))

hist(SEbase_matrix, breaks = 24, xlab = "Atmospheric CO", main = "")
hist(SEbase_matrix[,17:20], col = rgb(0, 0, 1, 0.2), breaks = 24, add=TRUE)
legend("topright", legend = c("Full Response", "Group 3"),
       fill = c(gray(0.9),  rgb(0, 0, 1, 0.3)))

hist(SEbase_matrix, breaks = 24, xlab = "Atmospheric CO", main = "")
hist(SEbase_matrix[,21:32], col = rgb(1, 0.5, 0, 0.2), breaks = 18, add=TRUE)
legend("topright", legend = c("Full Response", "Group 4"),
       fill = c(gray(0.9),  rgb(1, 0.5, 0, 0.3)))
dev.off()
```


```{r}

y_lim <- c(-25, max(NEbase_matrix, SEbase_matrix))

setwd("~/CO_AUS/Aus_CO-main/Interactions/Figures")

png(filename = "fulldata.png", width = 2600, height = 1800, res = 200)
set.panel(2,1)
boxplot(NEbase_matrix, ylim = y_lim, ylab = "Atmospheric CO", xlab = "Week",
        axes = FALSE, pch = 20, 
        cex.main = 1.5, cex.lab = 1.25, cex.axis = 1.5)
box()
axis(2)
axis(1, at = 1:32, labels = c(season_weeks),
     las = 3, cex.axis = 1.6)
abline(h = 0, lty = 2)
title("NE Aus", adj = 0, cex.main = 1.5)
abline(v = c(12.5, 17.5, 21.5), lty =2, col = "red")
text(7, -22, "Group 1", col = "red", cex =1)
text(15, -22, "Group 2", col = "red", cex = 1)
text(19.5, -22, "Group 3", col = "red", cex = 1)
text(27, -22, "Group 4", col = "red", cex = 1)

boxplot(SEbase_matrix, ylim = y_lim, ylab = "Atmospheric CO", xlab = "Week",
        axes = FALSE, pch = 20, 
        cex.main = 1.5, cex.lab = 1.25, cex.axis = 1.5)
box()
axis(2)
axis(1, at = 1:32, labels = c(season_weeks),
     las = 3, cex.axis = 1.6)
abline(h = 0, lty = 2)
abline(v = c(7.5, 16.5, 20.5), lty =2, col = "red")
title("SE Aus", adj = 0, cex.main = 1.5)
text(4, -22, "Group 1", col = "red", cex =1)
text(12, -22, "Group 2", col = "red", cex = 1)
text(18.5, -22, "Group 3", col = "red", cex = 1)
text(26, -22, "Group 4", col = "red", cex = 1)

dev.off()
```

```{r boxplots}

x_vals <- 1:32
y_lim <- range(neresp_new, seresp_new)

boxplot(SEbase_matrix, pch = 16)
boxplot(NEbase_matrix, pch = 16)

SE_group1 <- as.vector(SEbase_matrix[,1:7])
SE_group2 <- as.vector(SEbase_matrix[,8:16])
SE_group3 <- as.vector(SEbase_matrix[,17:20])
SE_group4 <- as.vector(SEbase_matrix[,21:32])

SEgroup_list <- list(SE_group1, SE_group2, SE_group3, SE_group4)
boxplot(SEgroup_list, pch = 16)


NE_group1 <- as.vector(NEbase_matrix[,1:12])
NE_group2 <- as.vector(NEbase_matrix[,13:17])
NE_group3 <- as.vector(NEbase_matrix[,18:21])
NE_group4 <- as.vector(NEbase_matrix[,22:32])

NEgroup_list <- list(NE_group1, NE_group2, NE_group3, NE_group4)
boxplot(NEgroup_list, pch = 16)

```



```{r test_block}
neresp_test <- resp_matrix[, 1:32]
subset_test <- neresp_test[, 31:32]

centered_subset <- scale(subset_test, center = TRUE, scale = FALSE)

d <- dist(t(neresp_test))
#dist(t(neresp_test), diag = TRUE)
dist(t(centered_subset))
dist(t(subset_test))

d[which.min(d)]
```


```{r baseline_hclust}
#using hclust function without considering time-constraints

#using single-linked
NEbase_matrix <- scale(resp_matrix[, 1:32], center = TRUE, scale = FALSE)
NEtest_clust <- hclust(dist(t(NEbase_matrix)), method = "average")
plot(NEtest_clust)

SEbase_matrix <- scale(resp_matrix[,33:64], center = TRUE, scale = FALSE)
SEtest_clust <- hclust(dist(t(SEbase_matrix)), method = "average")
plot(SEtest_clust)

```

```{r}
# Install and load dendextend
#install.packages("dendextend")
library(dendextend)

# Perform hierarchical clustering
hc <- hclust(dist(data))

# Convert hclust to a dendrogram
dend <- as.dendrogram(hc)

# Manually set the order (e.g., reverse the default order)
dend <- reorder(dend, order = rev(order.dendrogram(dend)))

# Plot the reordered dendrogram
plot(dend, main = "Manually Reordered Dendrogram")

```


```{r}
#clustering 

NEbase_matrix <- scale(resp_matrix[, 1:32], center = TRUE, scale = FALSE)
NEconst_clust <- constr.hclust(dist(t(NEbase_matrix)), chron = TRUE) #default with ward.d2 method

NEconst_clust$order <- 1:32


SEbase_matrix <- scale(resp_matrix[,33:64], center = TRUE, scale = FALSE)
SEconst_clust <- constr.hclust(dist(t(SEbase_matrix)), chron = TRUE) #default with ward.d2 method

SEconst_clust$order <- 1:32

```


```{r weeks/months}
bounded_resp_df[which(bounded_resp_df$week == 35), ] 
bounded_resp_df[which(bounded_resp_df$week == 36), ] 
```


```{r constr.hclust_test}

#setwd("~/CO_AUS/Aus_CO-main/Figures_Lasso")
setwd("~/CO_AUS/Aus_CO-main/Interactions/Figures")

#plot(dend, k = 5) #either, k = 5 or 6
png("NEcluster2.png", width = 2600, height = 1200, res = 200)
par(mar = c(5, 4, 4, 5) + 0.2, xpd = TRUE)  # Increase the right margin (fourth value) to make space for the legend
#par(mgp = c(3, -0.75, 0), xpd = TRUE)
stats:::plot.hclust(NEconst_clust, hang = -1, labels = FALSE, bty = "n", sub = "", ylab = "",
                    xlab = "Week", main = "NE Aus : Response Clustering", axes = FALSE, cex.main = 2.0,
                    cex.lab = 1.5)
#axis(2)
axis(1, at = 1:32, labels = c(season_weeks[1:32]), 
     las = 3, gap.axis = 0, tck = 0.5, lty = 0, cex.axis = 1.6)
rect(xleft = 0.5, xright = 12.5, ybottom = 0, ytop = 50, col = rgb(1, 0, 0, 0.2), border = NA)
#rect(xleft = 3.5, xright = 8.5, ybottom = 0, ytop = 50, col = rgb(0, 1, 0, 0.2), border = NA)
#rect(xleft = 8.5, xright = 12.5, ybottom = 0, ytop = 50, col = rgb(0, 0, 1, 0.2), border = NA)
rect(xleft = 12.5, xright = 17.5, ybottom = 0, ytop = 50, col = rgb(0, 1, 0, 0.2), border = NA)
rect(xleft = 17.5, xright = 21.5, ybottom = 0, ytop = 50, col = rgb(0, 0, 1, 0.2), border = NA)
rect(xleft = 21.5, xright = 32.5, ybottom = 0, ytop = 50, col = rgb(1, 0.5, 0, 0.2), border = NA)
text(6.5, -5, "Group 1", col = "black", cex = 1.5, xpd = TRUE)
text(14.5, -5, "Group 2", col = "black", cex = 1.5, xpd = TRUE)
text(19.5, -5, "Group 3", col = "black", cex = 1.5, xpd = TRUE)
text(26.5, -5, "Group 4", col = "black", cex = 1.5, xpd = TRUE)
dev.off()


#plot(SEconst_clust, k = 5) #either, k = 4 or 5
png("SEcluster2.png", width = 2600, height = 1200, res = 200)
par(mar = c(5, 4, 4, 5) + 0.2, xpd = TRUE)  # Increase the right margin (fourth value) to make space for the legend
#par(mgp = c(3, -0.75, 0))
stats:::plot.hclust(SEconst_clust, hang = -1, labels = FALSE, bty = "n", sub = "", ylab = "",
                    xlab = "Week", main = "SE Aus : Response Clustering", axes = FALSE, cex.main = 2.0,
                    cex.lab = 1.5)
axis(1, at = 1:32, labels = c(season_weeks[1:32]), 
     las = 3, gap.axis = 0, tck = 0.5, lty = 0, cex.axis = 1.6)
rect(xleft = 0.5, xright = 7.5, ybottom = 0, ytop = 50, col = rgb(1, 0, 0, 0.2), border = NA)
#rect(xleft = 3.5, xright = 7.5, ybottom = 0, ytop = 50, col = rgb(0, 1, 0, 0.2), border = NA)
rect(xleft = 7.5, xright = 16.5, ybottom = 0, ytop = 50, col = rgb(0, 1, 0, 0.2), border = NA)
rect(xleft = 16.5, xright = 20.5, ybottom = 0, ytop = 50, col = rgb(0, 0, 1, 0.2), border = NA)
rect(xleft = 20.5, xright = 32.5, ybottom = 0, ytop = 50, col = rgb(1, 0.5, 0, 0.2), border = NA)
text(4, -5, "Group 1", col = "black", cex = 1.5)
text(12, -5, "Group 2", col = "black", cex = 1.5)
text(18.5, -5, "Group 3", col = "black", cex = 1.5)
text(26.5, -5, "Group 4", col = "black", cex = 1.5)
dev.off()

```

```{r clustered_data}
#new matrices (eventually convert to list of df's or matrices)

#NEAus
NEAus_1 <- NEbase_matrix[ ,1:3]
NEAus_2 <- NEbase_matrix[ ,4:8]
NEAus_3 <- NEbase_matrix[ ,9:12]
NEAus_4 <- NEbase_matrix[ ,13:17]
NEAus_5 <- NEbase_matrix[ ,18:32]

#SEAus
SEAus_1 <- SEbase_matrix[ ,1:3]
SEAus_2 <- SEbase_matrix[ ,4:7]
SEAus_3 <- SEbase_matrix[ ,8:16]
SEAus_4 <- SEbase_matrix[ ,17:20]
SEAus_5 <- SEbase_matrix[ ,21:32]
```


```{r response_plots}
line_col <- rainbow(10)
y_range <- range(NEAus_2)
plot(1:5, NEAus_2[1,], type = "l", lwd = 2, xaxt = "n", ylim = y_range,
     ylab = "Anomaly (Total Column CO)", xlab = "Weeks")
axis(1, at=1:5, labels = season_weeks[4:8])
for (i in 2:7) {
  lines(1:5, NEAus_2[i,], lwd = 2, col = line_col[i])
}

```


Additional work, not currently needed.

Test a naive single-linked agglomeration clustering

Then:
-create implementations for:
--single-linkage
--complete-linkage
--pair group with arithmetic mean (un-weighted and weighted)


```{r test_function}

#function to implement the single link agglomeration clustering algorithm
agglcluster_sl <- function() {
  
  
}

#internal function for subdiag (distance vector) update
vector_update <- function(dist_matrix, index_n, subdiag, min_ind) {
  #get updates from distance matrix
  min_loc <- index_n[1, ] 

  #neighborhood checks (add in elif boundary checks)
  #TODO: assign min_ind and min_loc
  low <- min_ind-1
  upr <- min_ind+1
  
  
  d_1 <- dist_matrix[min_loc[1], min_loc[2] - 1] #(49,51)
  d_2 <- dist_matrix[min_loc[1] + 1, min_loc[2]] #(50,52)

  d1_name <- colnames(dist_matrix)[ min_loc[2] - 1]
  d2_name <- rownames(dist_matrix)[min_loc[1] + 1]

  #update distance vector (originally the subdiagonal)
  sub_names <- names(subdiag)
  min_name <- sub_names[min_ind]

  
  t1 <- min(d_1, subdiag[min_ind-1])
  t1_name <- paste0("(",d1_name,",",min_name,")")
  t2 <- min(d_2, subdiag[min_ind+1])
  t2_name <- paste0("(",min_name,",",d2_name,")")

  temp_subdiag <- subdiag
  temp_subdiag[min_ind-1] <- t1
  sub_names[min_ind-1] <- t1_name

  temp_subdiag[min_ind+1] <- t2
  sub_names[min_ind+1] <- t2_name

  temp_subdiag <- temp_subdiag[-min_ind]
  sub_names <- sub_names[-min_ind]
  names(temp_subdiag) <- sub_names

  return(temp_subdiag)
}


```


```{r test_block}


#setup section:
base_matrix <- scale(resp_matrix[, 1:19], center = TRUE, scale = FALSE)
colnames(base_matrix) <- substring(colnames(base_matrix), 6)

#distance matrix
d <- dist(t(base_matrix))
temp_matrix <- as.matrix(d)
#TODO: update the name change as
dist_matrix <- as.matrix(d)

#loop 1 starts here
##sub-diagonal 
subdiag <- temp_matrix[col(temp_matrix) == row(temp_matrix) + 1]

#subdiag colnames as pair (,)
base_names <- colnames(base_matrix)
sub_names <- c()

n <- length(base_names)
for (i in 1:n-1) {
  first <- base_names[i]
  second <- base_names[i+1]
  sub_names <- c(sub_names, paste0("(",first,",",second,")"))
}

sub_names <- sub_names[-1]
names(subdiag) <- sub_names

subdiag

dend_df <- as.data.frame(matrix(NA, ncol = 2))
for (i in 1:3) {
  min_n <- min(subdiag)
  min_ind <- which.min(subdiag)
  min_name <- sub_names[min_ind]
  index_n <- which(temp_matrix == min_n, arr.ind = TRUE)

  height_new <- min_n/2
  
  dend_df <- rbind(dend_df, c(height_new, min_name))

  subdiag <- vector_update(dist_matrix, index_n, subdiag, min_ind)
  print(subdiag)
}


#TODO: pick up after the next step since we are now connecting data that will have a lower height than an already connected section. 

#either address the above issue or change this some average linkage methods.
#perform some comparisons with the first distance matrix update using averages
#we also need elifs around the boundaries to avoid out of bounds issues.


```


```{r minimizing_test}
min_n <- min(subdiag)
min_ind <- which.min(subdiag)
min_name <- sub_names[min_ind]
index_n <- which(temp_matrix == min_n, arr.ind = TRUE)
```


```{r function_tests}
#loop 2 (loop n+1)
min_loc <- index_n[1, ] 

min_loc[1]
min_loc[2]
names(subdiag)
subdiag[min_ind-1]
subdiag[min_ind+1]

#neighborhood checks (add in elif boundary checks)

#get lengths from matrix/vector
n_1 <- length(subdiag)
n_row <- nrow(dist_matrix)
n_col <- ncol(dist_matrix)


#TODO: assign min_ind and min_loc
low <- min_ind-1
upr <- min_ind+1


if (low < 1) {
  
}

d_1 <- dist_matrix[min_loc[1], min_loc[2] - 1] #(49,51)
d_2 <- dist_matrix[min_loc[1] + 1, min_loc[2]] #(50,52)

d1_name <- colnames(dist_matrix)[ min_loc[2] - 1]
d2_name <- rownames(dist_matrix)[min_loc[1] + 1]

#update distance vector (originally the subdiagonal)
sub_names <- names(subdiag)
min_name <- sub_names[min_ind]


t1 <- min(d_1, subdiag[min_ind-1])
t1_name <- paste0("(",d1_name,",",min_name,")")
t2 <- min(d_2, subdiag[min_ind+1])
t2_name <- paste0("(",min_name,",",d2_name,")")

temp_subdiag <- subdiag
temp_subdiag[min_ind-1] <- t1
sub_names[min_ind-1] <- t1_name

temp_subdiag[min_ind+1] <- t2
sub_names[min_ind+1] <- t2_name

temp_subdiag <- temp_subdiag[-min_ind]
sub_names <- sub_names[-min_ind]
names(temp_subdiag) <- sub_names
```


```{r }
#minimum check (variation)

#min of subdiag, location, and name
min_n <- min(subdiag)
min_ind <- which.min(subdiag)
min_name <- sub_names[min_ind]
index_n <- which(temp_matrix == min_n, arr.ind = TRUE)

#base_matrix[ ,index_n[1,]] #not needed (delete later)

#height
height_new <- min_n/2

#update
#TODO: update height/dendogram df (output)
subdiag <- vector_update(dist_matrix, index_n, subdiag, min_ind)
subdiag

min_n <- min(subdiag)
min_ind <- which.min(subdiag)
min_name <- sub_names[min_ind]
index_n <- which(temp_matrix == min_n, arr.ind = TRUE)

height_new <- min_n/2

subdiag <- vector_update(dist_matrix, index_n, subdiag, min_ind)
subdiag
```


```{r naive_single}
#using L2 distance

#disjoint of L(0) = 0
#set-up for week 35:52 and 1.
base_matrix <- scale(resp_matrix[, 1:19], center = TRUE, scale = FALSE)

#TODO: create df and/or create a new col names for the matrix
## change colnames to only number so we can track updates better

#test for this change:
upd_matrix <- base_matrix
colnames(upd_matrix) <- substring(colnames(base_matrix), 6)

d <- dist(t(base_matrix))

minval <- min(d)

mindex <- which(as.matrix(d) == minval, arr.ind = TRUE)

temp_matrix <- as.matrix(d)
#diag(temp_matrix, 1)

#TODO: plot this (add weeks in the half points (0.5, 1.5, ...))
subdiag <- temp_matrix[row(temp_matrix) == col(temp_matrix) + 1]
plot(subdiag, pch = 16) 

min_n <- min(subdiag) #min neighboring

index_n <- which(as.matrix(d) == min_n, arr.ind = TRUE)

base_matrix[ ,index_n[1,]]

#height 
height_1 <- dist(t(base_matrix[ ,index_n[1,]]))/2

which(col(temp_matrix) == index_n[1, ],  arr.ind = TRUE)



```

Compare below with a mean of $(a,b)$,
$$\min(D_1(a,c), D_1(b,c))$$

