---
title: "correlation_iod"
author: "Ryan Peterson"
date: "2025-09-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library}
suppressMessages( library(hierNet)) #yes
suppressMessages( library(glmnet)) #test ridge regression for coefs
suppressMessages( library(RAMP)) #maybe
suppressMessages( library(MASS)) #for lm.ridge

suppressMessages( library(foreach)) #parallelization setup
suppressMessages( library(parallel))
suppressMessages( library(doParallel))

suppressMessages( library( lubridate)) #you know why
suppressMessages( library( colorspace)) #for some color alternatives
suppressMessages( library( fields)) #for set.panel() and others 
suppressMessages( library(ggpubr)) #nice tables for dfs (uses ggplot)

suppressMessages( library( caret)) #for confusion matrix

suppressMessages( library( tictoc)) #some timing

#time series ploting
#TODO: figure out which is necessary
suppressMessages(library(plotly))
suppressMessages(library(TSstudio))
suppressMessages(library(xts))

```

```{r data_load}
#and functions
# Data Set-Up
setwd("~/CO_AUS/Aus_CO-main/Interactions")

load( "Data/ne_data.rda")
load( "Data/se_data.rda")
load( "Data/bounded_data.rda")
load( "Data/data_matrix.rda")
load( "Data/lag_list.rda")
load( "Data/data_quantile.rda")

#functions:
#source("group_functions.R") #grouping/clustering
source("group_functionsNew.R") #new groupings
source("refit_functions.R") #coef/refit functions


setwd("~/CO_AUS/Aus_CO-main/Interactions_New")
load( "IOD_lag.rda")

setwd("~/CO_AUS/Aus_CO-main/pIOD")
load( "weeklypIOD.rda") #new.pIOD.df
```

# Additional Data Cleaning

```{r pIOD_cleaning}
pIOD.df <- new.pIOD.df[which(new.pIOD.df$year >= 2000 & new.pIOD.df$year <= 2020), ]
max.index <- which(pIOD.df$year == 2020 & pIOD.df$week == 14)
pIOD.df <- pIOD.df[1:max.index,]

pIOD.df <- pIOD.df[-which(pIOD.df$week == 53), ] #remove week 53
rownames(pIOD.df) <- NULL

```



# Time-Series Work


## Time-Series Figures

```{r TS_figs}
jja.ind <- which(month(bounded_pred_df$time) %in% c(6,7,8))
son.ind <- which(month(bounded_pred_df$time) %in% c(9,10,11))

pIOD.df$s.index <- scale(pIOD.df$s.index)
pIOD.df$m.index <- scale(pIOD.df$m.index)

#jja
dmi.jja <- bounded_pred2_df[jja.ind, ]
piod.jja <- pIOD.df[jja.ind,]
#son
dmi.son <- bounded_pred2_df[son.ind, ]
piod.son <- pIOD.df[son.ind,]

s.index.son  <- piod.son$s.index
etio.son <- dmi.son$etio.anomaly
strong.range <- range(etio.son, s.index.son)

m.index.son  <- piod.son$m.index
wtio.son <- dmi.son$wtio.anomaly
mod.range <- range(wtio.son, m.index.son)

son.dmi <- dmi.son$dmi.anomaly

#fig setup
years.pIOD <- 2000:2019

n.son <- length(son.ind)
#length(s.index.son)
son.div <- which(diff(piod.son$year) !=0 ) + 0.5
son.div.full <-  c(0.5, son.div, n.son+0.5)

year.loc <- (head(son.div.full, -1) + tail(son.div.full, -1))/2


setwd("~/CO_AUS/Aus_CO-main/Interactions_New/Figures")

png(filename = "son_strongIOD.png", width = 2600, height = 1300, res = 250)
par(mar = c(5, 5, 3, 7.3))
plot(1:length(s.index.son), s.index.son, type = "l",  col = "firebrick", ylim=strong.range,
     ylab = "Index", xlab = "Year",
           axes = FALSE)
axis(1, at = year.loc, labels = years.pIOD, tick = FALSE, cex.axis = 0.66)
axis(2)                      
box()
lines(1:length(etio.son), -etio.son, col = "royalblue4")
title("SON Weekly - Strong pIOD", adj = 0)
abline(h = 0, lty  =2)
abline(v=son.div.full, lty = 3, lwd = 0.75, col = "gray35")
legend("topright",
       legend = c("S-Index", "-ETIO"),
       lty    = c(1,1),                 # line type
       lwd    = 1.33,                 # line width
       col    = c( "firebrick", "royalblue4"),
       #bty    = "n",               # no box; remove if you want a box
       inset  = c(-0.17, 0 ),
       xpd = TRUE)
dev.off()

png(filename = "son_modIOD.png", width = 2600, height = 1300, res = 250)
par(mar = c(5, 5, 3, 7.3))
plot(1:length(m.index.son), m.index.son, type = "l",  col = "forestgreen", ylim=mod.range,
     ylab = "Index", xlab = "Year",
           axes = FALSE)
axis(1, at = year.loc, labels = years.pIOD, tick = FALSE, cex.axis = 0.66)
axis(2)                      
box()
lines(1:length(wtio.son), wtio.son, col = "magenta4")
title("SON Weekly - Moderate pIOD", adj = 0)
abline(h = 0, lty  =2)
abline(v=son.div.full, lty = 3, lwd = 0.75, col = "gray35")
legend("topright",
       legend = c("M-Index", "WTIO"),
       lty    = c(1,1),                 # line type
       lwd    = 1.33,                 # line width
       col    = c( "forestgreen", "magenta4"),
       #bty    = "n",               # no box; remove if you want a box
       inset  = c(-0.17, 0 ),
       xpd = TRUE)
dev.off()
```


```{r}
mod.range2 <- range(wtio.son, m.index.son, son.dmi)

setwd("~/CO_AUS/Aus_CO-main/Interactions_New/Figures")

png(filename = "son_modIOD2.png", width = 2600, height = 1300, res = 250)
par(mar = c(5, 5, 3, 7.3))
plot(1:length(m.index.son), m.index.son, type = "l",  col = "forestgreen", ylim=mod.range2,
     ylab = "Index", xlab = "Year",
           axes = FALSE)
axis(1, at = year.loc, labels = years.pIOD, tick = FALSE, cex.axis = 0.66)
axis(2)                      
box()
lines(1:length(wtio.son), wtio.son, col = "magenta4")
lines(1:length(son.dmi), son.dmi, col = "orangered3", lty = 4)
title("SON Weekly - Moderate pIOD", adj = 0)
abline(h = 0, lty  =2)
abline(v=son.div.full, lty = 3, lwd = 0.75, col = "gray35")
legend("topright",
       legend = c("M-Index", "WTIO", "DMI"),
       lty    = c(1,1,4),                 # line type
       lwd    = 1.33,                 # line width
       col    = c( "forestgreen", "magenta4", "orangered3"),
       #bty    = "n",               # no box; remove if you want a box
       inset  = c(-0.17, 0 ),
       xpd = TRUE)
dev.off()
```

```{r jja_plots}
s.index.jja  <- piod.jja$s.index
etio.jja <- dmi.jja$etio.anomaly
strong.rangejja <- range(etio.jja, s.index.jja)

m.index.jja  <- piod.jja$m.index
wtio.jja <- dmi.jja$wtio.anomaly
mod.rangejja <- range(wtio.jja, m.index.jja)

jja.dmi <- dmi.jja$dmi.anomaly

#fig setup
years.pIOD <- 2000:2019

n.jja <- length(jja.ind)
#length(s.index.son)
jja.div <- which(diff(piod.jja$year) !=0 ) + 0.5
jja.div.full <-  c(0.5, jja.div, n.jja+0.5)

year.loc <- (head(jja.div.full, -1) + tail(jja.div.full, -1))/2



par(mar = c(5, 5, 3, 7.3))
plot(1:length(s.index.jja), s.index.jja, type = "l",  col = "firebrick", ylim=strong.rangejja,
     ylab = "Index", xlab = "Year",
           axes = FALSE)
axis(1, at = year.loc, labels = years.pIOD, tick = FALSE, cex.axis = 0.66)
axis(2)                      
box()
lines(1:length(etio.jja), -etio.jja, col = "royalblue4")
title("JJA Weekly - Strong pIOD", adj = 0)
abline(h = 0, lty  =2)
abline(v=jja.div.full, lty = 3, lwd = 0.75, col = "gray35")
legend("topright",
       legend = c("S-Index", "-ETIO"),
       lty    = c(1,1),                 # line type
       lwd    = 1.33,                 # line width
       col    = c( "firebrick", "royalblue4"),
       #bty    = "n",               # no box; remove if you want a box
       inset  = c(-0.17, 0 ),
       xpd = TRUE)
```



## ACF & CCF

```{r ts_dataprep}
NEaus_ts <- ts(bounded_resp_df$NE_Aus_anomaly_co, 
               start = as.Date(min(bounded_resp_df$time)), frequency = 52)
SEaus_ts <- ts(bounded_resp_df$SE_Aus_anomaly_co, 
               start = as.Date(min(bounded_resp_df$time)), frequency = 52)

nino_ts <- ts(bounded_pred_df$nino.anomaly, 
              start = as.Date(min(bounded_pred_df$time)), frequency = 52)
dmi_ts <- ts(bounded_pred_df$dmi.anomaly, 
             start = as.Date(min(bounded_pred_df$time)), frequency = 52)
tsa_ts <- ts(bounded_pred_df$tsa.anomaly, 
             start = as.Date(min(bounded_pred_df$time)), frequency = 52)
aao_ts <- ts(bounded_pred_df$aao.anomaly, 
             start = as.Date(min(bounded_pred_df$time)), frequency = 52)

olrNE_ts <- ts(bounded_olr_df$NE_anom, 
              start = as.Date(min(bounded_olr_df$Date)), frequency = 52)
olrSE_ts  <- ts(bounded_olr_df$SE_anom, 
              start = as.Date(min(bounded_olr_df$Date)), frequency = 52)

wtio_ts <- ts(bounded_pred2_df$wtio.anomaly, 
              start = as.Date(min(bounded_pred_df$time)), frequency = 52)
etio_ts <- ts(bounded_pred2_df$etio.anomaly, 
              start = as.Date(min(bounded_pred_df$time)), frequency = 52)
```


```{r acf}

acf(NEaus_ts, type = "correlation", 
    lag = 52, main = "NE Aus")

acf(SEaus_ts, type = "correlation", 
    lag = 52, main = "SE Aus")

acf(nino_ts, type = "correlation", 
    lag = 52, main = "Nino")

acf(dmi_ts, type = "correlation", 
    lag = 52, main = "DMI")

acf(tsa_ts, type = "correlation", 
    lag = 52, main = "TSA")

acf(aao_ts, type = "correlation", 
    lag = 52, main = "AAO")

acf(olrNE_ts, type = "correlation", 
    lag = 52, main = "OLR - NE Aus")

acf(olrSE_ts, type = "correlation", 
    lag = 52, main = "OLR - SE Aus")

acf(wtio_ts, type = "correlation", 
    lag = 52, main = "WTIO")

acf(etio_ts, type = "correlation", 
    lag = 52, main = "ETIO")


#detrend 
detr_NE <- lm(NEaus_ts ~ time(NEaus_ts))
detr_SE <- lm(SEaus_ts ~ time(SEaus_ts))

resid_NE <- resid(detr_NE)
resid_SE <- resid(detr_SE)

```

```{r ccf}
#OLR NE Aus
ccf(as.numeric(olrNE_ts), as.numeric(nino_ts), type = "correlation", 
    lag = 52, main = " OLR:NE Aus & Nino")

ccf(as.numeric(olrNE_ts), as.numeric(dmi_ts), type = "correlation", 
    lag = 52, main = " OLR:NE Aus & DMI")

ccf(as.numeric(olrNE_ts), as.numeric(wtio_ts), type = "correlation", 
    lag = 52, main = " OLR:NE Aus & WTIO")

ccf(as.numeric(olrNE_ts), as.numeric(etio_ts), type = "correlation", 
    lag = 52, main = " OLR:NE Aus & ETIO")

ccf(as.numeric(olrNE_ts), as.numeric(aao_ts), type = "correlation", 
    lag = 52, main = " OLR:NE Aus & SAM")

#OLR SE Aus
ccf(as.numeric(olrSE_ts), as.numeric(nino_ts), type = "correlation", 
    lag = 52, main = " OLR:SE Aus & Nino")

ccf(as.numeric(olrSE_ts), as.numeric(dmi_ts), type = "correlation", 
    lag = 52, main = " OLR:SE Aus & DMI")

ccf(as.numeric(olrSE_ts), as.numeric(wtio_ts), type = "correlation", 
    lag = 52, main = " OLR:SE Aus & WTIO")

ccf(as.numeric(olrSE_ts), as.numeric(etio_ts), type = "correlation", 
    lag = 52, main = " OLR:SE Aus & ETIO")

ccf(as.numeric(olrSE_ts), as.numeric(aao_ts), type = "correlation", 
    lag = 52, main = " OLR:SE Aus & SAM")

#WTIO 
ccf(as.numeric(wtio_ts), as.numeric(nino_ts), type = "correlation", 
    lag = 52, main = "WTIO & Nino", ylim = c(-1,1))

ccf(as.numeric(wtio_ts), as.numeric(aao_ts), type = "correlation", 
    lag = 52, main = "WTIO & SAM")

ccf(as.numeric(wtio_ts), as.numeric(NEaus_ts), type = "correlation", 
    lag = 52, main = "WTIO & NE Aus")

ccf(as.numeric(wtio_ts), as.numeric(SEaus_ts), type = "correlation", 
    lag = 52, main = "WTIO & SE Aus")

#ETIO
ccf(as.numeric(etio_ts), as.numeric(nino_ts), type = "correlation", 
    lag = 52, main = "ETIO & Nino", ylim = c(-1,1))

ccf(as.numeric(etio_ts), as.numeric(aao_ts), type = "correlation", 
    lag = 52, main = "ETIO & SAM")

ccf(as.numeric(NEaus_ts), as.numeric(etio_ts), type = "correlation", 
    lag = 52, main = "NE Aus & ETIO")

ccf(as.numeric(resid_SE), as.numeric(etio_ts), type = "correlation", 
    lag = 52, main = "SE Aus & ETIO")

ccf(as.numeric(dmi_ts), as.numeric(resid_SE), type = "correlation", 
    lag = 52, main = "SE Aus & DMI")

#TSA
ccf(as.numeric(aao_ts), as.numeric(tsa_ts), type = "correlation", 
    lag = 52, main = "SAM & TSA")

```


```{r}
ccf(as.numeric(olrNE_ts), as.numeric(nino_ts), type = "correlation", 
    lag = 52, main = " OLR:NE Aus & Nino", xlim = c(0,52))

ccf(as.numeric(olrSE_ts), as.numeric(etio_ts), type = "correlation", 
    lag = 52, main = " OLR:SE Aus & ETIO", xlim = c(0,52))


```

### OLR and Others

x[t+k] and y[t]

```{r}
ccf.lim <- c(-0.2, 0.4)

setwd("~/CO_AUS/Aus_CO-main/Interactions_New/Figures")

#Ne OLr
png(filename = "neolr_nino.png", width = 2400, height = 1200, res = 250)
par(mar = c(5, 5, 3, 3))
ccf(as.numeric(olrNE_ts), as.numeric(nino_ts), type = "correlation", 
    lag = 52, ylab = "cross-correlation", main = "",
    xlim = c(0,52), ylim = ccf.lim)
title("NE Aus : OLR & Nino", adj = 0)
dev.off()

png(filename = "neolr_dmi.png", width = 2400, height = 1200, res = 250)
par(mar = c(5, 5, 3, 3))
ccf(as.numeric(olrNE_ts), as.numeric(dmi_ts), type = "correlation", 
    lag = 52, ylab = "cross-correlation", main = "",
    xlim = c(0,52), ylim = ccf.lim)
title("NE Aus : OLR & DMI", adj = 0)
dev.off()

png(filename = "neolr_tsa.png", width = 2400, height = 1200, res = 250)
par(mar = c(5, 5, 3, 3))
ccf(as.numeric(olrNE_ts), as.numeric(tsa_ts), type = "correlation", 
    lag = 52, ylab = "cross-correlation", main = "",
    xlim = c(0,52), ylim = ccf.lim)
title("NE Aus : OLR & TSA", adj = 0)
dev.off()

png(filename = "neolr_aao.png", width = 2400, height = 1200, res = 250)
par(mar = c(5, 5, 3, 3))
ccf(as.numeric(olrNE_ts), as.numeric(aao_ts), type = "correlation", 
    lag = 52, ylab = "cross-correlation", main = "",
    xlim = c(0,52), ylim = ccf.lim)
title("NE Aus : OLR & SAM (AAO)", adj = 0)
dev.off()

#se olr
png(filename = "seolr_nino.png", width = 2400, height = 1200, res = 250)
par(mar = c(5, 5, 3, 3))
ccf(as.numeric(olrSE_ts), as.numeric(nino_ts), type = "correlation", 
    lag = 52, main = "",
    ylab = "cross-correlation",
    xlim = c(0,52), ylim = ccf.lim)
title("SE Aus : OLR & Nino", adj = 0)
dev.off()

png(filename = "seolr_tsa.png", width = 2400, height = 1200, res = 250)
par(mar = c(5, 5, 3, 3))
ccf(as.numeric(olrSE_ts), as.numeric(tsa_ts), type = "correlation", 
    lag = 52, main = "",
    ylab = "cross-correlation",
    xlim = c(0,52), ylim = ccf.lim)
title("SE Aus : OLR & TSA", adj = 0)
dev.off()

png(filename = "seolr_aao.png", width = 2400, height = 1200, res = 250)
par(mar = c(5, 5, 3, 3))
ccf(as.numeric(olrSE_ts), as.numeric(aao_ts), type = "correlation", 
    lag = 52, main = "",
    ylab = "cross-correlation",
    xlim = c(0,52), ylim = ccf.lim)
title("SE Aus : OLR & SAM (AAO)", adj = 0)
dev.off()

png(filename = "seolr_dmi.png", width = 2400, height = 1200, res = 250)
par(mar = c(5, 5, 3, 3))
ccf(as.numeric(olrSE_ts), as.numeric(dmi_ts), type = "correlation", 
    lag = 52, main = "",
    ylab = "cross-correlation",
    xlim = c(0,52), ylim = ccf.lim)
title("SE Aus : OLR & DMI", adj = 0)
dev.off()

png(filename = "seolr_wtio.png", width = 2400, height = 1200, res = 250)
par(mar = c(5, 5, 3, 3))
ccf(as.numeric(olrSE_ts), as.numeric(wtio_ts), type = "correlation", 
    lag = 52, main = "",
    ylab = "cross-correlation",
    xlim = c(0,52), ylim = ccf.lim)
title("SE Aus : OLR & WTIO", adj = 0)
dev.off()

png(filename = "seolr_etio.png", width = 2400, height = 1200, res = 250)
par(mar = c(5, 5, 3, 3))
ccf(as.numeric(olrSE_ts), as.numeric(etio_ts), type = "correlation", 
    lag = 52, main = "",
    ylab = "cross-correlation",
    xlim = c(0,52), ylim = ccf.lim)
title("SE Aus : OLR & ETIO", adj = 0)
dev.off()

```


## Updated EDA TS Figures
(time series (predictor) figures for final paper)

```{r }
#TODO: combine dataframes/sets to be one single predictor df
pred_anoms <- bounded_pred_df[,-c(6,7)]
pred_anoms$NEolr.anomaly <- bounded_olr_df$NE_anom
pred_anoms$SEolr.anomaly <- bounded_olr_df$SE_anom
pred_anoms$week <- bounded_pred_df$week

#TODO: adjust these colors as need
top.color <- "coral1"
bottom.color <- "skyblue1"

names(pred_anoms) <- c("time", 
                            "NINO", "DMI", "TSA", "SAM", "NE OLR", "SE OLR", "week")

y.lab.vals <- c("Anomaly (\u00B0C)",
                "Anomaly (\u00B0C)",
                "Anomaly (\u00B0C)",
                "Anomaly",
                "Anomaly",
                "Anomaly")
```


```{r}
predictors <- pred_anoms

pred_nams <- names(predictors)

for (i in 3:length(predictors)-1){
  predictors[,i] <- (predictors[,i] - mean(predictors[,i]))/ sd(predictors[,i]) #standardize
}

first.date <- min(predictors$time)
last.date <- max(predictors$time)

time <- predictors$time
time.range <- c(first.date, last.date)
x.ticks <- seq(year(time.range[1]), year(time.range[2]), by = 1) #can also be done with lubridate floor
x.ticks.new <- c(x.ticks, x.ticks[21] + 1)

x.ticks <- ymd(paste0(x.ticks, "01", "01"))
#c(x_ticks, last.date) #get last date

#extend to 2021 (or mid 2020)
x.ticks.new <- ymd(paste0(x.ticks.new, "01", "01"))

```

```{r fig_predTS}


#get full predictor data range
pred.max <- max(round(range(predictors[,2:7])))
pred.range <- c(-pred.max, pred.max)

setwd("~/CO_AUS/Aus_CO-main/Interactions_New/Figures")


#PC1 vs DMI
png(filename = "preds_tes.png", width = 2500, height = 3000, res = 300)

par(mfrow = c(6, 1))
par(mar = c(0,2,0,0))
par(oma = c(1.5,2,0,0))
par(mgp = c(2.75,1,0))
for (i in 2:7){
  this.pred <- (predictors[,i])
  temp.time <- as.Date(predictors$time)
  #temp.time <- gsub("-", "", temp.time)
  
  y.tick.max <- max(round(range(this.pred)))
  # y.tick.max <- 4
  y.tick.max.lab <- y.tick.max / 2
  y.ticks <- seq(-y.tick.max, y.tick.max, by = 1)
  y.tick.labs <- c(-y.tick.max.lab, 0, y.tick.max.lab)
  
  plot(temp.time, this.pred, type = "l", col = "black", lwd = 2,
       xaxt = "n", xlab = "",
       yaxt = "n", ylab = y.lab.vals[i-1], col.lab = "black",
       xlim = c(as.Date(time.range[1]) + months(7), as.Date(time.range[2]) - months(7)),
       ylim = pred.range, bty = "n", cex.lab = 1.25,  xpd = NA)
  
      if (i == 7){
        text(x = x.ticks[-length(x.ticks)] + months(6),
         y = range(y.ticks)[1]-0.7,
         labels = year(x.ticks[-length(x.ticks)]),
         cex = 1.3, col = "black", xpd = NA)
      }
  
    
     if (i == 2){ abline(v = x.ticks[1:(length(x.ticks))],
                      lty = 2, col = "grey", lwd = 2, xpd = NA) }
  
      axis(side = 2, at = y.tick.labs, labels = y.tick.labs, col = NA, 
      col.ticks = "black", col.axis = "black")
  
      abline(h = 0, lty = 1, col = "grey", lwd = 1)
  
      over <- this.pred >= 0
      this.pred.over <- this.pred
      this.pred.over[!over] <- 0
      this.pred.under <- this.pred
      this.pred.under[over] <- 0
  
      envelopePlot(x1 = temp.time,
               y1 = this.pred.over,
               x2 = temp.time,
               y2 = rep(0, length(time)),
               col = alpha(top.color, 0.7),
               lineCol = NA)
      envelopePlot(x1 = temp.time,
               y1 = this.pred.under,
               x2 = temp.time,
               y2 = rep(0, length(time)),
               col = alpha(bottom.color, 0.7),
               lineCol = NA)
      
        
  td <- y.tick.labs[3]
  #td <- 2    
  legend(x = c(ymd("1999-05-01"), ymd("2001-10-01")),
         y = c(1.5*td, 2.75*td),
         # legend = toupper(pred.names[i]),
         legend = pred_nams[i],
         box.col = "white", bg = "white",
         # adj = c(0., 0.6),
         xpd = NA, text.col = "grey40", cex = 1.75)
  
}
dev.off()
```


```{r repeat_wtio_etio}
#compare dmi, wtio, etio
#TODO: combine dataframes/sets to be one single predictor df
predanoms_new <- bounded_pred_df[,c(1,3)]
predanoms_new$wtio.anomaly <- bounded_pred2_df$wtio.anomaly
predanoms_new$etio.anomaly <- bounded_pred2_df$etio.anomaly
predanoms_new$week <- bounded_pred_df$week

#TODO: adjust these colors as need
top.color <- "coral1"
bottom.color <- "skyblue1"

names(predanoms_new) <- c("time", 
                            "DMI", "WTIO", "ETIO", "week")

y.lab.vals <- c("Anomaly (\u00B0C)",
                "Anomaly (\u00B0C)",
                "Anomaly (\u00B0C)")

predictors <- predanoms_new

pred_nams <- names(predictors)

for (i in 3:length(predictors)-1){
  predictors[,i] <- (predictors[,i] - mean(predictors[,i]))/ sd(predictors[,i]) #standardize
}

first.date <- min(predictors$time)
last.date <- max(predictors$time)

time <- predictors$time
time.range <- c(first.date, last.date)
x.ticks <- seq(year(time.range[1]), year(time.range[2]), by = 1) #can also be done with lubridate floor
x.ticks.new <- c(x.ticks, x.ticks[21] + 1)

x.ticks <- ymd(paste0(x.ticks, "01", "01"))
#c(x_ticks, last.date) #get last date

#extend to 2021 (or mid 2020)
x.ticks.new <- ymd(paste0(x.ticks.new, "01", "01"))

```

```{r}

#get full predictor data range
pred.max <- max(round(range(predictors[,2:4])))
pred.range <- c(-pred.max, pred.max)

setwd("~/CO_AUS/Aus_CO-main/Interactions_New/Figures")


#PC1 vs DMI
png(filename = "IOD_ts.png", width = 2500, height = 1750, res = 300)

par(mfrow = c(3, 1))
par(mar = c(0,2,0,0))
par(oma = c(1.5,2,0,0))
par(mgp = c(2.75,1,0))
for (i in 2:4){
  this.pred <- (predictors[,i])
  temp.time <- as.Date(predictors$time)
  #temp.time <- gsub("-", "", temp.time)
  
  y.tick.max <- max(round(range(this.pred)))
  # y.tick.max <- 4
  y.tick.max.lab <- y.tick.max / 2
  y.ticks <- seq(-y.tick.max, y.tick.max, by = 1)
  y.tick.labs <- c(-y.tick.max.lab, 0, y.tick.max.lab)
  
  plot(temp.time, this.pred, type = "l", col = "black", lwd = 2,
       xaxt = "n", xlab = "",
       yaxt = "n", ylab = y.lab.vals[i-1], col.lab = "black",
       xlim = c(as.Date(time.range[1]) + months(7), as.Date(time.range[2]) - months(7)),
       ylim = pred.range, bty = "n", cex.lab = 1.25,  xpd = NA)
  
      if (i == 4){
        text(x = x.ticks[-length(x.ticks)] + months(6),
         y = range(y.ticks)[1]-1.5,
         labels = year(x.ticks[-length(x.ticks)]),
         cex = 1.3, col = "black", xpd = NA)
      }
  
    
     if (i == 2){ abline(v = x.ticks[1:(length(x.ticks))],
                      lty = 2, col = "grey", lwd = 2, xpd = NA) }
  
      axis(side = 2, at = y.tick.labs, labels = y.tick.labs, col = NA, 
      col.ticks = "black", col.axis = "black")
  
      abline(h = 0, lty = 1, col = "grey", lwd = 1)
  
      over <- this.pred >= 0
      this.pred.over <- this.pred
      this.pred.over[!over] <- 0
      this.pred.under <- this.pred
      this.pred.under[over] <- 0
  
      envelopePlot(x1 = temp.time,
               y1 = this.pred.over,
               x2 = temp.time,
               y2 = rep(0, length(time)),
               col = alpha(top.color, 0.7),
               lineCol = NA)
      envelopePlot(x1 = temp.time,
               y1 = this.pred.under,
               x2 = temp.time,
               y2 = rep(0, length(time)),
               col = alpha(bottom.color, 0.7),
               lineCol = NA)
      
        
  #td <- y.tick.labs[3]
  td <- 1.75    
  legend(x = c(ymd("1999-07-01"), ymd("2001-12-01")),
         y = c(1.5*td, 2.75*td),
         # legend = toupper(pred.names[i]),
         legend = pred_nams[i],
         box.col = "white", bg = "white",
         # adj = c(0., 0.6),
         xpd = NA, text.col = "grey40", cex = 1.75)
  
}
dev.off()
```


### EDA w/ pIOD indices

```{r pIOD}
plot(1:1054, pIOD.df$s.index, type = "l")
plot(1:1054, pIOD.df$m.index, type = "l")
```


```{r}
#get only jja and only son, then both
jja.ind <- which(month(bounded_pred_df$time) %in% c(6,7,8))
son.ind <- which(month(bounded_pred_df$time) %in% c(9,10,11))

djf.ind <- which(month(bounded_pred_df$time) %in% c(12,1,2))
mam.ind <- which(month(bounded_pred_df$time) %in% c(3,4,5))

#seasonal assignments
#jja
bounded_pred_df[jja.ind, ]
dmi.jja <- bounded_pred2_df[jja.ind, ]
piod.jja <- pIOD.df[jja.ind,]
#son
bounded_pred_df[son.ind, ]
dmi.son <- bounded_pred2_df[son.ind, ]
piod.son <- pIOD.df[son.ind,]
#djf
bounded_pred_df[djf.ind, ]
dmi.djf <- bounded_pred2_df[djf.ind, ]
piod.djf <- pIOD.df[djf.ind,]
#mam
bounded_pred_df[mam.ind, ]
dmi.mam <- bounded_pred2_df[mam.ind, ]
piod.mam <- pIOD.df[mam.ind,]


```


```{r seasonal_correlation}
#jja cor
dmi.jja.corM <- cor(dmi.jja$dmi.anomaly, scale(piod.jja$m.index))
dmi.jja.corS <- cor(dmi.jja$dmi.anomaly, scale(piod.jja$s.index))
wtio.jja.cor <- cor(dmi.jja$wtio.anomaly, scale(piod.jja$m.index))
etio.jja.cor <- cor(dmi.jja$etio.anomaly, scale(piod.jja$s.index))

cor(dmi.jja$wtio.anomaly, scale(piod.jja$PC1))

#son cor
dmi.son.corM <- cor(dmi.son$dmi.anomaly, scale(piod.son$m.index))
dmi.son.corS <- cor(dmi.son$dmi.anomaly, scale(piod.son$s.index))
wtio.son.cor <- cor(dmi.son$wtio.anomaly, piod.son$m.index)
etio.son.cor <- cor(dmi.son$etio.anomaly, piod.son$s.index)

cor(dmi.son$wtio.anomaly, scale(piod.son$PC1))

#djf cor
wtio.djf.cor <- cor(dmi.djf$wtio.anomaly, piod.djf$m.index)
etio.djf.cor <- cor(dmi.djf$etio.anomaly, piod.djf$s.index)

cor(dmi.djf$wtio.anomaly, scale(piod.djf$PC1))

#mam cor
wtio.mam.cor <- cor(dmi.mam$wtio.anomaly, piod.mam$m.index)
etio.mam.cor <- cor(dmi.mam$etio.anomaly, piod.mam$s.index)

cor(dmi.mam$wtio.anomaly, scale(piod.mam$PC1))

```


```{r PC_Cor}
wtio.pc1 <- cor(bounded_pred2_df$wtio.anomaly, pIOD.df$PC1)
etio.pc2 <- cor(bounded_pred2_df$etio.anomaly, pIOD.df$PC2)

wtio.pc1
etio.pc2
cor(bounded_pred2_df$etio.anomaly, scale(pIOD.df$PC1))
cor(bounded_pred2_df$wtio.anomaly, scale(pIOD.df$PC2))

cor(bounded_pred2_df$dmi.anomaly, scale(pIOD.df$PC1))
cor(bounded_pred2_df$dmi.anomaly, scale(pIOD.df$PC2))

wtio.cor <- cor(bounded_pred2_df$wtio.anomaly, scale(pIOD.df$m.index))
etio.cor <- cor(bounded_pred2_df$etio.anomaly, scale(pIOD.df$s.index))

##jja correlation
wtio.pc1.jja <- cor(dmi.jja$wtio.anomaly, scale(piod.jja$PC1))
etio.pc2.jja <- cor(dmi.jja$etio.anomaly, scale(piod.jja$PC2))

#son correlation
wtio.pc1.son <- cor(dmi.son$wtio.anomaly, scale(piod.son$PC1))
etio.pc2.son <- cor(dmi.son$etio.anomaly, piod.son$PC2)

dmi.pc1.son <- cor(dmi.son$dmi.anomaly, piod.son$PC1)

etio.pc1.son <- cor(dmi.son$etio.anomaly, piod.son$PC1)

#djf cor
wtio.pc1.djf <- cor(dmi.djf$wtio.anomaly, piod.djf$PC1)
etio.pc2.djf <- cor(dmi.djf$etio.anomaly, piod.djf$PC2)

#mam cor
wtio.pc1.mam <- cor(dmi.mam$wtio.anomaly, piod.mam$PC1)
etio.pc2.mam <- cor(dmi.mam$etio.anomaly, piod.mam$PC2)
```



```{r fits_corlines}
#get lines of best fit
wtio.jja.lm <- lm(dmi.jja$wtio.anomaly ~ scale(piod.jja$m.index))
etio.jja.lm <- lm(dmi.jja$etio.anomaly ~ scale(piod.jja$s.index))

wtio.son.lm <- lm(dmi.son$wtio.anomaly ~ scale(piod.son$m.index))
etio.son.lm <- lm(dmi.son$etio.anomaly ~ scale(piod.son$s.index))

```


```{r seasonal_plots}
#jja wtio and pc1
plot(dmi.jja$wtio.anomaly, scale(piod.jja$PC1), pch = 16)
title("JJA: WTIO and PC1", adj = 0)
#etio and pc2
plot(dmi.jja$etio.anomaly, scale(piod.jja$PC2), pch = 16)
title("JJA: ETIO and PC2", adj = 0)

#son wtio and pc1
plot(dmi.son$wtio.anomaly, scale(piod.son$PC1), pch = 16)
title("SON: WTIO and PC1", adj = 0)
#etio and pc2
plot(dmi.son$etio.anomaly, scale(piod.son$PC2), pch = 16)
title("SON: ETIO and PC2", adj = 0)

#djf wtio and pc1
plot(dmi.djf$wtio.anomaly, scale(piod.djf$PC1), pch = 16)
title("DJF: WTIO and PC1", adj = 0)
#etio and pc2
plot(dmi.djf$etio.anomaly, scale(piod.djf$PC2), pch = 16)
title("DJF: ETIO and PC2", adj = 0)

#mam wtio and pc1
plot(dmi.mam$wtio.anomaly, scale(piod.mam$PC1), pch = 16)
title("MAM: WTIO and PC1", adj = 0)
#etio and pc2
plot(dmi.mam$etio.anomaly, scale(piod.mam$PC2), pch = 16)
title("MAM: ETIO and PC2", adj = 0)

```


```{r season_altplots}
#jja wtio and pc2
plot(dmi.jja$wtio.anomaly, scale(piod.jja$PC2), pch = 16)
title("JJA: WTIO and PC2", adj = 0)
#etio and pc1
plot(dmi.jja$etio.anomaly, scale(piod.jja$PC1), pch = 16)
title("JJA: ETIO and PC1", adj = 0)



#son wtio and pc2
plot(dmi.son$wtio.anomaly, scale(piod.son$PC2), pch = 16)
title("SON: WTIO and PC2", adj = 0)
#etio and pc1
plot(dmi.son$etio.anomaly, scale(piod.son$PC1), pch = 16)
title("SON: ETIO and PC1", adj = 0)

#djf wtio and pc2
plot(dmi.djf$wtio.anomaly, scale(piod.djf$PC2), pch = 16)
title("DJF: WTIO and PC2", adj = 0)
#etio and pc1
plot(dmi.djf$etio.anomaly, scale(piod.djf$PC1), pch = 16)
title("DJF: ETIO and PC1", adj = 0)

#mam wtio and pc2
plot(dmi.mam$wtio.anomaly, scale(piod.mam$PC2), pch = 16)
title("MAM: WTIO and PC2", adj = 0)
#etio and pc1
plot(dmi.mam$etio.anomaly, scale(piod.mam$PC1), pch = 16)
title("MAM: ETIO and PC1", adj = 0)
```



```{r full_plots}
setwd("~/CO_AUS/Aus_CO-main/Interactions_New/Figures")

#plot(bounded_pred2_df$dmi.anomaly, pIOD.df$PC1, pch = 19)
#plot(bounded_pred2_df$dmi.anomaly, pIOD.df$PC2, pch = 19)

png(filename = "wtio_pc1.png", width = 2000, height = 1200, res = 250)
par(mar = c(5, 5, 3, 5))
plot(bounded_pred2_df$wtio.anomaly, pIOD.df$PC1, pch = 19, cex = 0.89,
     xlab = "WTIO", ylab = "PC1")
title("", adj = 0)
text(-0.65, 3, paste0("Cor = ", round(wtio.pc1, 3)), adj = 0 )
dev.off()


png(filename = "etio_pc2.png", width = 2000, height = 1200, res = 250)
par(mar = c(5, 5, 3, 5))
plot(bounded_pred2_df$etio.anomaly, pIOD.df$PC2, pch = 19, cex = 0.89,
     xlab = "ETIO", ylab = "PC2")
title("", adj = 0)
text(-1.75, -2.2, paste0("Cor = ", round(etio.pc2, 3)), adj = 0 )
dev.off()


png(filename = "wtio_mindexNEW.png", width = 2000, height = 1200, res = 250)
par(mar = c(5, 5, 3, 5))
plot(bounded_pred2_df$wtio.anomaly, scale(pIOD.df$m.index), pch = 19, cex = 0.89,
     ylab= "M-index", xlab = "WTIO")
text(-0.75, 2.75, paste0("Cor = ", round(wtio.cor, 3)), adj = 0 )
dev.off()


png(filename = "etio_sindexNEW.png", width = 2000, height = 1200, res = 250)
par(mar = c(5, 5, 3, 5))
plot(bounded_pred2_df$etio.anomaly, scale(pIOD.df$s.index), pch = 19, cex = 0.89,
     ylab = "S-index", xlab = "ETIO")
text(-1.75, -2.2, paste0("Cor = ", round(etio.cor, 3)), adj = 0 )
dev.off()


```


```{r son_plots}

setwd("~/CO_AUS/Aus_CO-main/Interactions_New/Figures")


png(filename = "wtio_mindexSON.png", width = 2000, height = 1200, res = 250)
par(mar = c(5, 5, 3, 5))
plot(dmi.son$wtio.anomaly, scale(piod.son$m.index), pch = 19, cex = 0.89,
     xlab = "WTIO", ylab = "M-Index")
text(-0.45, 2, paste0("Cor = ", round(wtio.son.cor, 3)), adj = 0 )
title("SON: WTIO and M-Index", adj = 0)
dev.off()

png(filename = "etio_sindexSON.png", width = 2000, height = 1200, res = 250)
par(mar = c(5, 5, 3, 5))
plot(dmi.son$etio.anomaly, scale(piod.son$s.index), pch = 19, cex = 0.89,
     xlab = "ETIO", ylab = "S-Index")
text(-1.75, -1.5, paste0("Cor = ", round(etio.son.cor, 3)), adj = 0 )
title("SON: ETIO and S-Index", adj = 0)
dev.off()

plot(dmi.son$wtio.anomaly, scale(piod.son$PC2), pch = 19)

plot(dmi.son$etio.anomaly, scale(piod.son$PC2), pch = 19)


plot(dmi.son$dmi.anomaly, scale(piod.son$PC1), pch = 19)
plot(dmi.son$dmi.anomaly, scale(piod.son$PC2), pch = 19)
```


```{r jja_plots}
#JJA
plot(dmi.jja$wtio.anomaly, scale(piod.jja$m.index), pch = 19)

plot(dmi.jja$wtio.anomaly, scale(piod.jja$PC1), pch = 19)
#abline(wtio.jja.lm, lwd = 1.5, lty = 2, col = "firebrick")

plot(dmi.jja$etio.anomaly, scale(piod.jja$s.index), pch = 19)
plot(dmi.jja$etio.anomaly, scale(piod.jja$PC2), pch = 19)

#abline(etio.jja.lm, lwd = 1.5, lty = 2, col = "firebrick")
```


Note: look at comparisons for SON, then the other seasons.

```{r}
wtio.cor <- cor(bounded_pred2_df$wtio.anomaly, scale(pIOD.df$m.index))
etio.cor <- cor(bounded_pred2_df$etio.anomaly, scale(pIOD.df$s.index))


full.col <- rep("black", times = length(pIOD.df$m.index))
son.col <- full.col
son.col[son.ind] <- "firebrick3"


plot(bounded_pred2_df$wtio.anomaly, pIOD.df$m.index, pch = 19,
     ylab= "M-index", xlab = "WTIO", col = son.col)

plot(bounded_pred2_df$etio.anomaly, pIOD.df$s.index, pch = 19,
     ylab = "S-index", xlab = "ETIO", col = son.col)
title("", adj = 0 )


```

```{r}

#plot residuals
#wtio - m.index
west.resid <- bounded_pred2_df$wtio.anomaly - scale(pIOD.df$m.index)
east.resid <- (-bounded_pred2_df$etio.anomaly) - scale(pIOD.df$s.index)

plot(1:1054, west.resid, type = "l")
plot(1:1054, east.resid, type = "l")


#TODO: look at son only, then everything else
```


Repeat correlation work from earlier work

# Correlation Work

Comparison between climate modes and CO anomalies

```{r correlation_functions}

#specific to our problem (we can generalize later)
pred_cor <- function(resp, preds){
   
  cor_list <- list()
  for (j in 1:3) {
    temp_df <- as.data.frame(cbind(resp[[j]], preds[[j]]))
  
    nino_cor <- cor(temp_df, method = "pearson")[2:53]
    wtio_cor <- cor(temp_df, method = "pearson")[54:105]
    etio_cor <- cor(temp_df, method = "pearson")[106:157]
    tsa_cor <- cor(temp_df, method = "pearson")[158:209]
    aao_cor <- cor(temp_df, method = "pearson")[210:261]
    olr_cor <- cor(temp_df, method = "pearson")[262:313]
    
    cor_df <- data.frame(nino_cor, wtio_cor, etio_cor, tsa_cor, aao_cor, olr_cor)
    
    cor_list[[paste0("Group_", j)]] <- cor_df
  }
  
  return(cor_list)
  
}


predbase_cor <- function(resp, preds){
   
  cor_list <- list()
  for (j in 1:3) {
    temp_df <- as.data.frame(cbind(resp[[j]], preds[[j]]))
  
    nino_cor <- cor(temp_df, method = "pearson")[2:53]
    dmi_cor <- cor(temp_df, method = "pearson")[54:105]
    tsa_cor <- cor(temp_df, method = "pearson")[106:157]
    aao_cor <- cor(temp_df, method = "pearson")[158:209]
    olr_cor <- cor(temp_df, method = "pearson")[210:261]
    
    cor_df <- data.frame(nino_cor, dmi_cor, tsa_cor, aao_cor, olr_cor)
    
    cor_list[[paste0("Group_", j)]] <- cor_df
  }
  
  return(cor_list)
  
}

```


```{r correlation}
#full response correlation
NEcor_list <- pred_cor(NEresp_new, NEpreds_new)
SEcor_list <- pred_cor(SEresp_new, SEpreds_new)

NEcor_base <- predbase_cor(NEresp, NEpreds)
SEcor_base <- predbase_cor(SEresp, SEpreds)

#partial response correlation
NEcor_list_part <- pred_cor(NEresp_newpart, NEpreds_newpart)
SEcor_list_part <- pred_cor(SEresp_newpart, SEpreds_newpart)

NEcor_base_part <- predbase_cor(NEresp_part, NEpreds_part)
SEcor_base_part <- predbase_cor(SEresp_part, SEpreds_part)

#TODO: finalize the figures for this correlation

```

```{r test_plots}
plot(1:52, NEcor_list[[1]]$wtio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "firebrick2", lwd = 1.5)
abline(h = 0, lty = 2)
title("NE Aus Group 1 and WTIO")

plot(1:52, NEcor_list[[2]]$wtio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "firebrick2", lwd = 1.5)
abline(h = 0, lty = 2)
title("NE Aus Group 2 and WTIO")

plot(1:52, NEcor_list[[3]]$wtio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "firebrick2", lwd = 1.5)
abline(h = 0, lty = 2)
title("NE Aus Group 3 and WTIO")



plot(1:52, SEcor_list[[1]]$wtio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "firebrick2", lwd = 1.5)
abline(h = 0, lty = 2)
title("SE Aus Group 1 and WTIO")

plot(1:52, SEcor_list[[2]]$wtio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "firebrick2", lwd = 1.5)
abline(h = 0, lty = 2)
title("SE Aus Group 2 and WTIO")

plot(1:52, SEcor_list[[3]]$wtio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "firebrick2", lwd = 1.5)
abline(h = 0, lty = 2)
title("SE Aus Group 3 and WTIO")


```

```{r}
plot(1:52, NEcor_list[[1]]$etio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "firebrick2", lwd = 1.5)
abline(h = 0, lty = 2)
title("NE Aus Group 1 and ETIO")

plot(1:52, NEcor_list[[2]]$etio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "firebrick2", lwd = 1.5)
abline(h = 0, lty = 2)
title("NE Aus Group 2 and ETIO")

plot(1:52, NEcor_list[[3]]$etio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "firebrick2", lwd = 1.5)
abline(h = 0, lty = 2)
title("NE Aus Group 3 and ETIO")

plot(1:52, SEcor_list[[1]]$etio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "firebrick2", lwd = 1.5)
abline(h = 0, lty = 2)
title("SE Aus Group 1 and ETIO")

plot(1:52, SEcor_list[[2]]$etio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "firebrick2", lwd = 1.5)
abline(h = 0, lty = 2)
title("SE Aus Group 2 and ETIO")

plot(1:52, SEcor_list[[3]]$etio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "firebrick2", lwd = 1.5)
abline(h = 0, lty = 2)
title("SE Aus Group 3 and ETIO")

```

```{r test_figs}
plot(1:52, SEcor_base[[2]]$dmi_cor, col = "darkorchid3", lwd = 1.5, lty = 1,
     type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag")
lines(1:52, -SEcor_list[[2]]$etio_cor, col = "tomato4", lwd = 1.5, lty = 1)
lines(1:52, -SEcor_list_part[[2]]$etio_cor, col = "tomato4", lwd = 1.5, lty = 2)
lines(1:52, SEcor_base_part[[2]]$dmi_cor, col = "darkorchid3", lwd = 1.5, lty = 2)
abline(h = 0, lty = 2)
title("SE Aus Group 2 and IOD")


plot(1:52, SEcor_base[[2]]$dmi_cor, col = "darkorchid3", lwd = 1.5, lty = 1,
     type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag")
lines(1:52, SEcor_list[[2]]$wtio_cor, col = "firebrick2", lwd = 1.5, lty = 1)
lines(1:52, SEcor_list_part[[2]]$wtio_cor, col = "firebrick2", lwd = 1.5, lty = 2)
lines(1:52, SEcor_base_part[[2]]$dmi_cor, col = "darkorchid3", lwd = 1.5, lty = 2)
abline(h = 0, lty = 2)
title("SE Aus Group 2 and IOD")
```



```{r iod_cor}
#TODO: finalize and output these figures
setwd("~/CO_AUS/Aus_CO-main/Interactions_New/Figures")

#overlay DMI, WTIO, and ETIO
png(filename = "NEgroup1_iod.png", width = 2000, height = 1500, res = 300)
par(mar = c(5, 5, 4, 3))
plot(1:52, NEcor_list[[1]]$wtio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "tomato4", lwd = 1.5, lty = 2)
lines(1:52, NEcor_list[[1]]$etio_cor, col = "cyan4", lwd = 1.5, lty = 2)
lines(1:52,  NEcor_base[[1]]$dmi_cor, col = "darkorchid3", lwd = 1.5, lty = 1)
abline(h = 0, lty = 2)
title("IOD (NE Aus Group 1)", adj = 0)
legend("topright", inset = c(0.01, 0.01),
       legend = c("DMI", "WTIO",  "ETIO"),
       lty = c(1,2,2),
              col = c( "darkorchid3", 
                "tomato4",
                "cyan4"),
       lwd = c(1.5, 1.5, 1.5))
dev.off()


#overlay DMI, WTIO, and ETIO
png(filename = "NEgroup2_iod.png", width = 2000, height = 1500, res = 300)
par(mar = c(5, 5, 4, 3))
plot(1:52, NEcor_list[[2]]$wtio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "tomato4", lwd = 1.5, lty = 2)
lines(1:52, NEcor_list[[2]]$etio_cor, col = "cyan4", lwd = 1.5, lty = 2)
lines(1:52,  NEcor_base[[2]]$dmi_cor, col = "darkorchid3", lwd = 1.5, lty = 1)
abline(h = 0, lty = 2)
title("IOD (NE Aus Group 2)", adj = 0)
legend("topright", inset = c(0.01, 0.01),
       legend = c("DMI", "WTIO",  "ETIO"),
       lty = c(1,2,2),
              col = c( "darkorchid3", 
                "tomato4",
                "cyan4"),
       lwd = c(1.5, 1.5, 1.5))
dev.off()


png(filename = "NEgroup3_iod.png", width = 2000, height = 1500, res = 300)
par(mar = c(5, 5, 4, 3))
plot(1:52, NEcor_list[[3]]$wtio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "tomato4", lwd = 1.5, lty = 2)
lines(1:52, NEcor_list[[3]]$etio_cor, col = "cyan4", lwd = 1.5, lty = 2)
lines(1:52,  NEcor_base[[3]]$dmi_cor, col = "darkorchid3", lwd = 1.5, lty = 1)
abline(h = 0, lty = 2)
title("IOD (NE Aus Group 3)", adj = 0)
legend("topright", inset = c(0.01, 0.01),
       legend = c("DMI", "WTIO",  "ETIO"),
       lty = c(1,2,2),
              col = c( "darkorchid3", 
                "tomato4",
                "cyan4"),
       lwd = c(1.5, 1.5, 1.5))
dev.off()


png(filename = "SEgroup1_iod.png", width = 2000, height = 1500, res = 300)
par(mar = c(5, 5, 4, 3))
plot(1:52, SEcor_list[[1]]$wtio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "tomato4", lwd = 1.5, lty = 2)
lines(1:52, SEcor_list[[1]]$etio_cor, col = "cyan4", lwd = 1.5, lty = 2)
lines(1:52,  SEcor_base[[1]]$dmi_cor, col = "darkorchid3", lwd = 1.5, lty = 1)
abline(h = 0, lty = 2)
title("IOD (SE Aus Group 1)", adj = 0)
legend("topright", inset = c(0.01, 0.01),
       legend = c("DMI", "WTIO",  "ETIO"),
       lty = c(1,2,2),
              col = c( "darkorchid3", 
                "tomato4",
                "cyan4"),
       lwd = c(1.5, 1.5, 1.5))
dev.off()


png(filename = "SEgroup2_iod.png", width = 2000, height = 1500, res = 300)
par(mar = c(5, 5, 4, 3))
plot(1:52, SEcor_list[[2]]$wtio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "tomato4", lwd = 1.5, lty = 2)
lines(1:52, SEcor_list[[2]]$etio_cor, col = "cyan4", lwd = 1.5, lty = 2)
lines(1:52,  SEcor_base[[2]]$dmi_cor, col = "darkorchid3", lwd = 1.5, lty = 1)
abline(h = 0, lty = 2)
title("IOD (SE Aus Group 2)", adj = 0)
legend("topright", inset = c(0.01, 0.01),
       legend = c("DMI", "WTIO",  "ETIO"),
       lty = c(1,2,2),
              col = c( "darkorchid3", 
                "tomato4",
                "cyan4"),
       lwd = c(1.5, 1.5, 1.5))
dev.off()


png(filename = "SEgroup3_iod.png", width = 2000, height = 1500, res = 300)
par(mar = c(5, 5, 4, 3))
plot(1:52, SEcor_list[[3]]$wtio_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = "tomato4", lwd = 1.5, lty = 2)
lines(1:52, SEcor_list[[3]]$etio_cor, col = "cyan4", lwd = 1.5, lty = 2)
lines(1:52,  SEcor_base[[3]]$dmi_cor, col = "darkorchid3", lwd = 1.5, lty = 1)
abline(h = 0, lty = 2)
title("IOD (SE Aus Group 3)", adj = 0)
legend("topright", inset = c(0.01, 0.01),
       legend = c("DMI", "WTIO",  "ETIO"),
       lty = c(1,2,2),
              col = c( "darkorchid3", 
                "tomato4",
                "cyan4"),
       lwd = c(1.5, 1.5, 1.5))
dev.off()

```




