---
title: "IOD_dmi.rmd"
author: "Ryan Peterson"
date: "2025-09-07"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library}
#.nc files
suppressMessages(library(ncdf4))
suppressMessages(library(terra))

# date/data mgmt
suppressMessages(library(lubridate))
suppressMessages(library(abind))

#visualization and interpolation
suppressMessages(library(fields))
suppressMessages(library(colorspace))
suppressMessages(library(RColorBrewer))
suppressMessages(library(scales)) #for adjusting opacity
```


```{r other_dataloads}
setwd("~/CO_AUS/Aus_CO-main/Interactions")

load( "Data/ne_data.rda")
load( "Data/se_data.rda")
load( "Data/bounded_data.rda")
load( "Data/data_matrix.rda")
load( "Data/lag_list.rda")

setwd("~/CO_AUS/Aus_CO-main")

#anomaly only response with week data
response_anoms <- read.csv("Data/response_anoms.csv", header = TRUE, stringsAsFactors = FALSE)

#predictors with week data
predictor_anoms <- read.csv("Data/predictor_anoms.csv", header = TRUE, stringsAsFactors = FALSE)

#add in OLR data
load( "olr_anom.rda")
```

```{r pIOD_load}

setwd("~/CO_AUS/Aus_CO-main/pIOD")
load("piod_index.rda")
```


```{r nc_load}
setwd("~/CO_AUS/Aus_CO-main")

#dmi 
dmi.monthly <- read.csv("pIOD/Data/dmi.had.long.csv", header = TRUE, stringsAsFactors = FALSE)

#dmi longer anom
dmi.anom <- read.csv("Data/dmi_weekly_avg.csv", header = TRUE, stringsAsFactors = FALSE)

#DMI
dmi.nc <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/dmi.nc")

#WTIO
wtio <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/wtio.nc")

#SETIO
setio <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/setio.nc")


#note this is the correct old data!
#old data??
#sst.nc <- nc_open("~/CO_AUS/Aus_CO-main/Data/sst.wkmean.1990-present.nc")
#DMI
dmi.old <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/dmi(2).nc")

#WTIO
wtio.old <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/wtio(1).nc")

#SETIO
setio.old <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/setio(2).nc")


```


```{r nc_prep}

#weeks (time)
time.dmi <- ncvar_get(dmi.nc, "TIME") # days since 1800-01-01 00:00:0.0
time.dmi <- as_datetime("1800-01-01T00:00:00") + days(time.dmi)

time.wtio <- ncvar_get(wtio, "TIME") # days since 1800-01-01 00:00:0.0
time.wtio <- as_datetime("1800-01-01T00:00:00") + days(time.wtio)

time.setio <- ncvar_get(setio, "TIME") # days since 1800-01-01 00:00:0.0
time.setio <- as_datetime("1800-01-01T00:00:00") + days(time.setio)

#weekly data
sst.dmi <- ncvar_get(dmi.nc, "DMI")

sst.wtio <- ncvar_get(wtio, "WTIO")

sst.setio <- ncvar_get(setio, "SETIO")

#get week of the year
#shift 3 days to Wednesday
time.dmi <- time.dmi + days(3)
time.wtio <- time.wtio + days(3)
time.setio <- time.setio + days(3)

#get df
dmi.new.df <- data.frame(sst = sst.dmi, date = time.dmi, week = epiweek(time.dmi))

wtio.df <- data.frame(sst = sst.wtio, date = time.wtio, week = epiweek(time.wtio))

setio.df <- data.frame(sst = sst.setio, date = time.setio, week = epiweek(time.setio))


#get specific dates 
time.dmi[748]
time.dmi[2013]

#from 1996-01-03 to 2020-04-01
time.domain <- which(dmi.new.df$date >= time.dmi[748] & dmi.new.df$date <= time.dmi[2013])
 
dmi.new2.df <- dmi.new.df[time.domain,]
wtio2.df <- wtio.df[time.domain,]
setio2.df <- setio.df[time.domain,]
```

```{r nc_prepOld}

#weeks (time)
time.dmi <- ncvar_get(dmi.old, "WEDCEN2") # days since 1800-01-01 00:00:0.0
time.dmi <- as_datetime("1900-01-01T00:00:00") + days(time.dmi)

time.wtio <- ncvar_get(wtio.old, "WEDCEN2") # days since 1800-01-01 00:00:0.0
time.wtio <- as_datetime("1900-01-01T00:00:00") + days(time.wtio)

time.setio <- ncvar_get(setio.old, "WEDCEN2") # days since 1800-01-01 00:00:0.0
time.setio <- as_datetime("1900-01-01T00:00:00") + days(time.setio)

#weekly data
sst.dmi <- ncvar_get(dmi.old, "DMI")

sst.wtio <- ncvar_get(wtio.old, "WTIO")

sst.setio <- ncvar_get(setio.old, "SETIO")

#get week of the year
#shift 3 days to Wednesday
#time.dmi <- time.dmi + days(3)
#time.wtio <- time.wtio + days(3)
#time.setio <- time.setio + days(3)

#get df
dmi.new.df <- data.frame(sst = sst.dmi, date = time.dmi, week = epiweek(time.dmi))

wtio.df <- data.frame(sst = sst.wtio, date = time.wtio, week = epiweek(time.wtio))

setio.df <- data.frame(sst = sst.setio, date = time.setio, week = epiweek(time.setio))


#get specific dates 
time.dmi[10]
time.dmi[740]
time.dmi[2005]

#from 1996-01-03 to 2020-04-01
time.domain <- which(dmi.new.df$date >= time.dmi[740] & dmi.new.df$date <= time.dmi[2005])
 
dmi.new2.df <- dmi.new.df[time.domain,]
dmi.new2.df$year <- year(dmi.new2.df$date)
dmi.new2.df$month <- month(dmi.new2.df$date)

wtio2.df <- wtio.df[time.domain,]
wtio2.df$year <- year(wtio2.df$date)
wtio2.df$month <- month(wtio2.df$date)

setio2.df <- setio.df[time.domain,]
setio2.df$year <- year(setio2.df$date)
setio2.df$month <- month(setio2.df$date)



#from 1982-01-06 to 2020-04-01
time.domain <- which(dmi.new.df$date >= time.dmi[10] & dmi.new.df$date <= time.dmi[2005])
 
dmi.new3.df <- dmi.new.df[time.domain,]
dmi.new3.df$year <- year(dmi.new3.df$date)
dmi.new3.df$month <- month(dmi.new3.df$date)

wtio3.df <- wtio.df[time.domain,]
wtio3.df$year <- year(wtio3.df$date)
wtio3.df$month <- month(wtio3.df$date)

setio3.df <- setio.df[time.domain,]
setio3.df$year <- year(setio3.df$date)
setio3.df$month <- month(setio3.df$date)

```



```{r other_data_prep}
dmi.anom$anomaly <- dmi.anom$time

dmi.anom$time <- as_date(rownames(dmi.anom))

rownames(dmi.anom) <- NULL
```


```{r naive_plot}


dmi.diff <-  scale(dmi.new2.df$sst) - scale(predictor_anoms$dmi.anomaly)


plot(1:1266, dmi.diff, type = "l")

#week 1
wtio.week1 <- wtio2.df[which(wtio2.df$week == 1), ]
setio.week1 <- setio2.df[which(setio2.df$week == 1), ]

dmi.test.week1 <- wtio.week1$sst - setio.week1$sst

#select weeks
dmi.week1 <- dmi.new2.df[which(dmi.new2.df$week == 1), ]
pred.dmi.week1 <- predictor_anoms[which(predictor_anoms$week == 1), ]

length(dmi.week1$sst)

plot(1:25, dmi.week1$sst, type = "l")
lines(1:25, scale(pred.dmi.week1$dmi.anomaly, scale = FALSE), lty = 2)
lines(1:25, dmi.test.week1, lty = 3)

plot(1:25, scale(dmi.test.week1, center = TRUE, scale = FALSE), lty = 3, type = "l")


#other weeks
#week 41
wtio.week40 <- wtio2.df[which(wtio2.df$week == 41), ]
setio.week40 <- setio2.df[which(setio2.df$week == 41), ]

dmi.test.week40 <- wtio.week40$sst - setio.week40$sst

#select weeks
dmi.week40 <- dmi.new2.df[which(dmi.new2.df$week == 41), ]
pred.dmi.week40 <- predictor_anoms[which(predictor_anoms$week == 41), ]

length(dmi.week40$sst)

plot(1:24, scale(dmi.week40$sst,center = TRUE, scale = FALSE), type = "l")
lines(1:24, scale(pred.dmi.week40$dmi.anomaly, scale = FALSE), lty = 2)
lines(1:24, dmi.test.week40, lty = 3)
```

```{r monthly_avgWIP}
dmi.sep <- dmi.new2.df[month(dmi.new2.df$date) %in% c(9),]
dmi.oct <- dmi.new2.df[dmi.new2.df$month == 10, ]
rownames(dmi.oct) <- NULL

dmi.nov <- dmi.new2.df[dmi.new2.df$month == 11, ]


mean(dmi.sep$sst[1:4])
mean(dmi.oct$sst[104:108])
mean(dmi.nov$sst[43:46])

```

```{r son_avg}
#1996-2015
dmi.son <- dmi.new2.df[dmi.new2.df$month %in% c(9,10,11), ]
wtio.son <- wtio2.df[wtio2.df$month %in% c(9,10,11), ]
setio.son <- setio2.df[setio2.df$month %in% c(9,10,11), ]


years <- 1996:2015
son.avg <- data.frame()
for (j in years) {
  dmi.mean <- mean(dmi.son[dmi.son$year == j, 1])
  wtio.mean <- mean(wtio.son[wtio.son$year == j, 1])
  stio.mean <- mean(setio.son[setio.son$year == j, 1])
  son.avg <- rbind(son.avg, c(dmi.mean, wtio.mean, stio.mean) )
  
}

colnames(son.avg) <- c("dmi", "wtio", "etio")
rownames(son.avg) <- years

#1982-2015
dmi.son <- dmi.new3.df[dmi.new3.df$month %in% c(9,10,11), ]
wtio.son <- wtio3.df[wtio3.df$month %in% c(9,10,11), ]
setio.son <- setio3.df[setio3.df$month %in% c(9,10,11), ]


years <- 1982:2015
son2.avg <- data.frame()
for (j in years) {
  dmi.mean <- mean(dmi.son[dmi.son$year == j, 1])
  wtio.mean <- mean(wtio.son[wtio.son$year == j, 1])
  stio.mean <- mean(setio.son[setio.son$year == j, 1])
  son2.avg <- rbind(son2.avg, c(dmi.mean, wtio.mean, stio.mean) )
  
}

colnames(son2.avg) <- c("dmi", "wtio", "etio")
rownames(son2.avg) <- years


```



```{r pIOD_compare}
dmi.son.avg <- son2.avg$dmi
wtio.son.avg <- son2.avg$wtio
etio.son.avg <- son2.avg$etio
PC1.new <- PC1[1:34]
mindex.new <-  m.index[1:34]
sindex.new <- s.index[1:34]

#correlation
dmipc1.cor <- cor(dmi.son.avg, PC1.new)
wtiomod.cor <- cor(wtio.son.avg, mindex.new)
etiostr.cor <- cor(etio.son.avg, sindex.new)
dmipc1.cor
wtiomod.cor
etiostr.cor

#check against other options
cor(wtio.son.avg, PC1)
cor(etio.son.avg, PC1)
cor(wtio.son.avg, PC2)
cor(etio.son.avg, PC2)
cor(wtio.son.avg, sindex.new)
cor(etio.son.avg, mindex.new)

#fit
dmipc1.fit <- lm(PC1.new ~ dmi.son.avg)
summary(dmipc1.fit)

wtiomod.fit <-lm(mindex.new ~ wtio.son.avg)
summary(wtiomod.fit)

etiostr.fit <-lm(sindex.new ~ etio.son.avg)
summary(etiostr.fit)

```


```{r plots}
setwd("~/CO_AUS/Aus_CO-main/pIOD/Figures/New")


#PC1 vs DMI
png(filename = "dmipc1.png", width = 2000, height = 1200, res = 300)
par(mar = c(5, 5, 3, 5))
plot(dmi.son.avg, PC1.new, pch = 19,
     xlab = "DMI", ylab = "PC1")
abline(dmipc1.fit, col = "red", lty = 2)
title("", adj = 0)
text(-0.75, 2, paste0("Cor = ", round(dmipc1.cor,3)), adj = 0 )
dev.off()

#m-index vs wtio
png(filename = "wtiomindex.png", width = 2000, height = 1200, res = 300)
par(mar = c(5, 5, 3, 5))
plot(wtio.son.avg, mindex.new, pch = 19,
     xlab = "WTIO", ylab = "M-index")
abline(wtiomod.fit, col = "red", lty = 2)
title("", adj =0)
text(-0.4, 2, paste0("Cor = ", round(wtiomod.cor, 3)), adj = 0 )
dev.off()

#s-index vs etio
png(filename = "etiosindex.png", width = 2000, height = 1200, res = 300)
par(mar = c(5, 5, 3, 5))
plot(etio.son.avg, sindex.new, pch = 19,
     xlab = "ETIO", ylab = "S-index",
     xlim = c(-1.5,1.2), ylim = c(-2, 4.25))
abline(etiostr.fit, col = "red", lty = 2)
title("", adj = 0)
text(0.5, 3.5, paste0("Cor = ", round(etiostr.cor, 3)), adj = 0 )
dev.off()

```

# Data Cleaning

```{r setup}
season_weeks <- c(35:52, 1:14)

#get years from bounded_resp
season_years <- unique(bounded_resp_df$year)

seasons <- c()
for (i in 1:(length(season_years)-1)) {
  temp_season <- paste0(season_years[i], "-", season_years[i+1])
  #print(temp_season)  
  seasons <- c(seasons, temp_season)
}


rm(i, season_years, temp_season)
```


```{r data_cleaning}
#TODO prep wtio and etio for use in modeling
#update to predictor anom data frame with wtio and etio

pred.dmi.anoms <- data.frame(time = dmi.new2.df$date, 
                             dmi.anomaly = dmi.new2.df$sst,
                             wtio.anomaly = wtio2.df$sst,
                             etio.anomaly = setio2.df$sst,
                             week = dmi.new2.df$week,
                             year = dmi.new2.df$year)

#repeating some work from data_cleaning.rmd
week <- 1

predictor <- pred.dmi.anoms

#resp_dates <- as_date(response[response$week == week, ]$time) #not needed, 
pred_dates <- as_date(predictor[predictor$week == week, ]$time)

#get minimum prediction date from response data
#low_bound <- pred_dates[which(pred_dates == min(resp_dates)) - 1]
low_bound <- pred_dates[5]

#get maximum response date from predictor data
upper_bound <- max(as_date(predictor$time)) + days(7)

#this requires week being set correctly above, that req should be fixed
bounded_pred_df <- predictor[predictor$time >= low_bound & predictor$time <= upper_bound, ]

#2019 boundary (week 14 2019: end of 2018/2019 season)
max_date <- as_date(response_anoms[response_anoms$week == 14 & 
                                     response_anoms$year == 2020, ]$time)

max_date <- as_date(bounded_pred_df[bounded_pred_df$week == 14 & bounded_pred_df$year == 2020, ]$time)

bounded_pred_df <- bounded_pred_df[bounded_pred_df$time <= max_date, ]


#fix for the correct columns
week_53pred <- which(bounded_pred_df$week == 53, )
for (j in week_53pred) {
  bounded_pred_df[j-1, 2] <- mean(c(bounded_pred_df[j-1, 2], 
                                    bounded_pred_df[j, 2]))
  bounded_pred_df[j-1, 3] <- mean(c(bounded_pred_df[j-1, 3],
                                    bounded_pred_df[j, 3]))
  bounded_pred_df[j-1, 4] <- mean(c(bounded_pred_df[j-1, 4],
                                    bounded_pred_df[j, 4]))
}

bounded_pred_df <- bounded_pred_df[-week_53pred, ]
rm(j, week_53pred)

bounded_pred_df <- bounded_pred_df[ ,-1]
row.names(bounded_pred_df) <- NULL


```


```{r temp_blcok}
i <- season_weeks[28]

temp_resp <- bounded_resp_df[bounded_resp_df$week == i, ]
  
if (i <= 14) {
  temp_resp <- temp_resp[-which(temp_resp$year == 2001), ]
}

#TODO: use this to add the start of the weekly df's
tempNE_df <- as.data.frame(matrix(seasons, ncol = 1, byrow = TRUE))
tempNE_df <- cbind(tempNE_df, temp_resp$NE_Aus_anomaly_co)
colnames(tempNE_df) <- c("Seasons", "NE_Aus")
  
tempSE_df <- as.data.frame(matrix(seasons, ncol = 1, byrow = TRUE))
tempSE_df <- cbind(tempSE_df, temp_resp$SE_Aus_anomaly_co)
colnames(tempSE_df) <- c("Seasons", "SE_Aus")

#current
lag_resp <- temp_resp[which(temp_resp$week == i), ]
min_year <- min(lag_resp$year)
max_year <- max(lag_resp$year)

#lag loop (inner loop)
#resp_week_lag <- as.data.frame(matrix())
dmi_lag <- matrix(NA, nrow = length(lag_resp$NE_Aus_anomaly_co))
wtio_lag <- matrix(NA, nrow = length(lag_resp$NE_Aus_anomaly_co))
etio_lag <- matrix(NA, nrow = length(lag_resp$NE_Aus_anomaly_co))


```



```{r data_clean2}

NE_laglist_std <- list()
SE_laglist_std <- list()

#for i in season_weeks
for(i in season_weeks){
  
  temp_resp <- bounded_resp_df[bounded_resp_df$week == i, ]
    
  if (i <= 14) {
    temp_resp <- temp_resp[-which(temp_resp$year == 2001), ]
  }
  
  #TODO: use this to add the start of the weekly df's
  tempNE_df <- as.data.frame(matrix(seasons, ncol = 1, byrow = TRUE))
  tempNE_df <- cbind(tempNE_df, temp_resp$NE_Aus_anomaly_co)
  colnames(tempNE_df) <- c("Seasons", "NE_Aus")
    
  tempSE_df <- as.data.frame(matrix(seasons, ncol = 1, byrow = TRUE))
  tempSE_df <- cbind(tempSE_df, temp_resp$SE_Aus_anomaly_co)
  colnames(tempSE_df) <- c("Seasons", "SE_Aus")
  
  #current
  lag_resp <- temp_resp[which(temp_resp$week == i), ]
  min_year <- min(lag_resp$year)
  max_year <- max(lag_resp$year)
  
  #lag loop (inner loop)
  #resp_week_lag <- as.data.frame(matrix())
  nino_lag <- matrix(NA, nrow = length(lag_resp$NE_Aus_anomaly_co))
  dmi_lag <- matrix(NA, nrow = length(lag_resp$NE_Aus_anomaly_co))
  tsa_lag <- matrix(NA, nrow = length(lag_resp$NE_Aus_anomaly_co))
  aao_lag <- matrix(NA, nrow = length(lag_resp$NE_Aus_anomaly_co))
  
  NEolr_lag <- matrix(NA, nrow = length(lag_resp$NE_Aus_anomaly_co))
  SEolr_lag <- matrix(NA, nrow = length(lag_resp$NE_Aus_anomaly_co))
  
  week_vec <- c()
  lag_vec <- c()
  for (j in 1:52) {
    lag <- j
    lag_week <- i - lag
    if (lag_week <= 0) {
      lag_week <- 52 + lag_week
      lag_year <- c(min_year - 1, max_year -1)
    } else {
      lag_year <- min_year
      lag_year <- c(min_year, max_year)
    }
    
    lag_pred <- bounded_pred_df[which(bounded_pred_df$week == lag_week), ]
    lag_pred <- lag_pred[which(lag_pred$year >= lag_year[1] & lag_pred$year <= lag_year[2]), ]
    
    lag_olr <- bounded_olr_df[which(bounded_olr_df$Week == lag_week), ]
    lag_olr <- lag_olr[which(lag_olr$Year >= lag_year[1] & lag_olr$Year <= lag_year[2]), ]
    
    nino_lag <- cbind(nino_lag, lag_pred$nino.anomaly)
    dmi_lag <- cbind(dmi_lag, lag_pred$dmi.anomaly)
    tsa_lag <- cbind(tsa_lag, lag_pred$tsa.anomaly)
    aao_lag <- cbind(aao_lag, lag_pred$aao.anomaly)
    
    NEolr_lag <- cbind(NEolr_lag, lag_olr$NE_anom)
    SEolr_lag <- cbind(SEolr_lag, lag_olr$SE_anom) 
    
    week_vec <- c(week_vec, lag_week)
    lag_vec <- c(lag_vec, lag)
  }
  
  nino_lag <- nino_lag[,-1]
  colnames(nino_lag) <- paste0("nino_lag", lag_vec[1:52])
  nino_lag <- scale(nino_lag, center = TRUE, scale = TRUE)
  
  dmi_lag <- dmi_lag[,-1]
  colnames(dmi_lag) <- paste0("dmi_lag", lag_vec[1:52])
  dmi_lag <- scale(dmi_lag, center = TRUE, scale = TRUE)
  
  tsa_lag <- tsa_lag[,-1]
  colnames(tsa_lag) <- paste0("tsa_lag", lag_vec[1:52])
  tsa_lag <- scale(tsa_lag, center = TRUE, scale = TRUE)
  
  aao_lag <- aao_lag[,-1]
  colnames(aao_lag) <- paste0("aao_lag", lag_vec[1:52])
  aao_lag <- scale(aao_lag, center = TRUE, scale = TRUE)
  
  NEolr_lag <- NEolr_lag[ ,-1]
  colnames(NEolr_lag) <- paste0("NEolr_lag", lag_vec[1:52])
  NEolr_lag <- scale(NEolr_lag, center = TRUE, scale = TRUE)
  
  SEolr_lag <- SEolr_lag[ ,-1]
  colnames(SEolr_lag) <- paste0("SEolr_lag", lag_vec[1:52])
  SEolr_lag <- scale(SEolr_lag, center = TRUE, scale = TRUE)
  
  
  NEweek_lag <- data.frame(tempNE_df, nino_lag, dmi_lag, tsa_lag, aao_lag, NEolr_lag)
  SEweek_lag <- data.frame(tempSE_df, nino_lag, dmi_lag, tsa_lag, aao_lag, SEolr_lag)
  
  NE_laglist_std[[paste("Week ", i)]] <- NEweek_lag
  SE_laglist_std[[paste("Week ", i)]] <- SEweek_lag
}


```

