---
title: "IOF_EOF_ORAS"
author: "Ryan Peterson"
date: "2025-08-10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
#.nc files
suppressMessages(library(ncdf4))
suppressMessages(library(terra))

# date/data mgmt
suppressMessages(library(lubridate))
suppressMessages(library(abind))

#visualization and interpolation
suppressMessages(library(fields))
suppressMessages(library(colorspace))
suppressMessages(library(RColorBrewer))
suppressMessages(library(scales)) #for adjusting opacity
```


```{r import}
#import some of the associated data
setwd("~/CO_AUS/Aus_CO-main")

#ORAS5
##1982
#sept 1982
nc.ORAS.1982s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198209_CONS_v0.1.nc")
#oct 1982
nc.ORAS.1982o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198210_CONS_v0.1.nc")
#nov 1982
nc.ORAS.1982n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198211_CONS_v0.1.nc")

##1983
#sept 1983
nc.ORAS.1983s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198309_CONS_v0.1.nc")
#oct 1983
nc.ORAS.1983o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198310_CONS_v0.1.nc")
#nov 1983
nc.ORAS.1983n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198311_CONS_v0.1.nc")

##1984
#sept 1984
nc.ORAS.1984s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198409_CONS_v0.1.nc")
#oct 1984
nc.ORAS.1984o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198410_CONS_v0.1.nc")
#nov 1984
nc.ORAS.1984n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198411_CONS_v0.1.nc")

##1985
#sept 1985
nc.ORAS.1985s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198509_CONS_v0.1.nc")
#oct 1985
nc.ORAS.1985o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198510_CONS_v0.1.nc")
#nov 1985
nc.ORAS.1985n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198511_CONS_v0.1.nc")

##1986
#sept 1986
nc.ORAS.1986s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198609_CONS_v0.1.nc")
#oct 1986
nc.ORAS.1986o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198610_CONS_v0.1.nc")
#nov 1986
nc.ORAS.1986n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198611_CONS_v0.1.nc")

##1987
#sept 1987
nc.ORAS.1987s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198709_CONS_v0.1.nc")
#oct 1987
nc.ORAS.1987o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198710_CONS_v0.1.nc")
#nov 1987
nc.ORAS.1987n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198711_CONS_v0.1.nc")

##1988
#sept 1988
nc.ORAS.1988s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198809_CONS_v0.1.nc")
#oct 1988
nc.ORAS.1988o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198810_CONS_v0.1.nc")
#nov 1988
nc.ORAS.1988n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198811_CONS_v0.1.nc")

##1989
#sept 1989
nc.ORAS.1989s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198909_CONS_v0.1.nc")
#oct 1989
nc.ORAS.1989o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198910_CONS_v0.1.nc")
#nov 1989
nc.ORAS.1989n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_198911_CONS_v0.1.nc")

##1990
#sept 1990
nc.ORAS.1990s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199009_CONS_v0.1.nc")
#oct 1990
nc.ORAS.1990o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199010_CONS_v0.1.nc")
#nov 1990
nc.ORAS.1990n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199011_CONS_v0.1.nc")

##1991
#sept 1991
nc.ORAS.1991s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199109_CONS_v0.1.nc")
#oct 1991
nc.ORAS.1991o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199110_CONS_v0.1.nc")
#nov 1991
nc.ORAS.1991n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199111_CONS_v0.1.nc")

##1992
#sept 1992
nc.ORAS.1992s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199209_CONS_v0.1.nc")
#oct 1992
nc.ORAS.1992o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199210_CONS_v0.1.nc")
#nov 1992
nc.ORAS.1992n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199211_CONS_v0.1.nc")

##1993
#sept 1993
nc.ORAS.1993s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199309_CONS_v0.1.nc")
#oct 1993
nc.ORAS.1993o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199310_CONS_v0.1.nc")
#nov 1993
nc.ORAS.1993n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199311_CONS_v0.1.nc")

##1994
#sept 1994
nc.ORAS.1994s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199409_CONS_v0.1.nc")
#oct 1994
nc.ORAS.1994o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199410_CONS_v0.1.nc")
#nov 1994
nc.ORAS.1994n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199411_CONS_v0.1.nc")

##1995
#sept 1995
nc.ORAS.1995s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199509_CONS_v0.1.nc")
#oct 1995
nc.ORAS.1995o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199510_CONS_v0.1.nc")
#nov 1995
nc.ORAS.1995n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199511_CONS_v0.1.nc")

##1996
#sept 1996
nc.ORAS.1996s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199609_CONS_v0.1.nc")
#oct 1996
nc.ORAS.1996o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199610_CONS_v0.1.nc")
#nov 1996
nc.ORAS.1996n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199611_CONS_v0.1.nc")

##1997
#sept 1997
nc.ORAS.1997s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199709_CONS_v0.1.nc")
#oct 1997
nc.ORAS.1997o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199710_CONS_v0.1.nc")
#nov 1997
nc.ORAS.1997n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199711_CONS_v0.1.nc")

##1998
#sept 1998
nc.ORAS.1998s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199809_CONS_v0.1.nc")
#oct 1998
nc.ORAS.1998o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199810_CONS_v0.1.nc")
#nov 1998
nc.ORAS.1998n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199811_CONS_v0.1.nc")

##1999
#sept 1999
nc.ORAS.1999s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199909_CONS_v0.1.nc")
#oct 1999
nc.ORAS.1999o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199910_CONS_v0.1.nc")
#nov 1999
nc.ORAS.1999n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_199911_CONS_v0.1.nc")

##2000
#sept 2000
nc.ORAS.2000s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200009_CONS_v0.1.nc")
#oct 2000
nc.ORAS.2000o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200010_CONS_v0.1.nc")
#nov 2000
nc.ORAS.2000n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200011_CONS_v0.1.nc")

##2001
#sept 2001
nc.ORAS.2001s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200109_CONS_v0.1.nc")
#oct 2001
nc.ORAS.2001o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200110_CONS_v0.1.nc")
#nov 2001
nc.ORAS.2001n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200111_CONS_v0.1.nc")

##2002
#sept 2002
nc.ORAS.2002s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200209_CONS_v0.1.nc")
#oct 2002
nc.ORAS.2002o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200210_CONS_v0.1.nc")
#nov 2002
nc.ORAS.2002n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200211_CONS_v0.1.nc")

##2003
#sept 2003
nc.ORAS.2003s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200309_CONS_v0.1.nc")
#oct 2003
nc.ORAS.2003o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200310_CONS_v0.1.nc")
#nov 2003
nc.ORAS.2003n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200311_CONS_v0.1.nc")

##2004
#sept 2004
nc.ORAS.2004s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200409_CONS_v0.1.nc")
#oct 2004
nc.ORAS.2004o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200410_CONS_v0.1.nc")
#nov 2004
nc.ORAS.2004n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200411_CONS_v0.1.nc")

##2005
#sept 2005
nc.ORAS.2005s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200509_CONS_v0.1.nc")
#oct 2005
nc.ORAS.2005o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200510_CONS_v0.1.nc")
#nov 2005
nc.ORAS.2005n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200511_CONS_v0.1.nc")

##2006
#sept 2006
nc.ORAS.2006s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200609_CONS_v0.1.nc")
#oct 2006
nc.ORAS.2006o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200610_CONS_v0.1.nc")
#nov 2006
nc.ORAS.2006n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200611_CONS_v0.1.nc")

##2007
#sept 2007
nc.ORAS.2007s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200709_CONS_v0.1.nc")
#oct 2007
nc.ORAS.2007o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200710_CONS_v0.1.nc")
#nov 2007
nc.ORAS.2007n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200711_CONS_v0.1.nc")

##2008
#sept 2008
nc.ORAS.2008s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200809_CONS_v0.1.nc")
#oct 2008
nc.ORAS.2008o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200810_CONS_v0.1.nc")
#nov 2008
nc.ORAS.2008n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200811_CONS_v0.1.nc")

##2009
#sept 2009
nc.ORAS.2009s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200909_CONS_v0.1.nc")
#oct 2009
nc.ORAS.2009o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200910_CONS_v0.1.nc")
#nov 2009
nc.ORAS.2009n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_200911_CONS_v0.1.nc")

##2010
#sept 2010
nc.ORAS.2010s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201009_CONS_v0.1.nc")
#oct 2010
nc.ORAS.2010o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201010_CONS_v0.1.nc")
#nov 2010
nc.ORAS.2010n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201011_CONS_v0.1.nc")

##2011
#sept 2011
nc.ORAS.2011s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201109_CONS_v0.1.nc")
#oct 2011
nc.ORAS.2011o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201110_CONS_v0.1.nc")
#nov 2011
nc.ORAS.2011n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201111_CONS_v0.1.nc")

##2012
#sept 2012
nc.ORAS.2012s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201209_CONS_v0.1.nc")
#oct 2012
nc.ORAS.2012o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201210_CONS_v0.1.nc")
#nov 2012
nc.ORAS.2012n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201211_CONS_v0.1.nc")

##2013
#sept 2013
nc.ORAS.2013s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201309_CONS_v0.1.nc")
#oct 2013
nc.ORAS.2013o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201310_CONS_v0.1.nc")
#nov 2013
nc.ORAS.2013n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201311_CONS_v0.1.nc")

##2014
#sept 2014
nc.ORAS.2014s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201409_CONS_v0.1.nc")
#oct 2014
nc.ORAS.2014o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201410_CONS_v0.1.nc")
#nov 2014
nc.ORAS.2014n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201411_CONS_v0.1.nc")

##2015
#sept 2015
nc.ORAS.2015s <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201509_OPER_v0.1.nc")
#oct 2015
nc.ORAS.2015o <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201510_OPER_v0.1.nc")
#nov 2015
nc.ORAS.2015n <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/ORAS5/sosstsst_control_monthly_highres_2D_201511_OPER_v0.1.nc")

#TODO: add in years 2016-2019

```


```{r import_additional}
#ORA-S5 from 1979 to 2018


```


```{r load_ins}
setwd("~/CO_AUS/Aus_CO-main/pIOD")
load("sst_base.rda") #mostly for the lon.values and lat.values
```

```{r functions}
array_setup <- function(nc.data, wide.lon, wide.lat){

  #lon/lat matrices [nx, ny] ([lon, lat])
  get.lat <- ncvar_get(nc.data, "nav_lat")
  get.lon <- ncvar_get(nc.data, "nav_lon")
  
  #get sst data
  sst.oras <- ncvar_get(nc.data, "sosstsst")
  
  iod.mask <- get.lat >= wide.lat[1] & get.lat <= wide.lat[2] &
          get.lon >= wide.lon[1] & get.lon <= wide.lon[2]
  
  lat.in <- get.lat[iod.mask]
  lon.in <- get.lon[iod.mask]
  sst.oras.in <- sst.oras[iod.mask]
  
  return(list(lon = lon.in,
              lat = lat.in,
              sst = sst.oras.in))
}


reformat_interpolate <- function(lon.in, lat.in, sst.oras.in, 
                                 grid.list){
  #TODO: adjust raw numbers if needed
  #reformat 
  n <- length(lon.in) /363
  
  seq.list <- split(1:59169, ceiling(seq_along(1:59169) / 363))
  
  #take chunk of 363 reorder, and remove duplicate data manually
  new.order <- c(191:363, 3:190)
  
  #TODO: setup additional matrix just for the sst data
  sst.mat <- matrix(NA, ncol = 3)
  colnames(sst.mat) < c("lon", "lat", "sst")
  for (i in 1:n) {
    lon.temp <- lon.in[seq.list[[i]]]
    lat.temp <- lat.in[seq.list[[i]]]
    sst.temp <- sst.oras.in[seq.list[[i]]]
    
    #temporary matrix setup
    temp.mat <- cbind(lon = lon.temp[new.order], 
                      lat = lat.temp[new.order], 
                      sst = sst.temp[new.order])
    
    sst.mat <- rbind(sst.mat, temp.mat)
  }
  
  sst.df <- as.data.frame(sst.mat[-1,])
  
  get.x <- unique(sst.df$lon)
  get.y <- unique(sst.df$lat)
  
  sst.oras.matrix <- matrix(sst.df$sst, nrow = 361)
  
  #interpolate

  obj.oras <- list(x = get.x, y = get.y, z = sst.oras.matrix)
  
  out.interp <- interp.surface.grid(obj.oras, grid.list) #not currently working (duplicated data)

  return(out.interp$z)
}

```


```{r data_clean}

#wide, reduced boundary (Indian Ocean)
wide_maxLon <- 120
wide_minLon <- 30
wide_maxLat <- 20
wide_minLat <- -20

wide.lon <- c(wide_minLon, wide_maxLon)
wide.lat <- c(wide_minLat, wide_maxLat)

#setup gridlist
grid.list <- list(x = lon.values,
                  y = rev(lat.values))

oras_list <- list(nc.ORAS.1982s, nc.ORAS.1982o, nc.ORAS.1982n,
                  nc.ORAS.1983s, nc.ORAS.1983o, nc.ORAS.1983n,
                  nc.ORAS.1984s, nc.ORAS.1984o, nc.ORAS.1984n,
                  nc.ORAS.1985s, nc.ORAS.1985o, nc.ORAS.1985n,
                  nc.ORAS.1986s, nc.ORAS.1986o, nc.ORAS.1986n,
                  nc.ORAS.1987s, nc.ORAS.1987o, nc.ORAS.1987n,
                  nc.ORAS.1988s, nc.ORAS.1988o, nc.ORAS.1988n,
                  nc.ORAS.1989s, nc.ORAS.1989o, nc.ORAS.1989n,
                  nc.ORAS.1990s, nc.ORAS.1990o, nc.ORAS.1990n,
                  nc.ORAS.1991s, nc.ORAS.1991o, nc.ORAS.1991n,
                  nc.ORAS.1992s, nc.ORAS.1992o, nc.ORAS.1992n,
                  nc.ORAS.1993s, nc.ORAS.1993o, nc.ORAS.1993n,
                  nc.ORAS.1994s, nc.ORAS.1994o, nc.ORAS.1994n,
                  nc.ORAS.1995s, nc.ORAS.1995o, nc.ORAS.1995n,
                  nc.ORAS.1996s, nc.ORAS.1996o, nc.ORAS.1996n,
                  nc.ORAS.1997s, nc.ORAS.1997o, nc.ORAS.1997n,
                  nc.ORAS.1998s, nc.ORAS.1998o, nc.ORAS.1998n,
                  nc.ORAS.1999s, nc.ORAS.1999o, nc.ORAS.1999n,
                  nc.ORAS.2000s, nc.ORAS.2000o, nc.ORAS.2000n,
                  nc.ORAS.2001s, nc.ORAS.2001o, nc.ORAS.2001n,
                  nc.ORAS.2002s, nc.ORAS.2002o, nc.ORAS.2002n,
                  nc.ORAS.2003s, nc.ORAS.2003o, nc.ORAS.2003n,
                  nc.ORAS.2004s, nc.ORAS.2004o, nc.ORAS.2004n,
                  nc.ORAS.2005s, nc.ORAS.2005o, nc.ORAS.2005n,
                  nc.ORAS.2006s, nc.ORAS.2006o, nc.ORAS.2006n,
                  nc.ORAS.2007s, nc.ORAS.2007o, nc.ORAS.2007n,
                  nc.ORAS.2008s, nc.ORAS.2008o, nc.ORAS.2008n,
                  nc.ORAS.2009s, nc.ORAS.2009o, nc.ORAS.2009n,
                  nc.ORAS.2010s, nc.ORAS.2010o, nc.ORAS.2010n,
                  nc.ORAS.2011s, nc.ORAS.2011o, nc.ORAS.2011n,
                  nc.ORAS.2012s, nc.ORAS.2012o, nc.ORAS.2012n,
                  nc.ORAS.2013s, nc.ORAS.2013o, nc.ORAS.2013n,
                  nc.ORAS.2014s, nc.ORAS.2014o, nc.ORAS.2014n,
                  nc.ORAS.2015s, nc.ORAS.2015o, nc.ORAS.2015n)
                  
#sst array setup
sst.oras.array <- NULL
for (j in 1:length(oras_list)) {
  temp.nc <- oras_list[[j]]
  
  out.temp <- array_setup(temp.nc, wide.lon, wide.lat)
  
  temp.sst <- reformat_interpolate(out.temp$lon, out.temp$lat, 
                     out.temp$sst, grid.list)
  
  sst.oras.array <- abind(sst.oras.array, temp.sst, along = 3)
}

rm(nc.ORAS.1982s, nc.ORAS.1982o, nc.ORAS.1982n,
    nc.ORAS.1983s, nc.ORAS.1983o, nc.ORAS.1983n,
    nc.ORAS.1984s, nc.ORAS.1984o, nc.ORAS.1984n,
    nc.ORAS.1985s, nc.ORAS.1985o, nc.ORAS.1985n,
    nc.ORAS.1986s, nc.ORAS.1986o, nc.ORAS.1986n,
    nc.ORAS.1987s, nc.ORAS.1987o, nc.ORAS.1987n,
    nc.ORAS.1988s, nc.ORAS.1988o, nc.ORAS.1988n,
    nc.ORAS.1989s, nc.ORAS.1989o, nc.ORAS.1989n,
    nc.ORAS.1990s, nc.ORAS.1990o, nc.ORAS.1990n,
    nc.ORAS.1991s, nc.ORAS.1991o, nc.ORAS.1991n,
    nc.ORAS.1992s, nc.ORAS.1992o, nc.ORAS.1992n,
    nc.ORAS.1993s, nc.ORAS.1993o, nc.ORAS.1993n,
    nc.ORAS.1994s, nc.ORAS.1994o, nc.ORAS.1994n,
    nc.ORAS.1995s, nc.ORAS.1995o, nc.ORAS.1995n,
    nc.ORAS.1996s, nc.ORAS.1996o, nc.ORAS.1996n,
    nc.ORAS.1997s, nc.ORAS.1997o, nc.ORAS.1997n,
    nc.ORAS.1998s, nc.ORAS.1998o, nc.ORAS.1998n,
    nc.ORAS.1999s, nc.ORAS.1999o, nc.ORAS.1999n,
    nc.ORAS.2000s, nc.ORAS.2000o, nc.ORAS.2000n,
    nc.ORAS.2001s, nc.ORAS.2001o, nc.ORAS.2001n,
    nc.ORAS.2002s, nc.ORAS.2002o, nc.ORAS.2002n,
    nc.ORAS.2003s, nc.ORAS.2003o, nc.ORAS.2003n,
    nc.ORAS.2004s, nc.ORAS.2004o, nc.ORAS.2004n,
    nc.ORAS.2005s, nc.ORAS.2005o, nc.ORAS.2005n,
    nc.ORAS.2006s, nc.ORAS.2006o, nc.ORAS.2006n,
    nc.ORAS.2007s, nc.ORAS.2007o, nc.ORAS.2007n,
    nc.ORAS.2008s, nc.ORAS.2008o, nc.ORAS.2008n,
    nc.ORAS.2009s, nc.ORAS.2009o, nc.ORAS.2009n,
    nc.ORAS.2010s, nc.ORAS.2010o, nc.ORAS.2010n,
    nc.ORAS.2011s, nc.ORAS.2011o, nc.ORAS.2011n,
    nc.ORAS.2012s, nc.ORAS.2012o, nc.ORAS.2012n,
    nc.ORAS.2013s, nc.ORAS.2013o, nc.ORAS.2013n,
    nc.ORAS.2014s, nc.ORAS.2014o, nc.ORAS.2014n,
    nc.ORAS.2015s, nc.ORAS.2015o, nc.ORAS.2015n)

dim(sst.oras.array)

```

```{r save_data}
#TODO: save the data 

setwd("~/CO_AUS/Aus_CO-main/pIOD")

save(sst.oras.array, 
     file = "sst_oras5.rda")
```


```{r test_sstanoms}
#checking for sst-anoms with the oras data, modifications from sst.anoms function
A.new <- aperm(sst.oras.array, perm = c(3, 2, 1))  # reorder data as [time, lat, lon]
  
#get dimensions from reordered array
nx <- dim(A.new)[3]
ny <- dim(A.new)[2] 
nt <- dim(A.new)[1]

#if only using son:  
#TODO: adjust the original sst.anom function to account for only son months
nyears <- nt %/% 3
A.temp <- array(A.new, dim = c(3, nyears, ny, nx))

A.son <- apply(A.temp[1:3, , , ], c(2,3,4), mean, na.rm = TRUE) #already at correct subset
rm(A.temp)
```



# Test : Old work

```{r TESTdata_clean}
#TODO: explore the data to see how we need to prep it

#wide, reduced boundary (Indian Ocean)
wide_maxLon <- 120
wide_minLon <- 30
wide_maxLat <- 20
wide_minLat <- -20

lon.range <- c(wide_minLon, wide_maxLon)
lat.range <- c(wide_minLat, wide_maxLat)

#TODO: functionalize this since we will have a lot of individual files.

#lon/lat matrices [nx, ny] ([lon, lat])
get.lat <- ncvar_get(nc.ORAS.1982S, "nav_lat")
get.lon <- ncvar_get(nc.ORAS.1982S, "nav_lon")

#get sst data
sst.oras <- ncvar_get(nc.ORAS.1982S, "sosstsst")

iod.mask <- get.lat >= wide_minLat & get.lat <= wide_maxLat &
        get.lon >= wide_minLon & get.lon <= wide_maxLon

lat.in <- get.lat[iod.mask]
lon.in <- get.lon[iod.mask]
sst.oras.in <- sst.oras[iod.mask]

#reformat 
n <- length(lon.in) /363

seq.list <- split(1:59169, ceiling(seq_along(1:59169) / 363))

#take chunk of 363 reorder, and remove duplicate data manually
new.order <- c(191:363, 3:190)

#TODO: setup additional matrix just for the sst data
sst.mat <- matrix(NA, ncol = 3)
colnames(sst.mat) < c("lon", "lat", "sst")
for (i in 1:n) {
  lon.temp <- lon.in[seq.list[[i]]]
  lat.temp <- lat.in[seq.list[[i]]]
  sst.temp <- sst.oras.in[seq.list[[i]]]
  
  #temporary matrix setup
  temp.mat <- cbind(lon = lon.temp[new.order], 
                    lat = lat.temp[new.order], 
                    sst = sst.temp[new.order])
  
  sst.mat <- rbind(sst.mat, temp.mat)
}

sst.df <- as.data.frame(sst.mat[-1,])

get.x <- unique(sst.df$lon)
get.y <- unique(sst.df$lat)

sst.oras.matrix <- matrix(sst.df$sst, nrow = 361)

#note the correction here is just to interp to a grid
grid.list <- list(x = lon.values,
                  y = rev(lat.values))
obj.oras <- list(x = get.x, y = get.y, z = sst.oras.matrix)

out.interp <- interp.surface.grid(obj.oras, grid.list) #not currently working (duplicated data)

#test output
image.plot(list(x=lon.values, y=rev(lat.values), z=out.interp$z),
           col = ryb_col, breaks = brks)
world(add = TRUE)

 
#TODO: finalize the interpolation to a grid then funcationalize and run through SST anoms


#interpolation example code for SODA3.3.1
sst.interp.SODA <- NULL
for (i in 1:dim(sst.soda.new)[3]) {
  base.obj <- list(x = lon.values.soda, y = rev(lat.values.soda), z = sst.soda.new[,,i])

  grid.list <- list(x = lon.values,
                    y = lat.values)
  
  out.interp <- interp.surface.grid(base.obj, grid.list)
  
  interp.mat <- out.interp$z[ ,ncol(out.interp$z):1 ]
  
  sst.interp.SODA <- abind(sst.interp.SODA, interp.mat, along = 3)
}




as.index <- which(iod.mask, arr.ind = TRUE)
sst.oras.mat <- sst.oras[as.index]
```

```{r temp_clean}
#TODO: re-sort everything to get the correct order since these are fucked!
n <- length(lon.in) /363

seq.list <- split(1:59169, ceiling(seq_along(1:59169) / 363))

#test run for seq.list and individual 
#seq.list[[1]]
lon.test <- lon.in[seq.list[[1]]]
lat.test <- lat.in[seq.list[[1]]]
sst.test <- sst.oras.in[seq.list[[1]]]

test.mat <- cbind(lon = lon.test[new.order], 
                     lat = lat.test[new.order], 
                     sst = sst.oras.in[new.order])

#take chunk of 363 reorder, and remove duplicate data manually
new.order <- c(191:363, 3:190)

#TODO: setup additional matrix just for the sst data
sst.mat <- matrix(NA, ncol = 3)
colnames(sst.mat) < c("lon", "lat", "sst")
for (i in 1:n) {
  lon.temp <- lon.in[seq.list[[i]]]
  lat.temp <- lat.in[seq.list[[i]]]
  sst.temp <- sst.oras.in[seq.list[[i]]]
  
  #temporary matrix setup
  temp.mat <- cbind(lon = lon.temp[new.order], 
                    lat = lat.temp[new.order], 
                    sst = sst.temp[new.order])
  
  sst.mat <- rbind(sst.mat, temp.mat)
}

sst.df <- as.data.frame(sst.mat[-1,])

get.x <- unique(sst.df$lon)
get.y <- unique(sst.df$lat)

sst.oras.matrix <- matrix(sst.df$sst, nrow = 361)

oras.max <-max(sst.oras.matrix, na.rm = TRUE)
ryb_col <- rev(divergingx_hcl(n = 18, palette = "RdYlBu"))
brks <- c(-2:0, 4, 8, 12, 16, 20:30, oras.max)


image.plot(list(x=get.x, y=get.y, z=sst.oras.matrix),
           col = ryb_col, breaks = brks)
world(add = TRUE)
```



```{r temp_interp}
#for getting the interp surface working with the ORAS data

#this issue might be in all the na data at lower lon values,
## use other data product to figure out when the NAs stop
test.sst <- sst.array[,,1]

#note the correction here is just to interp to a grid
grid.list <- list(x = lon.values,
                  y = rev(lat.values))
obj.oras <- list(x = lon.new, y = rev(lat.new), z = sst.oras.new)

out.interp <- interp.surface.grid(obj.oras, grid.list) #not currently working (duplicated data)

#temp work on interp surface grid, delete when fixed
x <- grid.list$x
length(unique(x))
y <- grid.list$y
M <- length(x)
N <- length(y)
out <- matrix(NA, nrow = M, ncol = N)
ncol(out)

test.new <- cbind(rep(x[i], N), y)

i <- 5
out[i,] <- interp.surface(obj.oras, cbind(rep(x[i], N), y)) 
length(interp.surface(obj.oras, cbind(rep(x[i], N), y))) #produces 80 instead of 40

#internals of interp.surface
obj <- obj.oras
loc <- cbind(rep(x[i], N), y)

x <- obj$x
range(x)

y <- obj$y
length(y)
range(y)

z <- obj$z
nx <- length(x)
ny <- length(y)

length(loc[, 1])

lx <- approx(x, 1:nx, loc[, 1])$y
ly <- approx(y, 1:ny, loc[, 2])$y
lx1 <- floor(lx)
ly1 <- floor(ly)



x[lx1]
y[ly1]

cbind(lx1, ly1)
z[cbind(lx1, ly1)]

ex <- lx - lx1
ey <- ly - ly1

ex[lx1 == nx] <- 1
ey[ly1 == ny] <- 1
lx1[lx1 == nx] <- nx - 1
ly1[ly1 == ny] <- ny - 1



z[cbind(lx1, ly1)] * (1 - ex) * (1 - ey) + z[cbind(lx1 + 
        1, ly1)] * ex * (1 - ey) + z[cbind(lx1, ly1 + 1)] * (1 - 
        ex) * ey + z[cbind(lx1 + 1, ly1 + 1)] * ex * ey

```



```{r test_viz}
#for testing the visualization of a single month and year. 

quilt.plot(lon.in, lat.in, sst.oras.in, zlim = c(20, 31))
world(add= TRUE)


image(get.lon, rev(get.lat), iod.mask, col = c("white", "steelblue"),
      xlim = c(30, 120), ylim = c(-20,20))
world(add= TRUE)
```




