---
title: "IODsst_2019"
author: "Ryan Peterson"
date: "2025-08-31"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Library}
#.nc files
suppressMessages(library(ncdf4))
suppressMessages(library(terra))

# date/data mgmt
suppressMessages(library(lubridate))
suppressMessages(library(abind))

#visualization and interpolation
suppressMessages(library(fields))
suppressMessages(library(colorspace))
suppressMessages(library(RColorBrewer)) #colorRampPalette
suppressMessages(library(scales)) #for adjusting opacity

#matlab function (e.g. detrend)
suppressMessages(library(pracma))
```

Extend from 2015 to 2019:
1. replicate the GODAS 2019 point from fig 1 (cai et al 2019)
2. replicate data up to 2019 from 2025 Indian Ocean paper

```{r load_functions}
setwd("~/CO_AUS/Aus_CO-main/pIOD")

source("pIOD_functions.R") #sst.anom and eof functions
```

```{r load_data}
setwd()
#load in other data
load("sstGODAS.rda") #load sst.GODAS data
```


```{r setup}
#indian ocean region
wide_maxLon <- 120
wide_minLon <- 30
wide_maxLat <- 20
wide_minLat <- -20

#pIOD (40, -5) X (100, 5)
pIOD_maxLon <- 100
pIOD_minLon <- 40 
pIOD_maxLat <- 5
pIOD_minLat <- -5

#indian ocean grid
lon.wide <- seq(wide_minLon, wide_maxLon, by = 1)
lat.wide <- seq(wide_minLat, wide_maxLat, by = 1)

#grid list from 
grid.list <- list(x = lon.wide,
                  y = lat.wide)
```


# GODAS Data Prep

## Import Data

```{r GODAS_import}
setwd("~/CO_AUS/Aus_CO-main")

#GODAS data only (yearly .nc 1982-2015)
#1982
nc.GODAS.1982 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1982.nc")

#1983
nc.GODAS.1983 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1983.nc")

#1984
nc.GODAS.1984 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1984.nc")

#1985
nc.GODAS.1985 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1985.nc")

#1986
nc.GODAS.1986 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1986.nc")

#1987
nc.GODAS.1987 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1987.nc")

#1988
nc.GODAS.1988 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1988.nc")

#1989
nc.GODAS.1989 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1989.nc")

#1990
nc.GODAS.1990 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1990.nc")

#1991
nc.GODAS.1991 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1991.nc")

#1992
nc.GODAS.1992 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1992.nc")

#1993
nc.GODAS.1993 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1993.nc")

#1994
nc.GODAS.1994 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1994.nc")

#1995
nc.GODAS.1995 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1995.nc")

#1996
nc.GODAS.1996 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1996.nc")

#1997
nc.GODAS.1997 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1997.nc")

#1998
nc.GODAS.1998 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1998.nc")

#1999
nc.GODAS.1999 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1999.nc")

#2000
nc.GODAS.2000 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2000.nc")

#2001
nc.GODAS.2001 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2001.nc")

#2002
nc.GODAS.2002 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2002.nc")

#2003
nc.GODAS.2003 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2003.nc")

#2004
nc.GODAS.2004 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2004.nc")

#2005
nc.GODAS.2005 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2005.nc")

#2006
nc.GODAS.2006 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2006.nc")

#2007
nc.GODAS.2007 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2007.nc")

#2008
nc.GODAS.2008 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2008.nc")

#2009
nc.GODAS.2009 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2009.nc")

#2010
nc.GODAS.2010 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2010.nc")

#2011
nc.GODAS.2011 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2011.nc")

#2012
nc.GODAS.2012 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2012.nc")

#2013
nc.GODAS.2013 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2013.nc")

#2014
nc.GODAS.2014 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2014.nc")

#2015
nc.GODAS.2015 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2015.nc")

```

```{r additional_GODAS_import}
#include back to 1980
#1980
nc.GODAS.1980 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1980.nc")

#1981
nc.GODAS.1981 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.1981.nc")

#include up to 2019
#2016
nc.GODAS.2016 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2016.nc")

#2017
nc.GODAS.2017 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2017.nc")

#2018
nc.GODAS.2018 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2018.nc")

#2019
nc.GODAS.2019 <- nc_open("~/CO_AUS/Aus_CO-main/pIOD/Data/pottmp.2019.nc")
```

## Prep Functions

```{r prep_functions}
#sorting/extraction of godas .nc data
godas_prep <- function(nc.data){
  
  #extract lon.lat
  lon.grid.temp <- nc.data[["dim"]][["lon"]][["vals"]]
  lat.grid.temp <- nc.data[["dim"]][["lat"]][["vals"]]
  
  #reorder lon for 
  lon.grid.temp[lon.grid.temp >= 180] <- lon.grid.temp[lon.grid.temp >= 180] - 360
  lon.order.temp <- order(lon.grid.temp)
  
  lon.grid.temp <- lon.grid.temp[lon.order.temp]
  
  #reorder lat
  lat.order.temp <- order(lat.grid.temp, decreasing = TRUE)
  lat.grid.temp <- lat.grid.temp[lat.order.temp]
  
  #times for months
  times.temp <- ncvar_get(nc.data, "time") # days since 1800-01-01 00:00:0.0
  times.temp <- as_datetime("1800-01-01T00:00:00") + days(times.temp)
  
  #temps, as array (lon, lat, level, time)
  #TODO adjust from K to c (K - 273.15)
  sst.temp <- ncvar_get(nc.data, "pottmp")
  sst.temp <- sst.temp[lon.order.temp, lat.order.temp, 1, ] #level: depth 5m
  
  #adjust to C from K (c = K - 273.15)
  sst.temp <- sst.temp - 273.15
  
  #return lon, lat, time, sst
  return(list(
    lon = lon.grid.temp,
    lat = lat.grid.temp,
    time = times.temp,
    sst = sst.temp))
}


```

## Cleaning w/o Interpolation

```{r data_cleaning}
#data cleaning 
godas_list <- list(nc.GODAS.1982, nc.GODAS.1983, nc.GODAS.1984, nc.GODAS.1985, nc.GODAS.1986, 
                   nc.GODAS.1987, nc.GODAS.1988, nc.GODAS.1989, nc.GODAS.1990, nc.GODAS.1991,
                   nc.GODAS.1992, nc.GODAS.1993, nc.GODAS.1994, nc.GODAS.1995, nc.GODAS.1996,
                   nc.GODAS.1997, nc.GODAS.1998, nc.GODAS.1999, nc.GODAS.2000, nc.GODAS.2001,
                   nc.GODAS.2002, nc.GODAS.2003, nc.GODAS.2004, nc.GODAS.2005, nc.GODAS.2006,
                   nc.GODAS.2007, nc.GODAS.2008, nc.GODAS.2009, nc.GODAS.2010, nc.GODAS.2011,
                   nc.GODAS.2012, nc.GODAS.2013, nc.GODAS.2014, nc.GODAS.2015, nc.GODAS.2016,
                   nc.GODAS.2017, nc.GODAS.2018, nc.GODAS.2019)

#get lon, lat, sst, and times
sst.GODAS.new2 <- NULL
for (i in 1:length(godas_list)) {
  nc.temp <- godas_list[[i]] 
  
  temp.nc.godas <- godas_prep(nc.temp)
  temp.lon <- temp.nc.godas$lon
  temp.lat <- temp.nc.godas$lat
  temp.sst <- temp.nc.godas$sst
  
  #get reduce range (indian ocean region)
  new.lon <- temp.lon[temp.lon <= wide_maxLon & temp.lon >= wide_minLon]
  lon.range <- range(which(temp.lon <= wide_maxLon & temp.lon >= wide_minLon))
  new.lat <- temp.lat[temp.lat <= wide_maxLat & temp.lat >= wide_minLat]
  lat.range <- range(which(temp.lat <= wide_maxLat & temp.lat >= wide_minLat))
  
  #assign
  sst.temp <- temp.sst[lon.range[1]:lon.range[2], lat.range[1]:lat.range[2], ]
  
  sst.GODAS.new2 <- abind(sst.GODAS.new2, sst.temp, along = 3)
}

GODAS.lon <- new.lon
GODAS.lat <- new.lat

rm(nc.GODAS.1982, nc.GODAS.1983, nc.GODAS.1984, nc.GODAS.1985, nc.GODAS.1986, 
                   nc.GODAS.1987, nc.GODAS.1988, nc.GODAS.1989, nc.GODAS.1990, nc.GODAS.1991,
                   nc.GODAS.1992, nc.GODAS.1993, nc.GODAS.1994, nc.GODAS.1995, nc.GODAS.1996,
                   nc.GODAS.1997, nc.GODAS.1998, nc.GODAS.1999, nc.GODAS.2000, nc.GODAS.2001,
                   nc.GODAS.2002, nc.GODAS.2003, nc.GODAS.2004, nc.GODAS.2005, nc.GODAS.2006,
                   nc.GODAS.2007, nc.GODAS.2008, nc.GODAS.2009, nc.GODAS.2010, nc.GODAS.2011,
                   nc.GODAS.2012, nc.GODAS.2013, nc.GODAS.2014, nc.GODAS.2015)

dim(sst.GODAS.new2)


```


# SST Anom Prep

(get sst anomalies)

```{r get_anoms}
#use sst.anom function
sst.anom.godas2 <- sst.anoms(sst.GODAS.new2, quadratic = FALSE)

```

## Interpolation

```{r interpolate_anoms}
dim.GODAS <- dim(sst.GODAS.new2)

#GODAS Interpolat
nx <- dim.GODAS[1]
ny <- dim.GODAS[2]
nt <- nrow(sst.anom.godas2$anom)

#GODAS lat: new.lat, lon: new.lon 
GODAS.new <- array(sst.anom.godas2$anom, dim = c(nt, ny, nx)) 
GODAS.new <- aperm(GODAS.new, c(3, 2, 1)) #as [nx, ny, nt]

GODAS.anom2 <- NULL
for (j in seq_len(nt)) {
  GODAS.obj <-  list(x = new.lon, y = new.lat, z = GODAS.new[,,j])

  temp.interp <- interp.surface.grid(GODAS.obj, grid.list)
  GODAS.anom2 <- abind(GODAS.anom2, temp.interp$z, along = 3)
}

dim(GODAS.anom2)
```

## pIOD Range

```{r pIOD}

```



