---
title: "model_results"
author: "Ryan Peterson"
date: "2025-06-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
#libraries
suppressMessages( library(hierNet)) 
suppressMessages(library(glmnet)) 
suppressMessages( library( lubridate))
suppressMessages(library(grid))

suppressMessages( library(scales)) #for adjusting opacity
```

```{r data_functions}
# data and functions
setwd("~/CO_AUS/Aus_CO-main/Interactions")

load( "Data/ne_data.rda")
load( "Data/se_data.rda")
load( "Data/bounded_data.rda")
load( "Data/data_matrix.rda")
load( "Data/lag_list.rda")
load( "Data/data_quantile.rda")

#functions:
#source("group_functions.R") #grouping/clustering
source("group_functionsNew.R") #New grouping/clustering
source("refit_functions.R") #coef/refit functions
```

```{r setup}
#season years/weeks
season_weeks <- c(38:52, 1:14)
season_years <- unique(bounded_resp_df$year)

seasons <- c()
for (i in 1:(length(season_years)-1)) {
  temp_season <- paste0(season_years[i], "-", season_years[i+1])
  #print(temp_season)  
  seasons <- c(seasons, temp_season)
}
rm(i, temp_season)

#center response data
NEbase_matrix <- scale(resp_matrix[ ,1:32], center = TRUE, scale = FALSE)
SEbase_matrix <- scale(resp_matrix[ ,33:64], center = TRUE, scale = FALSE)

#NEAus
NEAus_1 <- NEbase_matrix[ ,1:12] 
NEAus_2 <- NEbase_matrix[ ,13:17]
NEAus_3 <- NEbase_matrix[ ,18:32]

#NEAus
SEAus_1 <- SEbase_matrix[ ,1:16] 
SEAus_2 <- SEbase_matrix[ ,17:20] 
SEAus_3 <- SEbase_matrix[ ,21:32]

NEAus_mat <- list(NEAus_1, NEAus_2, NEAus_3)
SEAus_mat <- list(SEAus_1, SEAus_2, SEAus_3)

rm(NEAus_1, NEAus_2, NEAus_3, SEAus_1, SEAus_2, SEAus_3)


#NEAus
NEAus_1 <- NEbase_matrix[ ,4:12] 
NEAus_2 <- NEbase_matrix[ ,13:17]
NEAus_3 <- NEbase_matrix[ ,18:32]

#NEAus
SEAus_1 <- SEbase_matrix[ ,4:16] 
SEAus_2 <- SEbase_matrix[ ,17:20] 
SEAus_3 <- SEbase_matrix[ ,21:32]

NEAusmat_new <- list(NEAus_1, NEAus_2, NEAus_3)
SEAusmat_new <- list(SEAus_1, SEAus_2, SEAus_3)

rm(NEAus_1, NEAus_2, NEAus_3, SEAus_1, SEAus_2, SEAus_3)
```


```{r NE_data}
#old groups
NEpreds_old <- NElag_old(NE_laglist = NE_laglist_std, j = 1:19)
NEresp_old <- NEresp_3group(NEAus_mat = NEAus_mat, j = 1:19)

#new groups
NE_preds <- NElag_3group(NE_laglist = NE_laglist_std, j = 1:19)
NE_resp <- NEresp_3group(NEAus_mat = NEAusmat_new, j = 1:19)
#NE_preds_q75 <- NElag_3group(NE_laglist = NE_laglist_q75, j = 1:19)

#new groups w/o 2019-2020
NEpreds_wo <- NElag_3group(NE_laglist = NE_laglist_std, j = -c(19))
NEresp_wo <- NEresp_3group(NEAus_mat = NEAusmat_new, j = -c(19))

```


# NE Aus Group 1

```{r old_model}
#NE Aus Group 1
NEAus1 <- output_groupWard[[1]]

NErefit1 <- refit_bic(NEAus1$hierpath, max_index = 50, ebic.gamma = 0.25, gic.gamma = 2.15,
                      lambda.min = FALSE, AIC.c = FALSE,
                      intercept = FALSE,
                      resp = NEresp_old[[1]], preds = NEpreds_old[[1]], 
                      preds_quant = NEpreds_old[[1]])

NErefit1[[5]]
NErefit1[[5]][,c(1,5,6)]

which.min(NErefit1[[5]][ ,5]) #ridge BIC 
which.min(NErefit1[[5]][ ,6]) #lasso BIC 

i <- 2
ridge_coef <- NErefit1[[4]][[i]]
ridge_coef
length(ridge_coef)

```

Testing unspecified lambdas for reduced group 1.

```{r redo_new}
#TODO: redo old model fit for group 1 without week (run when I start a multi-hour break)
#we need to see the full 50 selected lambda for the new group 1 weeks
y_1 <- as.numeric(NE_resp[[1]])

X_1 <- cbind(as.matrix(NE_preds[[1]][ ,1:260]))
  
NEout1_new <- hierNet.path( X_1, y_1, strong = TRUE, nlam = 50,
                              diagonal = TRUE, trace = 0) 
```

```{r refit_redo}
NErefit1_redo <- refit_bic(NEout1_new, max_index = 20, ebic.gamma = 0.25, gic.gamma = 2.15,
                      lambda.min = FALSE, AIC.c = FALSE,
                      intercept = FALSE,
                      resp = NE_resp[[1]], preds = NE_preds[[1]], 
                      preds_quant = NE_preds[[1]])

NErefit1_redo[[5]]
NErefit1_redo[[5]][,c(1,5,6)]


which.min(NErefit1_redo[[5]][ ,5]) #ridge BIC 
which.min(NErefit1_redo[[5]][ ,6]) #lasso BIC 

i <- 1
ridge_coef <- NErefit1_redo[[4]][[i]]
ridge_coef
length(ridge_coef)
```


```{r test_new}
y_1 <- as.numeric(NE_resp[[1]])

X_1 <- cbind(as.matrix(NE_preds[[1]][ ,1:260]))
  
NEout1_test <- hierNet.path( X_1, y_1, strong = TRUE, nlam = 20,
                              diagonal = TRUE, trace = 0) 
```

```{r refit_test}
NErefit1_test <- refit_bic(NEout1_test, max_index = 20, ebic.gamma = 0.25, gic.gamma = 2.15,
                      lambda.min = FALSE, AIC.c = FALSE,
                      intercept = FALSE,
                      resp = NE_resp[[1]], preds = NE_preds[[1]], 
                      preds_quant = NE_preds[[1]])

NErefit1_test[[5]]
NErefit1_test[[5]][,c(1,5,6)]


which.min(NErefit1_test[[5]][ ,5]) #ridge BIC 
which.min(NErefit1_test[[5]][ ,6]) #lasso BIC 

i <- 1
ridge_coef <- NErefit1_test[[4]][[i]]
ridge_coef
length(ridge_coef)

lambda_fit1_test <- round(NErefit1_test[[5]][ ,1], 2)

plot(1:20, NErefit1_test[[5]][ ,5], type ="b" ,axes = FALSE,
     xlab = "lambda", "")
box()
axis(2)
axis(1, at = 1:20, labels = lambda_fit1_test)
```

## New model (with 2019/2020)

```{r}
lambda_seq <- seq(750, 580, length.out = 32)

y_1 <- as.numeric(NE_resp[[1]])

X_1 <- cbind(as.matrix(NE_preds[[1]][ ,1:260]))
  
NE1_path <- hierNet.path( X_1, y_1, strong = TRUE, lamlist = lambda_seq,
                              diagonal = TRUE, trace = 0) 
 
```

```{r main_refit}
NEcoefs1 <- get_coefs(NE1_path, max_index = 32, 
                      resp = NE_resp[[1]], preds = NE_preds[[1]], 
                      preds_quant =NE_preds[[1]])

NErefit1 <- refit_bic(NE1_path, max_index = 32, ebic.gamma = 0.25, gic.gamma = 2.15,
                      lambda.min = FALSE, AIC.c = FALSE,
                      intercept = FALSE,
                      resp = NE_resp[[1]], preds = NE_preds[[1]], 
                      preds_quant =NE_preds[[1]])

NErefit1[[5]]

NErefit1[[5]][,c(1,5,6)]
NErefit1[[5]][,c(1,8,9)]

which.min(NErefit1[[5]][ , 5]) #ridge BIC 
which.min(NErefit1[[5]][ , 6]) #lasso BIC 

which.min(NErefit1[[5]][ , 8]) #ridge eBIC 
which.min(NErefit1[[5]][ , 9]) #lasso eBIC 

i <- 1
ridge_coef <- NErefit1[[4]][[i]]
NEridge1_main <- ridge_coef
ridge_coef
length(ridge_coef)

#get LM coefs
j <- 1
lm_coef <- NErefit1[[2]][[j]]
lm_coef
length(lm_coef)

summary(NErefit1[[1]][[j]])

NEcoefs1[[2]]

```


## New model (without 2019/2020)

```{r }
lambda_seq <- seq(750, 575, length.out = 32)

y_1 <- as.numeric(NEresp_wo[[1]])

X_1 <- cbind(as.matrix(NEpreds_wo[[1]][ ,1:260]))
  
NE1path_wo <- hierNet.path( X_1, y_1, strong = TRUE, lamlist = lambda_seq,
                              diagonal = TRUE, trace = 0) 
```


```{r}
NErefit1_wo <- refit_bic(NE1path_wo, max_index = 32, ebic.gamma = 0.25, gic.gamma = 2.15,
                      lambda.min = FALSE, AIC.c = FALSE,
                      intercept = FALSE,
                      resp = NEresp_wo[[1]], preds = NEpreds_wo[[1]], 
                      preds_quant =NEpreds_wo[[1]])

NErefit1_wo[[5]]

NErefit1_wo[[5]][,c(1,5,6)]
NErefit1_wo[[5]][,c(1,8,9)]

which.min(NErefit1_wo[[5]][ , 5]) #ridge BIC 
which.min(NErefit1_wo[[5]][ , 6]) #lasso BIC 

which.min(NErefit1_wo[[5]][ , 8]) #ridge eBIC 
which.min(NErefit1_wo[[5]][ , 9]) #lasso eBIC 

i <- 1
ridge_coef <- NErefit1_wo[[4]][[i]]
NEridge1_wo <- ridge_coef
ridge_coef
length(ridge_coef)
```


## Plots


```{r plots}
NEridge1_main


#setwd("~/CO_AUS/Aus_CO-main/Interactions/Figures")

#png(filename = "NE1_newest.png", width = 3000, height = 3000, res = 300)
layout(matrix(c(1, 6,
                2, 6,
                3, 6,
                4, 6,
                5, 6), ncol = 2, byrow = TRUE),
       widths = c(1.5, 1), heights = c(1, 1, 1, 1, 1))

par(oma = c(1, 1, 3, 9))

# Store links
links <- list()

# --- Data Set-up --- 
## Nino
NE1_ninolag <- c(9:10)
NE1_ninocoef <- NEridge1_main[1:2]

## DMI

## TSA
NE1_tsalag <- c(15)
NE1_tsacoef <- NEridge1_main[3]

# --- Plot 1: Nino ---
par(mar = c(4, 4, 2, 1))
plot(NE1_ninolag, NE1_ninocoef, pch = 22, 
     col = "grey4", bg =  alpha("green4",.95), cex = 1.5,
     xlim = c(1,52), 
     ylim = c(-1,1),
     xlab = "", ylab = "")
abline(h = 0, lty = 2)
title("Nino", adj = 0)

# --- Plot 2: DMI ---
par(mar = c(4, 4, 2, 1))
plot(1, 0,type = "n",
     xlim = c(1,52), 
     ylim = c(-1,1),
     xlab = "", ylab = "")
abline(h = 0, lty = 2)
title("DMI", adj = 0)

# --- Plot 3: TSA ---
par(mar = c(4, 4, 2, 1))
plot(NE1_tsalag, NE1_tsacoef, pch = 22, col = "black",
       bg =  alpha("darkorange3", 0.95), xlim = c(1,52), cex = 1.4,
     ylim = c(-1,1),
     xlab = "", ylab = "Coefficients", cex.lab = 1.33)
abline(h = 0, lty = 2)
title("TSA", adj = 0)


## ---- Plot 4: SAM ---
plot(1, 0,type = "n",
     xlim = c(1,52), 
     ylim = c(-1,1),
     xlab = "", ylab = "")
abline(h = 0, lty = 2)
title("SAM (AAO)", adj = 0)

## ---- Plot 5: OLR ---
plot(1, 0,type = "n",
     xlim = c(1,52), 
     ylim = c(-1,1),
     xlab = "Lag", ylab = "")
abline(h = 0, lty = 2)
title("OLR", adj = 0)

# --- Plot 6: Interaction Effects ---
par(mar = c(4, 4, 2, 2))

int_range <- c(-1,1)

plot(NEridge1_main[1], 0, type = "n", main = "", 
     ylim = c(0,1), xlim = int_range,
     xlab = "Coefficients", cex.lab = 1.33,
     yaxt = "n",  ylab = "")
abline(v= 0, lty = 2)



#outer text and legends
par(xpd = NA)
legend("topright", inset = c(-0.52, 0.00),
       title = "Nino",
       legend = c("Fit w/ 2019/2020",  "Fit w/o 2019/2020"),
       pch = c(22, 24),
       col = c("grey4", "grey4"),
       pt.bg = c("green4", "chartreuse2"),
       pt.cex = c(1.5, 1.33))
legend("topright", inset = c(-0.52, 0.23),
       title = "DMI",
       legend = c("Fit w/ 2019/2020",  "Fit w/o 2019/2020"),
       pch = c(22,  24),
       col = c("grey4",  "grey4"),
       pt.bg = c("magenta4", "plum2"),
       pt.cex = c(1.5, 1.33))

legend("right", inset = c(-0.52, 0.00),
       title = "TSA",
       legend = c("Fit w/ 2019/2020", "Fit w/o 2019/2020"),
       pch = c(22, 24),
       col = c("grey4", "grey4"),
       pt.bg = c("darkorange3", "darkgoldenrod2"),
       pt.cex = c(1.5, 1.33))

legend("bottomright", inset = c(-0.52, 0.26),
       title = "SAM (AAO)",
       legend = c("Fit w/ 2019/2020", "Fit w/o 2019/2020"),
       pch = c(22, 24),
       col = c("grey4", "grey4"),
       pt.bg = c("red3", "coral2"),
       pt.cex = c(1.5, 1.33))

legend("bottomright", inset = c(-0.52, 0.05),
       title = "OLR",
       legend = c("Fit w/ 2019/2020",  "Fit w/o 2019/2020"),
       pch = c(22, 24),
       col = c("grey4", "grey4"),
       pt.bg = c("turquoise4", "paleturquoise3"),
       pt.cex = c(1.5, 1.33))


mtext("NE Aus Group 1 (Weeks 38-46)", outer = TRUE, cex = 1.5, font = 1)

```



# SE Aus Group 1


