---
title: "pca_work"
author: "Ryan Peterson"
date: "2024-09-24"
output: pdf_document
---

```{r library}
#find pca library
```


```{r data_import}
setwd("~/CO_AUS/Aus_CO-main")

# Data
load( "bounded_pred.rda")
load( "bounded_resp.rda")
load( "ne_data.rda")
load( "se_data.rda")

load( "data_matrix.rda")
```


Note: we don't want to use PCA for variable reduction because then we no longer have interpretability. 


```{r standardize_Te}
#standardize each data set

#standardize preds with scale
test_preds <- scale(bounded_pred_df[ ,2:5])

pca_test <- prcomp(test_preds, center = TRUE, scale. = TRUE)

summary(pca_test)

screeplot(pca_test, type = "lines")
```



```{r weekly_model_test}
test_matrix <- NE_list[[1]][ ,-c(1,2)]
rownames(test_matrix) <- NE_list[[1]]$Seasons

test_preds_35 <- scale(t(test_matrix))

pca_test <- prcomp(test_preds_35, center = TRUE, scale. = TRUE)

summary(pca_test)

screeplot(pca_test, type = "lines")

pca_test$rotation

pca_test$x

plot(pca_test$x[,1], pca_test$x[,2], xlab = "PC1", ylab = "PC2", main = "PCA")
text(pca_test$x[,1], pca_test$x[,2], labels = colnames(test_matrix), pos = 4)
```


```{r pca_preds}
#TODO: expand setup section to include all climate indices.
temp_nino <- NE_list[[1]][,3:54]

#standardized data
nino_pred <- scale(bounded_pred_df$nino.anomaly, center = TRUE, scale = TRUE)

#remove last 14 weeks of data (from early 2020)
nino_pred <- nino_pred[-(1041:1054)]

nino_df <- as.data.frame(matrix(NA, ncol = 52))
colnames(nino_df) <- colnames(temp_nino)

years <- unique(bounded_pred_df$year)[-21]
#TODO: expand this to include all 4 climate mode indices with this loop.
for (i in years) {
  temp_index <- which(bounded_pred_df$year == i)
  nino_df <- rbind(nino_df, nino_pred[temp_index])
}

nino_df <- nino_df[-1, ]
rownames(nino_df) <- years
```

```{r pca_check}
#TODO: rename a lot of the below variables and add in SE Aus PCA
resp_df <- as.data.frame(resp_matrix)

pca_nino <- prcomp(resp_matrix[,1:32], center = TRUE, scale. = TRUE, retx = TRUE)

summary(pca_nino)

screeplot(pca_nino, type = "lines", pch = 16)

pca_nino$rotation

pca_nino$x

plot(pca_nino$x[,1], pca_nino$x[,2], xlim = c(-10, 20),
     xlab = "PC1", ylab = "PC2", main = "PCA Response", pch=16)
text(pca_nino$x[,1], pca_nino$x[,2], labels = colnames(resp_df[,1:32]), pos = 4)
```

