---
title: "prediction_work"
author: "Ryan Peterson"
date: "2024-10-28"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library}
suppressMessages(library(genlasso)) #used for fused lasso 
```

# Data Set-Up

```{r data}
setwd("~/CO_AUS/Aus_CO-main")

load( "ne_data.rda")
load( "se_data.rda")

load( "bounded_data.rda")
load( "data_matrix.rda")

load( "lag_list.rda")
```


```{r setup}
season_weeks <- c(35:52, 1:14)

#get years from bounded_resp
season_years <- unique(bounded_resp_df$year)

seasons <- c()
for (i in 1:(length(season_years)-1)) {
  temp_season <- paste0(season_years[i], "-", season_years[i+1])
  #print(temp_season)  
  seasons <- c(seasons, temp_season)
}


rm(i, season_years, temp_season)
```

## Data Prep

```{r group_response}
NEbase_matrix <- scale(resp_matrix[-19, 1:32], center = TRUE, scale = FALSE)

SEbase_matrix <- scale(resp_matrix[-19, 33:64], center = TRUE, scale = FALSE)

#group response matrices

#NEAus
NEAus_1 <- NEbase_matrix[ ,1:3]
NEAus_2 <- NEbase_matrix[ ,4:8]
NEAus_3 <- NEbase_matrix[ ,9:12]
NEAus_4 <- NEbase_matrix[ ,13:17]
NEAus_5 <- NEbase_matrix[ ,18:21]
NEAus_6 <- NEbase_matrix[ ,22:32]

#SEAus
SEAus_1 <- SEbase_matrix[ ,1:3]
SEAus_2 <- SEbase_matrix[ ,4:7]
SEAus_3 <- SEbase_matrix[ ,8:16]
SEAus_4 <- SEbase_matrix[ ,17:20]
SEAus_5 <- SEbase_matrix[ ,21:32]

NEAus_mat <- list(NEAus_1, NEAus_2, NEAus_3, NEAus_4, NEAus_5, NEAus_6)
SEAus_mat <- list(SEAus_1, SEAus_2, SEAus_3, SEAus_4, SEAus_5)


#group response vectors list (as function)
#TODO: refine the following functions

#NE resp vectors
NEresp_grouping <- function(NEAus_mat, j = (1:19)){
  
  NEAus_mat <- lapply(NEAus_mat, function(mat) mat[j, ])
  
  NEAus1_resp <- as.vector(NEAus_mat[[1]])
  NEAus2_resp <- as.vector(NEAus_mat[[2]])
  NEAus3_resp <- as.vector(NEAus_mat[[3]])
  NEAus4_resp <- as.vector(NEAus_mat[[4]])
  NEAus5_resp <- as.vector(NEAus_mat[[5]])
  NEAus6_resp <- as.vector(NEAus_mat[[6]])
  
  NEAus_vec <- list(NEAus1_resp, NEAus2_resp, NEAus3_resp,
                    NEAus4_resp, NEAus5_resp, NEAus6_resp)
  
  return(NEAus_vec)
}

#SE resp vectors
SEresp_grouping <- function(SEAus_mat, j = (1:19)){
  
  SEAus_mat <- lapply(SEAus_mat, function(mat) mat[j, ])
  
  SEAus1_resp <- as.vector(SEAus_mat[[1]])
  SEAus2_resp <- as.vector(SEAus_mat[[2]])
  SEAus3_resp <- as.vector(SEAus_mat[[3]])
  SEAus4_resp <- as.vector(SEAus_mat[[4]])
  SEAus5_resp <- as.vector(SEAus_mat[[5]])
  
  SEAus_vec <- list(SEAus1_resp, SEAus2_resp, SEAus3_resp,
                    SEAus4_resp, SEAus5_resp)
  
  return(SEAus_vec) 
}  
```


```{r LagPred_functions}
#lag predictor set-up
#TODO: fine tune these functions for different groups
#goal is to enter in the grouping and get the appropriate outputs
#-currently manually set-up groups

## NE lag predictors
NElag_grouping <- function(NE_laglist, j = (1:19)){
  #row inclusion
  #j <- (1:19)


  #NE group 1: 35-37
  NE1_lag <- NE_laglist$`Week  35`[j, -(1:2)]
  NE1_lag <- rbind(NE1_lag, NE_laglist$`Week  36`[j, -(1:2)], NE_laglist$`Week  37`[j, -(1:2)])

  #NE group 2: 38-42
  NE2_lag <- NE_laglist$`Week  38`[j,-(1:2)]
  NE2_lag <- rbind(NE2_lag, NE_laglist$`Week  39`[j,-(1:2)], NE_laglist$`Week  40`[j,-(1:2)],
                 NE_laglist$`Week  41`[j,-(1:2)], NE_laglist$`Week  42`[j,-(1:2)])

  #NE group 3: 43-46
  NE3_lag <- NE_laglist$`Week  43`[j,-(1:2)]
  NE3_lag <- rbind(NE3_lag, NE_laglist$`Week  44`[j,-(1:2)], NE_laglist$`Week  45`[j,-(1:2)],
                 NE_laglist$`Week  46`[j,-(1:2)])

  #NE group 4: 47-51
  NE4_lag <- NE_laglist$`Week  47`[j,-(1:2)]
  NE4_lag <- rbind(NE4_lag, NE_laglist$`Week  48`[j,-(1:2)], NE_laglist$`Week  49`[j,-(1:2)],
                 NE_laglist$`Week  50`[j,-(1:2)], NE_laglist$`Week  51`[j,-(1:2)])

  #NE group 5: 52, 1-3
  NE5_lag <- NE_laglist$`Week  52`[j,-(1:2)]
  NE5_lag <- rbind(NE5_lag, NE_laglist$`Week  1`[j,-(1:2)], NE_laglist$`Week  2`[j,-(1:2)],
                 NE_laglist$`Week  3`[j,-(1:2)])

  #NE group 6: 4-14
  NE6_lag <- NE_laglist$`Week  4`[j,-(1:2)]
  NE6_lag <- rbind(NE6_lag, NE_laglist$`Week  5`[j,-(1:2)], NE_laglist$`Week  6`[j,-(1:2)],
                 NE_laglist$`Week  7`[j,-(1:2)], NE_laglist$`Week  8`[j,-(1:2)],
                 NE_laglist$`Week  9`[j,-(1:2)], NE_laglist$`Week  10`[j,-(1:2)],
                 NE_laglist$`Week  11`[j,-(1:2)], NE_laglist$`Week  12`[j,-(1:2)],
                 NE_laglist$`Week  13`[j,-(1:2)], NE_laglist$`Week  14`[j,-(1:2)])

  NEAus_preds <- list(NE1_lag, NE2_lag, NE3_lag, NE4_lag, NE5_lag, NE6_lag)
  return(NEAus_preds)
}  
  
## SE lag predictors
SElag_grouping <- function(SE_laglist, j = (1:19)){

  #SE group 1: 35-37
  SE1_lag <- SE_laglist$`Week  35`[j,-(1:2)]
  SE1_lag <- rbind(SE1_lag, SE_laglist$`Week  36`[j,-(1:2)], SE_laglist$`Week  37`[j,-(1:2)])
  
  #SE group 2: 38-41
  SE2_lag <- SE_laglist$`Week  38`[j,-(1:2)]
  SE2_lag <- rbind(SE2_lag, SE_laglist$`Week  39`[j,-(1:2)], SE_laglist$`Week  40`[j,-(1:2)],
                   SE_laglist$`Week  41`[j,-(1:2)])
  
  #SE group 3: 42-50
  SE3_lag <- SE_laglist$`Week  42`[j,-(1:2)]
  SE3_lag <- rbind(SE3_lag, SE_laglist$`Week  43`[j,-(1:2)], SE_laglist$`Week  44`[j,-(1:2)],
                   SE_laglist$`Week  45`[j,-(1:2)], SE_laglist$`Week  46`[j,-(1:2)],
                   SE_laglist$`Week  47`[j,-(1:2)], SE_laglist$`Week  48`[j,-(1:2)],
                   SE_laglist$`Week  49`[j,-(1:2)], SE_laglist$`Week  50`[j,-(1:2)])
  
  #SE group 4: 51-52,1-2
  SE4_lag <- SE_laglist$`Week  51`[j,-(1:2)]
  SE4_lag <- rbind(SE4_lag, SE_laglist$`Week  52`[j,-(1:2)], SE_laglist$`Week  1`[j,-(1:2)],
                   SE_laglist$`Week  2`[j,-(1:2)])
  
  #SE group 5: 3-14
  SE5_lag <- SE_laglist$`Week  3`[j,-(1:2)]
  SE5_lag <- rbind(SE5_lag, SE_laglist$`Week  4`[j,-(1:2)], SE_laglist$`Week  5`[j,-(1:2)],
                   SE_laglist$`Week  6`[j,-(1:2)], SE_laglist$`Week  7`[j,-(1:2)],
                   SE_laglist$`Week  8`[j,-(1:2)], SE_laglist$`Week  9`[j,-(1:2)],
                   SE_laglist$`Week  10`[j,-(1:2)], SE_laglist$`Week  11`[j,-(1:2)],
                   SE_laglist$`Week  12`[j,-(1:2)], SE_laglist$`Week  13`[j,-(1:2)],
                   SE_laglist$`Week  14`[j,-(1:2)])
  
  
  
  SEAus_preds <- list(SE1_lag, SE2_lag, SE3_lag, SE4_lag, SE5_lag)
  return(SEAus_preds)
}  
```

# Full Model Fused-Lasso

Not including the 2019/2020 Season

```{r}
#standardized lag predictors sans 2019/2020 seasons
test_preds <- NElag_grouping(NE_laglist = NE_laglist, j = -19)
test_resp <- NEresp_grouping(NEAus_mat = NEAus_mat, j = -19)

SE_preds <- SElag_grouping(SE_laglist = SE_laglist, j = -19)
SE_resp <- SEresp_grouping(SEAus_mat = SEAus_mat, j = -19)
```

```{r}
mean(SE_preds[[1]]$nino_lag1)
```


```{r d_matrix}
#TODO: check this to make sure nothing is wrong
##Also, we may need an extra row at the end if AAO 52 keeps being weird
### or reorder the climate index predictors.

D <- getD1d(52)
empty_D <- matrix(rep(0, (52*51)) , ncol = 52, nrow = 51)
D1 <- cbind(D, empty_D, empty_D, empty_D)
D2 <- cbind(empty_D, D, empty_D, empty_D)
D3 <- cbind(empty_D, empty_D, D, empty_D)
D4 <- cbind(empty_D, empty_D, empty_D, D)

#D5 <- cbind(empty_D, empty_D, empty_D, empty_D, D) #OLR matrix
D_new <- rbind(D1, D2, D3, D4)
```


```{r NEfusion_preds}
#group 1
NE_resp1 <- test_resp[[1]]
NE_pred1 <- as.matrix(test_preds[[1]][ ,1:208])

NEfuse_group1 <- fusedlasso(y = NE_resp1, X = NE_pred1, D_new, gamma = 1)
```

```{r}
#group 2
NE_resp2 <- test_resp[[2]]
NE_pred2 <- as.matrix(test_preds[[2]][ ,1:208])

NEfuse_group2 <- fusedlasso(y = NE_resp2, X = NE_pred2, D_new, gamma = 1)

#group 3
NE_resp3 <- test_resp[[3]]
NE_pred3 <- as.matrix(test_preds[[3]][ ,1:208])

NEfuse_group3 <- fusedlasso(y = NE_resp3, X = NE_pred3, D_new, gamma = 1)

#group 4
NE_resp4 <- test_resp[[4]]
NE_pred4 <- as.matrix(test_preds[[4]][ ,1:208])

NEfuse_group4 <- fusedlasso(y = NE_resp4, X = NE_pred4, D_new, gamma = 1)

#group 5
NE_resp5 <- test_resp[[5]]
NE_pred5 <- as.matrix(test_preds[[5]][ ,1:208])

NEfuse_group5 <- fusedlasso(y = NE_resp5, X = NE_pred5, D_new, gamma = 1)

#group 6
NE_resp6 <- test_resp[[6]]
NE_pred6 <- as.matrix(test_preds[[6]][ ,1:208])

NEfuse_group6 <- fusedlasso(y = NE_resp6, X = NE_pred6, D_new, gamma = 1)

```

```{r}
save(NEfuse_group1, NEfuse_group2, NEfuse_group3, 
     NEfuse_group4, NEfuse_group5, NEfuse_group6, 
     file = "NE_fuse.rda")
```




```{r NEcoeff_setup}
#group 1 coef
n <- length(NE_resp1)
p <- ncol(NE_pred1)
lambda1 <- sqrt(n * log(p))

NEgroup1_coef <- coef(NEfuse_group1, lambda = lambda1)

#group 2 coef
n <- length(NE_resp2)
p <- ncol(NE_pred2)
lambda2 <- sqrt(n * log(p))

NEgroup2_coef <- coef(NEfuse_group2, lambda = lambda2)

#group 3 coef
n <- length(NE_resp3)
p <- ncol(NE_pred3)
lambda3 <- sqrt(n * log(p))

NEgroup3_coef <- coef(NEfuse_group3, lambda = lambda3)

#group 4 coef
n <- length(NE_resp4)
p <- ncol(NE_pred4)
lambda4 <- sqrt(n * log(p))

NEgroup4_coef <- coef(NEfuse_group4, lambda = lambda4)

#group 5 coef
n <- length(NE_resp5)
p <- ncol(NE_pred5)
lambda5 <- sqrt(n * log(p))

NEgroup5_coef <- coef(NEfuse_group5, lambda = lambda5)

#group 6 coef
n <- length(NE_resp6)
p <- ncol(NE_pred6)
lambda6 <- sqrt(n * log(p))

NEgroup6_coef <- coef(NEfuse_group6, lambda = lambda6)

#extract each index
nino_coef1 <- NEgroup1_coef$beta[1:52,]
dmi_coef1 <- NEgroup1_coef$beta[53:104,]
tsa_coef1 <- NEgroup1_coef$beta[105:156,]
aao_coef1 <- NEgroup1_coef$beta[157:208,]

nino_coef2 <- NEgroup2_coef$beta[1:52,]
dmi_coef2 <- NEgroup2_coef$beta[53:104,]
tsa_coef2 <- NEgroup2_coef$beta[105:156,]
aao_coef2 <- NEgroup2_coef$beta[157:208,]

nino_coef3 <- NEgroup3_coef$beta[1:52,]
dmi_coef3 <- NEgroup3_coef$beta[53:104,]
tsa_coef3 <- NEgroup3_coef$beta[105:156,]
aao_coef3 <- NEgroup3_coef$beta[157:208,]

nino_coef4 <- NEgroup4_coef$beta[1:52,]
dmi_coef4 <- NEgroup4_coef$beta[53:104,]
tsa_coef4 <- NEgroup4_coef$beta[105:156,]
aao_coef4 <- NEgroup4_coef$beta[157:208,]

nino_coef5 <- NEgroup5_coef$beta[1:52,]
dmi_coef5 <- NEgroup5_coef$beta[53:104,]
tsa_coef5 <- NEgroup5_coef$beta[105:156,]
aao_coef5 <- NEgroup5_coef$beta[157:208,]

nino_coef6 <- NEgroup6_coef$beta[1:52,]
dmi_coef6 <- NEgroup6_coef$beta[53:104,]
tsa_coef6 <- NEgroup6_coef$beta[105:156,]
aao_coef6 <- NEgroup6_coef$beta[157:208,]


```


```{r NEcoef_viz}

#TODO: add in legend for each plot, increase the lwd for visibility. 

plot(1:52, nino_coef1, type = "l", xlab = "Lag", ylab = "Coeficients",
     main = "NE Group 1", ylim = range(NEgroup1_coef$beta), 
     col = "darkmagenta")
lines(1:52, dmi_coef1, col = "blue")
lines(1:52, tsa_coef1, col = "red")
lines(1:52, aao_coef1, col = "darkgreen")
abline(h = 0, lty = 2)

plot(1:52, nino_coef2, type = "l", xlab = "Lag", ylab = "Coeficients",
     main = "NE Group 2", ylim = range(NEgroup2_coef$beta), 
     col = "darkmagenta")
lines(1:52, dmi_coef2, col = "blue")
lines(1:52, tsa_coef2, col = "red")
lines(1:52, aao_coef2, col = "darkgreen")
abline(h = 0, lty = 2)

plot(1:52, nino_coef3, type = "l", xlab = "Lag", ylab = "Coeficients",
     main = "NE Group 3", ylim = range(NEgroup3_coef$beta), 
     col = "darkmagenta")
lines(1:52, dmi_coef3, col = "blue")
lines(1:52, tsa_coef3, col = "red")
lines(1:52, aao_coef3, col = "darkgreen")
abline(h = 0, lty = 2)

plot(1:52, nino_coef4, type = "l", xlab = "Lag", ylab = "Coeficients",
     main = "NE Group 4", ylim = range(NEgroup4_coef$beta), 
     col = "darkmagenta")
lines(1:52, dmi_coef4, col = "blue")
lines(1:52, tsa_coef4, col = "red")
lines(1:52, aao_coef4, col = "darkgreen")
abline(h = 0, lty = 2)

plot(1:52, nino_coef5, type = "l", xlab = "Lag", ylab = "Coeficients",
     main = "NE Group 5", ylim = range(NEgroup5_coef$beta), 
     col = "darkmagenta")
lines(1:52, dmi_coef5, col = "blue")
lines(1:52, tsa_coef5, col = "red")
lines(1:52, aao_coef5, col = "darkgreen")
abline(h = 0, lty = 2)

plot(1:52, nino_coef6, type = "l", xlab = "Lag", ylab = "Coeficients",
     main = "NE Group 6", ylim = range(NEgroup6_coef$beta), 
     col = "darkmagenta")
lines(1:52, dmi_coef6, col = "blue")
lines(1:52, tsa_coef6, col = "red")
lines(1:52, aao_coef6, col = "darkgreen")
abline(h = 0, lty = 2)
```


```{r SEfusion_preds}
#group 1
SE_resp1 <- SE_resp[[1]]
SE_pred1 <- as.matrix(SE_preds[[1]][ ,1:208])

SEfuse_group1 <- fusedlasso(y = SE_resp1, X = SE_pred1, D_new, gamma = 1)

#group 2
SE_resp2 <- SE_resp[[2]]
SE_pred2 <- as.matrix(SE_preds[[2]][ ,1:208])

SEfuse_group2 <- fusedlasso(y = SE_resp2, X = SE_pred2, D_new, gamma = 1)

#group 3
SE_resp3 <- SE_resp[[3]]
SE_pred3 <- as.matrix(SE_preds[[3]][ ,1:208])

SEfuse_group3 <- fusedlasso(y = SE_resp3, X = SE_pred3, D_new, gamma = 1)

#group 4
SE_resp4 <- SE_resp[[4]]
SE_pred4 <- as.matrix(SE_preds[[4]][ ,1:208])

SEfuse_group4 <- fusedlasso(y = SE_resp4, X = SE_pred4, D_new, gamma = 1)

#group 5
SE_resp5 <- SE_resp[[5]]
SE_pred5 <- as.matrix(SE_preds[[5]][ ,1:208])

SEfuse_group5 <- fusedlasso(y = SE_resp5, X = SE_pred5, D_new, gamma = 1)
```


```{r}
save(SEfuse_group1, SEfuse_group2, SEfuse_group3, 
     SEfuse_group4, SEfuse_group5, file = "SE_fuse.rda")
```


```{r SEcoeff_setup}
#group 1 coef
n <- length(SE_resp1)
p <- ncol(SE_pred1)
lambda1 <- sqrt(n * log(p))

SEgroup1_coef <- coef(SEfuse_group1, lambda = lambda1)

#group 2 coef
n <- length(SE_resp2)
p <- ncol(SE_pred2)
lambda2 <- sqrt(n * log(p))

SEgroup2_coef <- coef(SEfuse_group2, lambda = lambda2)

#group 3 coef
n <- length(SE_resp3)
p <- ncol(SE_pred3)
lambda3 <- sqrt(n * log(p))

SEgroup3_coef <- coef(SEfuse_group3, lambda = lambda3)

#group 4 coef
n <- length(SE_resp4)
p <- ncol(SE_pred4)
lambda4 <- sqrt(n * log(p))

SEgroup4_coef <- coef(SEfuse_group4, lambda = lambda4)

#group 5 coef
n <- length(SE_resp5)
p <- ncol(SE_pred5)
lambda5 <- sqrt(n * log(p))

SEgroup5_coef <- coef(SEfuse_group5, lambda = lambda5)


#split coefs by index
SEnino_coef1 <- SEgroup1_coef$beta[1:52,]
SEdmi_coef1 <- SEgroup1_coef$beta[53:104,]
SEtsa_coef1 <- SEgroup1_coef$beta[105:156,]
SEaao_coef1 <- SEgroup1_coef$beta[157:208,]

SEnino_coef2 <- SEgroup2_coef$beta[1:52,]
SEdmi_coef2 <- SEgroup2_coef$beta[53:104,]
SEtsa_coef2 <- SEgroup2_coef$beta[105:156,]
SEaao_coef2 <- SEgroup2_coef$beta[157:208,]

SEnino_coef3 <- SEgroup3_coef$beta[1:52,]
SEdmi_coef3 <- SEgroup3_coef$beta[53:104,]
SEtsa_coef3 <- SEgroup3_coef$beta[105:156,]
SEaao_coef3 <- SEgroup3_coef$beta[157:208,]

SEnino_coef4 <- SEgroup4_coef$beta[1:52,]
SEdmi_coef4 <- SEgroup4_coef$beta[53:104,]
SEtsa_coef4 <- SEgroup4_coef$beta[105:156,]
SEaao_coef4 <- SEgroup4_coef$beta[157:208,]

SEnino_coef5 <- SEgroup5_coef$beta[1:52,]
SEdmi_coef5 <- SEgroup5_coef$beta[53:104,]
SEtsa_coef5 <- SEgroup5_coef$beta[105:156,]
SEaao_coef5 <- SEgroup5_coef$beta[157:208,]
```


```{r SEcoef_viz}

#TODO: add in legend for each plot, increase the lwd for visibility. 

plot(1:52, SEnino_coef1, type = "l", xlab = "Lag", ylab = "Coeficients",
     main = "SE Group 1", ylim = range(SEgroup1_coef$beta), 
     col = "darkmagenta")
lines(1:52, SEdmi_coef1, col = "blue")
lines(1:52, SEtsa_coef1, col = "red")
lines(1:52, SEaao_coef1, col = "darkgreen")
abline(h = 0, lty = 2)

plot(1:52, SEnino_coef2, type = "l", xlab = "Lag", ylab = "Coeficients",
     main = "SE Group 2", ylim = range(SEgroup2_coef$beta), 
     col = "darkmagenta")
lines(1:52, SEdmi_coef2, col = "blue")
lines(1:52, SEtsa_coef2, col = "red")
lines(1:52, SEaao_coef2, col = "darkgreen")
abline(h = 0, lty = 2)

plot(1:52, SEnino_coef3, type = "l", xlab = "Lag", ylab = "Coeficients",
     main = "SE Group 3", ylim = range(SEgroup3_coef$beta), 
     col = "darkmagenta")
lines(1:52, SEdmi_coef3, col = "blue")
lines(1:52, SEtsa_coef3, col = "red")
lines(1:52, SEaao_coef3, col = "darkgreen")
abline(h = 0, lty = 2)

plot(1:52, SEnino_coef4, type = "l", xlab = "Lag", ylab = "Coeficients",
     main = "SE Group 4", ylim = range(SEgroup4_coef$beta), 
     col = "darkmagenta")
lines(1:52, SEdmi_coef4, col = "blue")
lines(1:52, SEtsa_coef4, col = "red")
lines(1:52, SEaao_coef4, col = "darkgreen")
abline(h = 0, lty = 2)

plot(1:52, SEnino_coef5, type = "l", xlab = "Lag", ylab = "Coeficients",
     main = "SE Group 5", ylim = range(SEgroup5_coef$beta), 
     col = "darkmagenta")
lines(1:52, SEdmi_coef5, col = "blue")
lines(1:52, SEtsa_coef5, col = "red")
lines(1:52, SEaao_coef5, col = "darkgreen")
abline(h = 0, lty = 2)
```

# In-Sample Predictions

## Predictions for each week and season

since we have centered the data we do not have an intercept term.

```{r NEpreds}
#TODO: define the clusters with respect to the for loops

NEgroup1_list <- list()
ne_beta1 <- NEgroup1_coef$beta
for (k in 1:3) {
  ne_week <- NE_laglist[[k]]
  ne_week_std <- NE_laglist[[k]]
  
  week_preds <- as.data.frame(matrix(NA, ncol = 5))
  colnames(week_preds) <- c("True", "Pred", "Resid", "Pred_sd", "Resid_sd")
  
  for (i in 1:18) {
    temp_preds <- as.matrix(ne_week[i, 3:210])
    temp_preds_std <- as.matrix(ne_week_std[i, 3:210])
    
    temp_resp <- ne_week[i,2]
    
    pred_temp <- temp_preds %*% ne_beta1
    pred_temp_std <- temp_preds_std %*% ne_beta1
    
    temp_resid <- temp_resp - pred_temp
    temp_resid_std <- temp_resp - pred_temp_std
    
    week_preds <- rbind(week_preds, c(temp_resp, pred_temp, temp_resid, pred_temp_std, temp_resid_std))
  }
  
  week_preds <- week_preds[-1, ]
  
  NEgroup1_list[[paste("Week ", season_weeks[k])]] <- week_preds
}


NEgroup2_list <- list()
ne_beta2 <- NEgroup2_coef$beta
for (k in 4:8) {
  ne_week <- NE_laglist[[k]]
  ne_week_std <- NE_laglist[[k]]
  
  week_preds <- as.data.frame(matrix(NA, ncol = 5))
  colnames(week_preds) <- c("True", "Pred", "Resid", "Pred_sd", "Resid_sd")
  
  for (i in 1:18) {
    temp_preds <- as.matrix(ne_week[i, 3:210])
    temp_preds_std <- as.matrix(ne_week_std[i, 3:210])
    
    temp_resp <- ne_week[i,2]
    
    pred_temp <- temp_preds %*% ne_beta2
    pred_temp_std <- temp_preds_std %*% ne_beta2
    
    temp_resid <- temp_resp - pred_temp
    temp_resid_std <- temp_resp - pred_temp_std
    
    week_preds <- rbind(week_preds, c(temp_resp, pred_temp, temp_resid, pred_temp_std, temp_resid_std))
  }
  
  week_preds <- week_preds[-1, ]
  
  NEgroup2_list[[paste("Week ", season_weeks[k])]] <- week_preds
}


NEgroup3_list <- list()
ne_beta3 <- NEgroup3_coef$beta
for (k in 9:12) {
  ne_week <- NE_laglist[[k]]
  ne_week_std <- NE_laglist[[k]]
  
  week_preds <- as.data.frame(matrix(NA, ncol = 5))
  colnames(week_preds) <- c("True", "Pred", "Resid", "Pred_sd", "Resid_sd")
  
  for (i in 1:18) {
    temp_preds <- as.matrix(ne_week[i, 3:210])
    temp_preds_std <- as.matrix(ne_week_std[i, 3:210])
    
    temp_resp <- ne_week[i,2]
    
    pred_temp <- temp_preds %*% ne_beta3
    pred_temp_std <- temp_preds_std %*% ne_beta3
    
    temp_resid <- temp_resp - pred_temp
    temp_resid_std <- temp_resp - pred_temp_std
    
    week_preds <- rbind(week_preds, c(temp_resp, pred_temp, temp_resid, pred_temp_std, temp_resid_std))
  }
  
  week_preds <- week_preds[-1, ]
  
  NEgroup3_list[[paste("Week ", season_weeks[k])]] <- week_preds
}


NEgroup4_list <- list()
ne_beta4 <- NEgroup4_coef$beta
for (k in 13:17) {
  ne_week <- NE_laglist[[k]]
  ne_week_std <- NE_laglist[[k]]
  
  week_preds <- as.data.frame(matrix(NA, ncol = 5))
  colnames(week_preds) <- c("True", "Pred", "Resid", "Pred_sd", "Resid_sd")
  
  for (i in 1:18) {
    temp_preds <- as.matrix(ne_week[i, 3:210])
    temp_preds_std <- as.matrix(ne_week_std[i, 3:210])
    
    temp_resp <- ne_week[i,2]
    
    pred_temp <- temp_preds %*% ne_beta4
    pred_temp_std <- temp_preds_std %*% ne_beta4
    
    temp_resid <- temp_resp - pred_temp
    temp_resid_std <- temp_resp - pred_temp_std
    
    week_preds <- rbind(week_preds, c(temp_resp, pred_temp, temp_resid, pred_temp_std, temp_resid_std))
  }
  
  week_preds <- week_preds[-1, ]
  
  NEgroup4_list[[paste("Week ", season_weeks[k])]] <- week_preds
}


NEgroup5_list <- list()
ne_beta5 <- NEgroup5_coef$beta
for (k in 18:21) {
  ne_week <- NE_laglist[[k]]
  ne_week_std <- NE_laglist[[k]]
  
  week_preds <- as.data.frame(matrix(NA, ncol = 5))
  colnames(week_preds) <- c("True", "Pred", "Resid", "Pred_sd", "Resid_sd")
  
  for (i in 1:18) {
    temp_preds <- as.matrix(ne_week[i, 3:210])
    temp_preds_std <- as.matrix(ne_week_std[i, 3:210])
    
    temp_resp <- ne_week[i,2]
    
    pred_temp <- temp_preds %*% ne_beta5
    pred_temp_std <- temp_preds_std %*% ne_beta5
    
    temp_resid <- temp_resp - pred_temp
    temp_resid_std <- temp_resp - pred_temp_std
    
    week_preds <- rbind(week_preds, c(temp_resp, pred_temp, temp_resid, pred_temp_std, temp_resid_std))
  }
  
  week_preds <- week_preds[-1, ]
  
  NEgroup5_list[[paste("Week ", season_weeks[k])]] <- week_preds
}


NEgroup6_list <- list()
ne_beta6 <- NEgroup6_coef$beta
for (k in 22:32) {
  ne_week <- NE_laglist[[k]]
  ne_week_std <- NE_laglist[[k]]
  
  week_preds <- as.data.frame(matrix(NA, ncol = 5))
  colnames(week_preds) <- c("True", "Pred", "Resid", "Pred_sd", "Resid_sd")
  
  for (i in 1:18) {
    temp_preds <- as.matrix(ne_week[i, 3:210])
    temp_preds_std <- as.matrix(ne_week_std[i, 3:210])
    
    temp_resp <- ne_week[i,2]
    
    pred_temp <- temp_preds %*% ne_beta6
    pred_temp_std <- temp_preds_std %*% ne_beta6
    
    temp_resid <- temp_resp - pred_temp
    temp_resid_std <- temp_resp - pred_temp_std
    
    week_preds <- rbind(week_preds, c(temp_resp, pred_temp, temp_resid, pred_temp_std, temp_resid_std))
  }
  
  week_preds <- week_preds[-1, ]
  
  NEgroup6_list[[paste("Week ", season_weeks[k])]] <- week_preds
}

#test for single week:

#ne_week35 <- NE_laglist$`Week  35`
#test_week <- NE_laglist[[1]]

#ne_week35_std <- NE_laglist_std$`Week  35`
#ne_beta1 <- NEgroup1_coef$beta


#i <- 1
#week35_preds <- as.matrix(ne_week35[i, 3:210])
#week35_preds_std <- as.matrix(ne_week35_std[i, 3:210])

#ne_week35[i,2]
#week35_preds %*% ne_beta1
#week35_preds_std %*% ne_beta1
```

```{r SE_preds}

SEgroup1_list <- list()
se_beta1 <- SEgroup1_coef$beta
for (k in 1:3) {
  se_week <- SE_laglist[[k]]
  se_week_std <- SE_laglist[[k]]
  
  week_preds <- as.data.frame(matrix(NA, ncol = 5))
  colnames(week_preds) <- c("True", "Pred", "Resid", "Pred_sd", "Resid_sd")
  
  for (i in 1:18) {
    temp_preds <- as.matrix(se_week[i, 3:210])
    temp_preds_std <- as.matrix(se_week_std[i, 3:210])
    
    temp_resp <- se_week[i,2]
    
    pred_temp <- temp_preds %*% se_beta1
    pred_temp_std <- temp_preds_std %*% se_beta1
    
    temp_resid <- temp_resp - pred_temp
    temp_resid_std <- temp_resp - pred_temp_std
    
    week_preds <- rbind(week_preds, c(temp_resp, pred_temp, temp_resid, pred_temp_std, temp_resid_std))
  }
  
  week_preds <- week_preds[-1, ]
  
  SEgroup1_list[[paste("Week ", season_weeks[k])]] <- week_preds
}

SEgroup2_list <- list()
se_beta2 <- SEgroup2_coef$beta
for (k in 4:7) {
  se_week <- SE_laglist[[k]]
  se_week_std <- SE_laglist[[k]]
  
  week_preds <- as.data.frame(matrix(NA, ncol = 5))
  colnames(week_preds) <- c("True", "Pred", "Resid", "Pred_sd", "Resid_sd")
  
  for (i in 1:18) {
    temp_preds <- as.matrix(se_week[i, 3:210])
    temp_preds_std <- as.matrix(se_week_std[i, 3:210])
    
    temp_resp <- se_week[i,2]
    
    pred_temp <- temp_preds %*% se_beta2
    pred_temp_std <- temp_preds_std %*% se_beta2
    
    temp_resid <- temp_resp - pred_temp
    temp_resid_std <- temp_resp - pred_temp_std
    
    week_preds <- rbind(week_preds, c(temp_resp, pred_temp, temp_resid, pred_temp_std, temp_resid_std))
  }
  
  week_preds <- week_preds[-1, ]
  
  SEgroup2_list[[paste("Week ", season_weeks[k])]] <- week_preds
}

SEgroup3_list <- list()
se_beta3 <- SEgroup3_coef$beta
for (k in 8:16) {
  se_week <- SE_laglist[[k]]
  se_week_std <- SE_laglist[[k]]
  
  week_preds <- as.data.frame(matrix(NA, ncol = 5))
  colnames(week_preds) <- c("True", "Pred", "Resid", "Pred_sd", "Resid_sd")
  
  for (i in 1:18) {
    temp_preds <- as.matrix(se_week[i, 3:210])
    temp_preds_std <- as.matrix(se_week_std[i, 3:210])
    
    temp_resp <- se_week[i,2]
    
    pred_temp <- temp_preds %*% se_beta3
    pred_temp_std <- temp_preds_std %*% se_beta3
    
    temp_resid <- temp_resp - pred_temp
    temp_resid_std <- temp_resp - pred_temp_std
    
    week_preds <- rbind(week_preds, c(temp_resp, pred_temp, temp_resid, pred_temp_std, temp_resid_std))
  }
  
  week_preds <- week_preds[-1, ]
  
  SEgroup3_list[[paste("Week ", season_weeks[k])]] <- week_preds
}

SEgroup4_list <- list()
se_beta4 <- SEgroup4_coef$beta
for (k in 17:20) {
  se_week <- SE_laglist[[k]]
  se_week_std <- SE_laglist[[k]]
  
  week_preds <- as.data.frame(matrix(NA, ncol = 5))
  colnames(week_preds) <- c("True", "Pred", "Resid", "Pred_sd", "Resid_sd")
  
  for (i in 1:18) {
    temp_preds <- as.matrix(se_week[i, 3:210])
    temp_preds_std <- as.matrix(se_week_std[i, 3:210])
    
    temp_resp <- se_week[i,2]
    
    pred_temp <- temp_preds %*% se_beta4
    pred_temp_std <- temp_preds_std %*% se_beta4
    
    temp_resid <- temp_resp - pred_temp
    temp_resid_std <- temp_resp - pred_temp_std
    
    week_preds <- rbind(week_preds, c(temp_resp, pred_temp, temp_resid, pred_temp_std, temp_resid_std))
  }
  
  week_preds <- week_preds[-1, ]
  
  SEgroup4_list[[paste("Week ", season_weeks[k])]] <- week_preds
}

SEgroup5_list <- list()
se_beta5 <- SEgroup5_coef$beta
for (k in 21:32) {
  se_week <- SE_laglist[[k]]
  se_week_std <- SE_laglist[[k]]
  
  week_preds <- as.data.frame(matrix(NA, ncol = 5))
  colnames(week_preds) <- c("True", "Pred", "Resid", "Pred_sd", "Resid_sd")
  
  for (i in 1:18) {
    temp_preds <- as.matrix(se_week[i, 3:210])
    temp_preds_std <- as.matrix(se_week_std[i, 3:210])
    
    temp_resp <- se_week[i,2]
    
    pred_temp <- temp_preds %*% se_beta5
    pred_temp_std <- temp_preds_std %*% se_beta5
    
    temp_resid <- temp_resp - pred_temp
    temp_resid_std <- temp_resp - pred_temp_std
    
    week_preds <- rbind(week_preds, c(temp_resp, pred_temp, temp_resid, pred_temp_std, temp_resid_std))
  }
  
  week_preds <- week_preds[-1, ]
  
  SEgroup5_list[[paste("Week ", season_weeks[k])]] <- week_preds
}
```




## Residual Plots

```{r resid_old}
#resid histogram setup
#residuals for histogram

NEgroup_list <- c(NEgroup1_list, NEgroup2_list, NEgroup3_list, NEgroup4_list, NEgroup5_list, NEgroup6_list)
SEgroup_list <- c(SEgroup1_list, SEgroup2_list, SEgroup3_list, SEgroup4_list, SEgroup5_list)

NEresid_hist <- as.data.frame(matrix(NA, nrow = 18))
SEresid_hist <- as.data.frame(matrix(NA, nrow = 18))

for(j in 1:32){
  NEresid_hist <- cbind(NEresid_hist, NEgroup_list[[k]]$Resid)
  SEresid_hist <- cbind(SEresid_hist, SEgroup_list[[k]]$Resid)
}

NEresid_hist <- NEresid_hist[,-1]
SEresid_hist <- SEresid_hist[,-1]
```


```{r updated_resid}
#residual set-up for boxplot


residNE1_box_df <- data.frame(values = NA, group = NA)
residSE1_box_df <- data.frame(values = NA, group = NA)

for (i in 1:16) {
  temp_vals <- NEgroup_list[[i]]$Resid
  temp_group <- rep(season_weeks[i], length(NEgroup_list[[i]]$Resid))
  residNE1_box_df <- rbind(residNE1_box_df, list(temp_vals, temp_group))
  
  temp_vals1 <- SEgroup_list[[i]]$Resid
  temp_group1 <- rep(season_weeks[i], length(SEgroup_list[[i]]$Resid))
  residSE1_box_df <- rbind(residSE1_box_df, list(temp_vals1, temp_group1))
}

residNE1_box_df <- residNE1_box_df[-1, ]
residNE1_box_df$group <- as.factor(residNE1_box_df$group)
residNE1_box_df$values <- as.numeric(residNE1_box_df$values)

residSE1_box_df <- residSE1_box_df[-1, ]
residSE1_box_df$group <- as.factor(residSE1_box_df$group)
residSE1_box_df$values <- as.numeric(residSE1_box_df$values)


#second half
residNE2_box_df <- data.frame(values = NA, group = NA)
residSE2_box_df <- data.frame(values = NA, group = NA)
for (i in 17:32) {
  temp_vals <- NEgroup_list[[i]]$Resid
  temp_group <- rep(season_weeks[i], length(NEgroup_list[[i]]$Resid))
  residNE2_box_df <- rbind(residNE2_box_df, list(temp_vals, temp_group))
  
  temp_vals1 <- SEgroup_list[[i]]$Resid
  temp_group1 <- rep(season_weeks[i], length(SEgroup_list[[i]]$Resid))
  residSE2_box_df <- rbind(residSE2_box_df, list(temp_vals1, temp_group1))
}

residNE2_box_df <- residNE2_box_df[-1, ]
residNE2_box_df$group <- as.factor(residNE2_box_df$group)
residNE2_box_df$values <- as.numeric(residNE2_box_df$values)

residSE2_box_df <- residSE2_box_df[-1, ]
residSE2_box_df$group <- as.factor(residSE2_box_df$group)
residSE2_box_df$values <- as.numeric(residSE2_box_df$values)

resid_min <- min(residNE1_box_df$values, residNE2_box_df$values, 
                 residSE1_box_df$values, residSE2_box_df$values)

resid_max <- max(residNE1_box_df$values, residNE2_box_df$values, 
                 residSE1_box_df$values, residSE2_box_df$values)

resid_lim <- c(resid_min, resid_max)
```



```{r resid_boxplots}
#resid boxplots
setwd("~/CO_AUS/Aus_CO-main/Figures_Simple")

#TODO:update using resid_lim from the simplified linear model
resid_lim <- c(-20, 20)

png("NEresid_lasso1.png", width = 800, height = 600, res = 100)
par(mar = c(8, 4, 4, 2) + 0.1)
boxplot(values ~ group, data = residNE1_box_df, ylim = resid_lim, ylab = "Residuals", xlab = "",
        main = "NE Aus Model Residuals (Weeks 35 to 50)",axes = FALSE, pch = 20)
box()
axis(2)
axis(1, at = 1:16, labels = c(paste0("Week ", season_weeks[1:16])),
     las = 3)
abline(h = 0, lty = 2)
dev.off()


png("SEresid_lasso1.png", width = 800, height = 600, res = 100)
par(mar = c(8, 4, 4, 2) + 0.1)
boxplot(values ~ group, data = residSE1_box_df, ylim = resid_lim, ylab = "Residuals", xlab = "",
        main = "SE Aus Model Residuals (Weeks 35 to 50)",axes = FALSE, pch = 20)
box()
axis(2)
axis(1, at = 1:16, labels = c(paste0("Week ", season_weeks[1:16])),
     las = 3)
abline(h = 0, lty = 2)
dev.off()


png("NEresid_lasso2.png", width = 800, height = 600, res = 100)
par(mar = c(8, 4, 4, 2) + 0.1)
boxplot(values ~ group, data = residNE2_box_df, ylim = resid_lim, ylab = "Residuals", xlab = "",
        main = "NE Aus Model Residuals (Weeks 51, 52, 1 to 14)",axes = FALSE, pch = 20)
box()
axis(2)
axis(1, at = 1:16, labels = c(paste0("Week ", season_weeks[17:32])),
     las = 3)
abline(h = 0, lty = 2)
dev.off()


png("SEresid_lasso2.png", width = 800, height = 600, res = 100)
par(mar = c(8, 4, 4, 2) + 0.1)
boxplot(values ~ group, data = residSE2_box_df, ylim = resid_lim, ylab = "Residuals", xlab = "",
        main = "SE Aus Model Residuals (Weeks 51, 52, 1 to 14)",axes = FALSE, pch = 20)
box()
axis(2)
axis(1, at = 1:16, labels = c(paste0("Week ", season_weeks[17:32])),
     las = 3)
abline(h = 0, lty = 2)
dev.off()
```

```{r}

week35_mean <- mean(NEgroup1_list[[1]]$True)
diff_mean <- NEgroup1_list[[1]]$True - week35_mean
sum(diff_mean^2)

week35_resid <- NEgroup1_list[[1]]$Resid
sum(week35_resid^2)

1 - (sum(week35_resid^2)/sum(diff_mean^2))

```


# Out-of-sample Prediction (2019/2020 Season)

predict 2019/202 wildfire season

```{r}

```

# Test sections

```{r test_plots}


plot(1:52, nino_coef2, type = "l", xlab = "Lag", ylab = "Coeficients", main = "Nino", col = "darkmagenta")
abline(h = 0, lty = 2)

plot(1:52, dmi_coef2, type = "l", xlab = "Lag", ylab = "Coeficients", main = "DMI", col = "blue")
abline(h = 0, lty = 2)

plot(1:52, tsa_coef2, type = "l", xlab = "Lag", ylab = "Coeficients", main = "TSA", col = "red")
abline(h = 0, lty = 2)

plot(1:52, aao_coef2, type = "l", xlab = "Lag", ylab = "Coeficients", main = "AAO", col = "darkgreen")
abline(h = 0, lty = 2)
```



```{r prediction}

```


