---
title: "refit_cv"
author: "Ryan Peterson"
date: "2025-09-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library}
suppressMessages( library(hierNet)) #yes
suppressMessages( library(glmnet)) #test ridge regression for coefs
suppressMessages( library(RAMP)) #maybe
suppressMessages( library(MASS)) #for lm.ridge

suppressMessages( library(foreach)) #parallelization setup
suppressMessages( library(parallel))
suppressMessages( library(doParallel))

suppressMessages( library( lubridate)) #you know why
suppressMessages( library( colorspace)) #for some color alternatives
suppressMessages( library( fields)) #for set.panel() and others 
suppressMessages( library(ggpubr)) #nice tables for dfs (uses ggplot)

suppressMessages( library( Metrics)) #measurement metrics
suppressMessages( library( caret)) #for confusion matrix

suppressMessages( library( tictoc)) #some timing
```

```{r data_load}
#and functions
# Data Set-Up
setwd("~/CO_AUS/Aus_CO-main/Interactions")

load( "Data/ne_data.rda")
load( "Data/se_data.rda")
load( "Data/bounded_data.rda")
load( "Data/data_matrix.rda")
load( "Data/lag_list.rda")
load( "Data/data_quantile.rda")

#functions:
setwd("~/CO_AUS/Aus_CO-main/Interactions")
#source("group_functions.R") #grouping/clustering
source("group_functionsNew.R") #new groupings
source("refit_functions.R") #coef/refit functions

setwd("~/CO_AUS/Aus_CO-main/Interactions_New")
load("IOD_lag.rda") #data
source("predictionTest_functions.R") #predtest functions 
```

# Data Setup

```{r data_setup_new}
#season years/weeks
season_weeks <- c(35:52, 1:14)
season_years <- unique(bounded_resp_df$year)

seasons <- c()
for (i in 1:(length(season_years)-1)) {
  temp_season <- paste0(season_years[i], "-", season_years[i+1])
  #print(temp_season)  
  seasons <- c(seasons, temp_season)
}
rm(i, temp_season)

#center response data
NEbase_matrix <- scale(resp_matrix[ ,1:32], center = TRUE, scale = FALSE)
SEbase_matrix <- scale(resp_matrix[ ,33:64], center = TRUE, scale = FALSE)

#Below includes removal of weeks 35-37 (adjust grouping functions if we need to change this.)
#NEAus
NEAus_1 <- NEbase_matrix[ ,4:12] 
NEAus_2 <- NEbase_matrix[ ,13:17]
NEAus_3 <- NEbase_matrix[ ,18:32]

#NEAus
SEAus_1 <- SEbase_matrix[ ,4:16] 
SEAus_2 <- SEbase_matrix[ ,17:20] 
SEAus_3 <- SEbase_matrix[ ,21:32]

NEAus_mat <- list(NEAus_1, NEAus_2, NEAus_3)
SEAus_mat <- list(SEAus_1, SEAus_2, SEAus_3)

rm(NEAus_1, NEAus_2, NEAus_3, SEAus_1, SEAus_2, SEAus_3)

#full model
NEpreds_new <- NElag_3group(NE_laglist = NE_iodlag, j = 1:19)
NEresp_new <- NEresp_3group(NEAus_mat = NEAus_mat, j = 1:19)

SEpreds_new <- SElag_3group(SE_laglist = SE_iodlag, j = 1:19)
SEresp_new <- SEresp_3group(SEAus_mat = SEAus_mat, j = 1:19)

#partial model
NEpreds_newpart <- NElag_3group(NE_laglist = NE_iodlag, j = -c(19))
NEresp_newpart <- NEresp_3group(NEAus_mat = NEAus_mat, j = -c(19))

SEpreds_newpart <- SElag_3group(SE_laglist = SE_iodlag, j = -c(19))
SEresp_newpart <- SEresp_3group(SEAus_mat = SEAus_mat, j = -c(19))


```


```{r partial_LOO}
#leaving out a single year
NEpartial_preds <- list()
NEpartial_resp <- list()
SEpartial_preds <- list()
SEpartial_resp <- list()
for (j in 1:length(seasons)) {
  #NE Aus
  NEpartial_preds[[seasons[j]]] <- NElag_3group(NE_laglist = NE_iodlag, j = -c(j))
  NEpartial_resp[[seasons[j]]] <- NEresp_3group(NEAus_mat = NEAus_mat, j = -c(j))
  
  #SE Aus
  SEpartial_preds[[seasons[j]]] <- SElag_3group(SE_laglist = SE_iodlag, j = -c(j))
  SEpartial_resp[[seasons[j]]] <- SEresp_3group(SEAus_mat = SEAus_mat, j = -c(j))
}

#extracting a single year (validation data)
NEvalid_preds <- list()
NEvalid_resp <- list()
SEvalid_preds <- list()
SEvalid_resp <- list()
for (k in 1:length(seasons)) {
  #NE Aus
  NEvalid_preds[[seasons[k]]] <- NElag_3group(NE_laglist = NE_iodlag, j = c(k))
  NEvalid_resp[[seasons[k]]] <- NEresp_3group(NEAus_mat = NEAus_mat, j = c(k))
  
  #SE Aus
  SEvalid_preds[[seasons[k]]] <- SElag_3group(SE_laglist = SE_iodlag, j = c(k))
  SEvalid_resp[[seasons[k]]] <- SEresp_3group(SEAus_mat = SEAus_mat, j = c(k))
}

```


# Functions (RAMP)

```{r refit_functions}
refit_ramp <- function(test.ramp, X_1){
  
  main.terms <- test.ramp$mainInd
  main.terms <- colnames(X_1)[main.terms]
  
  interactions <- test.ramp$interInd
      if (!is.null(interactions)){
        for (i in 1:length(interactions)){
          
          this.term <- interactions[i]
          these.subterms <- as.integer(strsplit(this.term, "X")[[1]][2:3])
          these.subterms <- colnames(X_1)[these.subterms]
          
          if (these.subterms[1] != these.subterms[2]){
            this.term <- paste(these.subterms, collapse = ":")
          } else {
            this.term <- paste0("I(", these.subterms[1], "^2)")
          }
          
          interactions[i] <- this.term
        }
      }
  
  #refit with lm
  if (!is.null(interactions)){
    model.string <- paste( paste(main.terms, collapse = " + "),
                           paste(interactions, collapse = " + "),
                           sep = " + ")
  } else {
    model.string <- paste(main.terms, collapse = " + ")
  }
  
  model.string <- paste0("co ~ ", model.string)
  
  return(model.string)
}



terms_only <- function(test.ramp, X_1){
  main.terms <- test.ramp$mainInd
  main.terms <- colnames(X_1)[main.terms]
  
  interactions <- test.ramp$interInd
      if (!is.null(interactions)){
        for (i in 1:length(interactions)){
          
          this.term <- interactions[i]
          these.subterms <- as.integer(strsplit(this.term, "X")[[1]][2:3])
          these.subterms <- colnames(X_1)[these.subterms]
          
          if (these.subterms[1] != these.subterms[2]){
            this.term <- paste(these.subterms, collapse = ":")
          } else {
            this.term <- paste0("I(", these.subterms[1], "^2)")
          }
          
          interactions[i] <- this.term
        }
      }
  return(c(main.terms, interactions))
}

```



# Refit Terms

```{r NEAus_base}
#NE Aus Group 1
y_1 <- as.numeric(NEresp_new[[1]])

#with OLR
X_1 <- cbind(as.matrix(NEpreds_new[[1]][ ,1:312]))
#without OLR
#X_1 <- cbind(as.matrix(NEpreds_new[[1]][ ,1:260]))

negroup1 <- RAMP(X = X_1, y = y_1,
                             penalty = "LASSO",
                             tune = "BIC",
                             n.lambda = 500)

#terms only
NE1.terms <- terms_only(negroup1, X_1)
NE1.refit <- refit_ramp(negroup1, X_1)

#NE Aus Group 2
y_2 <- as.numeric(NEresp_new[[2]])

#with OLR
X_2 <- cbind(as.matrix(NEpreds_new[[2]][ ,1:312]))
#without OLR
#X_2 <- cbind(as.matrix(NEpreds_new[[2]][ ,1:260]))

negroup2 <- RAMP(X = X_2, y = y_2,
                             penalty = "LASSO",
                             tune = "BIC",
                             n.lambda = 500)

#terms only
NE2.terms <- terms_only(negroup2, X_2)
NE2.refit <- refit_ramp(negroup2, X_2) 
                        
#NE Aus Group 3
y_3 <- as.numeric(NEresp_new[[3]])

#with OLR
X_3 <- cbind(as.matrix(NEpreds_new[[3]][ ,1:312]))
#without OLR
#X_3 <- cbind(as.matrix(NEpreds_new[[3]][ ,1:260]))

negroup3 <- RAMP(X = X_3, y = y_3,
                             penalty = "LASSO",
                             tune = "BIC",
                             n.lambda = 500)

#terms only
NE3.terms <- terms_only(negroup3, X_3)                      
NE3.refit <- refit_ramp(negroup3, X_3)  

NEmodels <- list(negroup1, negroup2, negroup3)
NErefits <- list(NE1.refit, NE2.refit, NE3.refit)
              
```

```{r SEAus_base}
#SE Aus Group 1
y_1 <- as.numeric(SEresp_new[[1]])

#with OLR
X_1 <- cbind(as.matrix(SEpreds_new[[1]][ ,1:312]))
#without OLR
#X_1 <- cbind(as.matrix(SEpreds_new[[1]][ ,1:260]))

segroup1 <- RAMP(X = X_1, y = y_1,
                             penalty = "LASSO",
                             tune = "BIC",
                             n.lambda = 500)

#terms only
SE1.terms <- terms_only(segroup1, X_1)
SE1.refit <- refit_ramp(segroup1, X_1)

#SE Aus Group 2
y_2 <- as.numeric(SEresp_new[[2]])

#with OLR
X_2 <- cbind(as.matrix(SEpreds_new[[2]][ ,1:312]))
#without OLR
#X_2 <- cbind(as.matrix(SEpreds_new[[2]][ ,1:260]))

segroup2 <- RAMP(X = X_2, y = y_2,
                             penalty = "LASSO",
                             tune = "BIC",
                             n.lambda = 500)

#terms only
SE2.terms <- terms_only(segroup2, X_2)
SE2.refit <- refit_ramp(segroup2, X_2)

#SE Aus Group 3
y_3 <- as.numeric(SEresp_new[[3]])

#with OLR
X_3 <- cbind(as.matrix(SEpreds_new[[3]][ ,1:312]))
#without OLR
#X_3 <- cbind(as.matrix(SEpreds_new[[3]][ ,1:260]))

segroup3 <- RAMP(X = X_3, y = y_3,
                             penalty = "LASSO",
                             tune = "BIC",
                             n.lambda = 500)

#terms only
SE3.terms <- terms_only(segroup3, X_3)
SE3.refit <- refit_ramp(segroup3, X_3)

SEmodels <- list(segroup1, segroup2, segroup3)
SErefits <- list(SE1.refit, SE2.refit, SE3.refit)

```

## Refit - Base w/o OLR

```{r NEAus_noOLR}
#NE Aus Group 1
y_1 <- as.numeric(NEresp_new[[1]])

#without OLR
X_1 <- cbind(as.matrix(NEpreds_new[[1]][ ,1:260]))

negroup1.noOLR <- RAMP(X = X_1, y = y_1,
                             penalty = "LASSO",
                             tune = "BIC",
                             n.lambda = 500)

#terms only
NE1.terms.noOLR <- terms_only(negroup1.noOLR, X_1)
NE1.refit.noOLR <- refit_ramp(negroup1.noOLR, X_1)

#TODO: refit 
lm.data_1 <- as.data.frame(cbind(y_1, X_1))
names(lm.data_1)[1] <- "co"

NE1.lm.noOLR <- lm(formula(NE1.refit.noOLR), lm.data_1)
summary(NE1.lm.noOLR)

#NE Aus Group 2
y_2 <- as.numeric(NEresp_new[[2]])

#without OLR
X_2 <- cbind(as.matrix(NEpreds_new[[2]][ ,1:260]))

negroup2.noOLR <- RAMP(X = X_2, y = y_2,
                             penalty = "LASSO",
                             tune = "BIC",
                             n.lambda = 500)

#terms only
NE2.terms.noOLR <- terms_only(negroup2.noOLR, X_2)
NE2.refit.noOLR <- refit_ramp(negroup2.noOLR, X_2)

#refit 
lm.data_2 <- as.data.frame(cbind(y_2, X_2))
names(lm.data_2)[1] <- "co"

NE2.lm.noOLR <- lm(formula(NE2.refit.noOLR), lm.data_2)
summary(NE2.lm.noOLR)


#NE Aus Group 3
y_3 <- as.numeric(NEresp_new[[3]])

#without OLR
X_3 <- cbind(as.matrix(NEpreds_new[[3]][ ,1:260]))

negroup3.noOLR <- RAMP(X = X_3, y = y_3,
                             penalty = "LASSO",
                             tune = "BIC",
                             n.lambda = 500)

#terms only
NE3.terms.noOLR <- terms_only(negroup3.noOLR, X_3)
NE3.refit.noOLR <- refit_ramp(negroup3.noOLR, X_3)

#refit 
lm.data_3 <- as.data.frame(cbind(y_3, X_3))
names(lm.data_3)[1] <- "co"

NE3.lm.noOLR <- lm(formula(NE3.refit.noOLR), lm.data_3)
summary(NE3.lm.noOLR)

NErefit.noOLR <- list(NE1.refit.noOLR, NE2.refit.noOLR, NE3.refit.noOLR)


```

```{r SEAus_noOLR}
#SE Aus Group 1
y_1 <- as.numeric(SEresp_new[[1]])

#without OLR
X_1 <- cbind(as.matrix(SEpreds_new[[1]][ ,1:260]))

segroup1.noOLR <- RAMP(X = X_1, y = y_1,
                             penalty = "LASSO",
                             tune = "BIC",
                             n.lambda = 500)

#terms only
SE1.terms.noOLR <- terms_only(segroup1.noOLR, X_1)
SE1.refit.noOLR <- refit_ramp(segroup1.noOLR, X_1)

#TODO: refit 
lm.data_1 <- as.data.frame(cbind(y_1, X_1))
names(lm.data_1)[1] <- "co"

SE1.lm.noOLR <- lm(formula(SE1.refit.noOLR), lm.data_1)
summary(SE1.lm.noOLR)

#SE Aus Group 2
y_2 <- as.numeric(SEresp_new[[2]])

#without OLR
X_2 <- cbind(as.matrix(SEpreds_new[[2]][ ,1:260]))

segroup2.noOLR <- RAMP(X = X_2, y = y_2,
                             penalty = "LASSO",
                             tune = "BIC",
                             n.lambda = 500)

#terms only
SE2.terms.noOLR <- terms_only(segroup2.noOLR, X_2)
SE2.refit.noOLR <- refit_ramp(segroup2.noOLR, X_2)

#refit 
lm.data_2 <- as.data.frame(cbind(y_2, X_2))
names(lm.data_2)[1] <- "co"

SE2.lm.noOLR <- lm(formula(SE2.refit.noOLR), lm.data_2)
summary(SE2.lm.noOLR)


#SE Aus Group 3
y_3 <- as.numeric(SEresp_new[[3]])

#without OLR
X_3 <- cbind(as.matrix(SEpreds_new[[3]][ ,1:260]))

segroup3.noOLR <- RAMP(X = X_3, y = y_3,
                             penalty = "LASSO",
                             tune = "BIC",
                             n.lambda = 500)

#terms only
SE3.terms.noOLR <- terms_only(segroup3.noOLR, X_3)
SE3.refit.noOLR <- refit_ramp(segroup3.noOLR, X_3)

#refit 
lm.data_3 <- as.data.frame(cbind(y_3, X_3))
names(lm.data_3)[1] <- "co"

SE3.lm.noOLR <- lm(formula(SE3.refit.noOLR), lm.data_3)
summary(SE3.lm.noOLR)

SErefit.noOLR <- list(SE1.refit.noOLR, SE2.refit.noOLR, SE3.refit.noOLR)


```


# Refit w/ eBIC

```{r NEaus_ebic}
#gamma
gamma_seq <- seq(0, 1, length.out = 12)


#NE Aus Group 1
y_1 <- as.numeric(NEresp_new[[1]])
#with OLR
X_1 <- cbind(as.matrix(NEpreds_new[[1]][ ,1:312]))

NEAus1.eBIC <- list()
for (j in 2:length(gamma_seq)) {
  negroup1.temp <- RAMP(X = X_1, y = y_1,
                             penalty = "LASSO",
                             tune = "EBIC",
                             ebic.gamma = gamma_seq[j],
                             n.lambda = 500)
  
  #terms only
  NE1.refit.temp <- refit_ramp(negroup1.temp, X_1)
  
    #refit 
  lm.data_1 <- as.data.frame(cbind(y_1, X_1))
  names(lm.data_1)[1] <- "co"
  
  NE1.lm.eBIC <- lm(formula(NE1.refit.temp), lm.data_1)
  #summary(NE1.lm.eBIC)
  NEAus1.eBIC[[paste0("Gamma:", gamma_seq[[j]])]] <- NE1.lm.eBIC
}


#NE Aus Group 2
y_2 <- as.numeric(NEresp_new[[2]])
#with OLR
X_2 <- cbind(as.matrix(NEpreds_new[[2]][ ,1:312]))

NEAus2.eBIC <- list()
for (j in 2:length(gamma_seq)) {
  negroup2.temp <- RAMP(X = X_2, y = y_2,
                             penalty = "LASSO",
                             tune = "EBIC",
                             ebic.gamma = gamma_seq[j],
                             n.lambda = 500)
  
  #terms only
  NE2.refit.temp <- refit_ramp(negroup2.temp, X_2)
  
  #refit 
  lm.data_2 <- as.data.frame(cbind(y_2, X_2))
  names(lm.data_2)[1] <- "co"
  
  NE2.lm.eBIC <- lm(formula(NE2.refit.temp), lm.data_2)
  #summary(NE1.lm.eBIC)
  NEAus2.eBIC[[paste0("Gamma:", gamma_seq[[j]])]] <- NE2.lm.eBIC
}


#NE Aus Group 3
y_3 <- as.numeric(NEresp_new[[3]])
#with OLR
X_3 <- cbind(as.matrix(NEpreds_new[[3]][ ,1:312]))

NEAus3.eBIC <- list()
for (j in 2:length(gamma_seq)) {
  negroup3.temp <- RAMP(X = X_3, y = y_3,
                             penalty = "LASSO",
                             tune = "EBIC",
                             ebic.gamma = gamma_seq[j],
                             n.lambda = 500)
  
  #terms only
  NE3.refit.temp <- refit_ramp(negroup3.temp, X_3)
  
  #refit 
  lm.data_3 <- as.data.frame(cbind(y_3, X_3))
  names(lm.data_3)[1] <- "co"
  
  NE3.lm.eBIC <- lm(formula(NE3.refit.temp), lm.data_3)
  #summary(NE1.lm.eBIC)
  NEAus3.eBIC[[paste0("Gamma:", gamma_seq[[j]])]] <- NE3.lm.eBIC
}



```

```{r SEaus_ebic}


#NE Aus Group 1
y_1 <- as.numeric(SEresp_new[[1]])
#with OLR
X_1 <- cbind(as.matrix(SEpreds_new[[1]][ ,1:312]))

SEAus1.eBIC <- list()
for (j in 2:length(gamma_seq)) {
  segroup1.temp <- RAMP(X = X_1, y = y_1,
                             penalty = "LASSO",
                             tune = "EBIC",
                             ebic.gamma = gamma_seq[j],
                             n.lambda = 500)
  
  #terms only
  SE1.refit.temp <- refit_ramp(segroup1.temp, X_1)
  
    #refit 
  lm.data_1 <- as.data.frame(cbind(y_1, X_1))
  names(lm.data_1)[1] <- "co"
  
  SE1.lm.eBIC <- lm(formula(SE1.refit.temp), lm.data_1)
  #summary(NE1.lm.eBIC)
  SEAus1.eBIC[[paste0("Gamma:", gamma_seq[[j]])]] <- SE1.lm.eBIC
}


#NE Aus Group 2
y_2 <- as.numeric(SEresp_new[[2]])
#with OLR
X_2 <- cbind(as.matrix(SEpreds_new[[2]][ ,1:312]))

SEAus2.eBIC <- list()
for (j in 2:length(gamma_seq)) {
  segroup2.temp <- RAMP(X = X_2, y = y_2,
                             penalty = "LASSO",
                             tune = "EBIC",
                             ebic.gamma = gamma_seq[j],
                             n.lambda = 500)
  
  #terms only
  SE2.refit.temp <- refit_ramp(segroup2.temp, X_2)
  
  #refit 
  lm.data_2 <- as.data.frame(cbind(y_2, X_2))
  names(lm.data_2)[1] <- "co"
  
  SE2.lm.eBIC <- lm(formula(SE2.refit.temp), lm.data_2)
  #summary(NE1.lm.eBIC)
  SEAus2.eBIC[[paste0("Gamma:", gamma_seq[[j]])]] <- SE2.lm.eBIC
}


#NE Aus Group 3
y_3 <- as.numeric(SEresp_new[[3]])
#with OLR
X_3 <- cbind(as.matrix(SEpreds_new[[3]][ ,1:312]))

SEAus3.eBIC <- list()
for (j in 2:length(gamma_seq)) {
  segroup3.temp <- RAMP(X = X_3, y = y_3,
                             penalty = "LASSO",
                             tune = "EBIC",
                             ebic.gamma = gamma_seq[j],
                             n.lambda = 500)
  
  #terms only
  SE3.refit.temp <- refit_ramp(segroup3.temp, X_3)
  
  #refit 
  lm.data_3 <- as.data.frame(cbind(y_3, X_3))
  names(lm.data_3)[1] <- "co"
  
  SE3.lm.eBIC <- lm(formula(SE3.refit.temp), lm.data_3)
  #summary(NE1.lm.eBIC)
  SEAus3.eBIC[[paste0("Gamma:", gamma_seq[[j]])]] <- SE3.lm.eBIC
}


```


## Refit - LOO

```{r NEAus_refit}

#NE Aus 
NE.term.list <- NULL
NE.model.list <- NULL
NE.refit.list <- NULL #refit with base model
for (j in 1:length(seasons)) {
  temp.resp <- NEpartial_resp[[j]]
  temp.preds <- NEpartial_preds[[j]]
  
  temp.list <- NULL
  temp.model <- NULL
  temp.refit <- NULL
  for (k in 1:length(temp.preds)) {
    temp.y <- as.numeric(temp.resp[[k]])
    #with OLR
    temp.X <- cbind(as.matrix(temp.preds[[k]][ ,1:312]))
    
    temp.fit <- RAMP(X = temp.X, y = temp.y,
                             penalty = "LASSO",
                             tune = "BIC",
                             n.lambda = 500)
    #terms only
    temp.list[[k]] <- terms_only(temp.fit, temp.X)
    temp.model[[k]] <- refit_ramp(temp.fit, temp.X)
    temp.refit[[k]] <- refit_ramp(NEmodels[[k]], temp.X)
  }
  NE.term.list[[seasons[j]]] <- temp.list
  NE.model.list[[seasons[j]]] <- temp.model
  NE.refit.list[[seasons[j]]] <- temp.refit
}

```

```{r sEAus_refit}

#sE Aus 
SE.term.list <- NULL
SE.model.list <- NULL
SE.refit.list <- NULL #refit with base model
for (j in 1:length(seasons)) {
  temp.resp <- SEpartial_resp[[j]]
  temp.preds <- SEpartial_preds[[j]]
  
  temp.list <- NULL
  temp.model <- NULL
  temp.refit <- NULL
  for (k in 1:length(temp.preds)) {
    temp.y <- as.numeric(temp.resp[[k]])
    #with OLR
    temp.X <- cbind(as.matrix(temp.preds[[k]][ ,1:312]))
    
    temp.fit <- RAMP(X = temp.X, y = temp.y,
                             penalty = "LASSO",
                             tune = "BIC",
                             n.lambda = 500)
    #terms only
    temp.list[[k]] <- terms_only(temp.fit, temp.X)
    temp.model[[k]] <- refit_ramp(temp.fit, temp.X)
    temp.refit[[k]] <- refit_ramp(SEmodels[[k]], temp.X)
  }
  SE.term.list[[seasons[j]]] <- temp.list
  SE.model.list[[seasons[j]]] <- temp.model
  SE.refit.list[[seasons[j]]] <- temp.refit
}

```

```{r save}
setwd("~/CO_AUS/Aus_CO-main/Interactions_New")
save(SE.term.list, SE.model.list, SE.refit.list, 
     NE.term.list, NE.model.list, NE.refit.list, file = "model_refits.rda")
```


## Comparison to Base

```{r NeAus_compare}
#NE Aus Group 1

#get frequency of each term 
baseNE1 <- NE1.terms
#refitNE1 <- NE.term.list[[2]][[1]]

refitNE1 <- unlist(lapply(NE.term.list, function(x) x[[1]]))
sapply(baseNE1, function(x) sum(x == refitNE1))
#unique(refitNE1)
NErefit1.unique <- table(refitNE1)
NErefit1.unique <- NErefit1.unique[!names(NErefit1.unique) %in% baseNE1]
sort(NErefit1.unique, decreasing = TRUE)


#group 2
baseNE2 <- NE2.terms
#refitNE2 <- NE.term.list[[2]][[2]]

refitNE2 <- unlist(lapply(NE.term.list, function(x) x[[2]]))
sapply(baseNE2, function(x) sum(x == refitNE2))
#unique(refitNE2)
NErefit2.unique <- table(refitNE2)
NErefit2.unique <- NErefit2.unique[!names(NErefit2.unique) %in% baseNE2]
sort(NErefit2.unique, decreasing = TRUE)


#group 3
baseNE3 <- NE3.terms
#refitNE3 <- NE.term.list[[2]][[3]]

refitNE3 <- unlist(lapply(NE.term.list, function(x) x[[3]]))
sapply(baseNE3, function(x) sum(x == refitNE3))
#unique(refitNE3)
NErefit3.unique <- table(refitNE3)
NErefit3.unique <- NErefit3.unique[!names(NErefit3.unique) %in% baseNE3]
sort(NErefit3.unique, decreasing = TRUE)

```

```{r seAus_compare}
#sE Aus Group 1

#get frequency of each term 
baseSE1 <- SE1.terms
#refitSE1 <- SE.term.list[[2]][[1]]

refitSE1 <- unlist(lapply(SE.term.list, function(x) x[[1]]))
sapply(baseSE1, function(x) sum(x == refitSE1))
#unique(refitSE1)
SErefit1.unique <- table(refitSE1)
SErefit1.unique <- SErefit1.unique[!names(SErefit1.unique) %in% baseSE1]
sort(SErefit1.unique, decreasing = TRUE)


#group 2
baseSE2 <- SE2.terms
#refitSE2 <- SE.term.list[[2]][[2]]

refitSE2 <- unlist(lapply(SE.term.list, function(x) x[[2]]))
sapply(baseSE2, function(x) sum(x == refitSE2))
#unique(refitSE2)
SErefit2.unique <- table(refitSE2)
SErefit2.unique <- SErefit2.unique[!names(SErefit2.unique) %in% baseSE2]
sort(SErefit2.unique, decreasing = TRUE)

#group 3
baseSE3 <- SE3.terms
#refitSE3 <- SE.term.list[[2]][[3]]

refitSE3 <- unlist(lapply(SE.term.list, function(x) x[[3]]))
sapply(baseSE3, function(x) sum(x == refitSE3))
#unique(refitSE3)
SErefit3.unique <- table(refitSE3)
SErefit3.unique <- SErefit3.unique[!names(SErefit3.unique) %in% baseSE3]
sort(SErefit3.unique, decreasing = TRUE)

```


# Model Validation

RMSE, ....

```{r test_model_fits}
#NE Aus Group 1
y_1 <- as.numeric(NEresp_new[[1]])

#with OLR
X_1 <- cbind(as.matrix(NEpreds_new[[1]][ ,1:312]))


lm.data_1 <- as.data.frame(cbind(y_1, X_1))
names(lm.data_1)[1] <- "co"

NE1.lm <- lm(formula(NE1.refit), lm.data_1)
summary(NE1.lm)


NEvalid_preds[[1]][[1]]
y.true <- NEvalid_resp[[1]][[1]]

y.pred <- predict(NE1.lm, NEvalid_preds[[1]][[1]], se.fit = TRUE)

y.pred$fit
y.pred$se.fit

CPRS(list(mean = y.pred$fit, sd = y.pred$se.fit), y.true)
intscore(list(mean = y.pred$fit, sd = y.pred$se.fit), y.true)

y.true
y.pred
y.true - y.pred

#without OLR
X_1 <- cbind(as.matrix(NEpreds_new[[1]][ ,1:260]))

lm.data_1 <- as.data.frame(cbind(y_1, X_1))
names(lm.data_1)[1] <- "co"

NE1.lm.noOLR <- lm(formula(NE1.refit.noOLR), lm.data_1)
summary(NE1.lm.noOLR)

test.X <- NEvalid_preds[[1]][[1]][ ,1:260]
y.pred.noOLR <- predict(NE1.lm.noOLR, test.X)

y.true
y.pred.noOLR
y.true - y.pred.noOLR
```

```{r base_NElm}
#NE Aus Group 1
y_1 <- as.numeric(NEresp_new[[1]])

#with OLR
X_1 <- cbind(as.matrix(NEpreds_new[[1]][ ,1:312]))

lm.data_1 <- as.data.frame(cbind(y_1, X_1))
names(lm.data_1)[1] <- "co"

NE1.lm <- lm(formula(NE1.refit), lm.data_1)
summary(NE1.lm)

#NE Aus Group 2
y_2 <- as.numeric(NEresp_new[[2]])

#with OLR
X_2 <- cbind(as.matrix(NEpreds_new[[2]][ ,1:312]))

lm.data_2 <- as.data.frame(cbind(y_2, X_2))
names(lm.data_2)[1] <- "co"

NE2.lm <- lm(formula(NE2.refit), lm.data_2)
summary(NE2.lm)

#without OLR
X_2 <- cbind(as.matrix(NEpreds_new[[2]][ ,1:260]))

lm.data_2 <- as.data.frame(cbind(y_2, X_2))
names(lm.data_2)[1] <- "co"

NE2.lm.noOLR <- lm(formula(NE2.refit.noOLR), lm.data_2)
summary(NE2.lm.noOLR)


#NE Aus Group 3
y_3 <- as.numeric(NEresp_new[[3]])

#with OLR
X_3 <- cbind(as.matrix(NEpreds_new[[3]][ ,1:312]))

lm.data_3 <- as.data.frame(cbind(y_3, X_3))
names(lm.data_3)[1] <- "co"

NE3.lm <- lm(formula(NE3.refit), lm.data_3)
summary(NE3.lm)


NE.lms <- list(NE1.lm, NE2.lm, NE3.lm)

```

```{r base_SElm}
#SE Aus Group 1
y_1 <- as.numeric(SEresp_new[[1]])

#with OLR
X_1 <- cbind(as.matrix(SEpreds_new[[1]][ ,1:312]))

lm.data_1 <- as.data.frame(cbind(y_1, X_1))
names(lm.data_1)[1] <- "co"

SE1.lm <- lm(formula(SE1.refit), lm.data_1)
summary(SE1.lm)

#SE Aus Group 2
y_2 <- as.numeric(SEresp_new[[2]])

#with OLR
X_2 <- cbind(as.matrix(SEpreds_new[[2]][ ,1:312]))

lm.data_2 <- as.data.frame(cbind(y_2, X_2))
names(lm.data_2)[1] <- "co"

SE2.lm <- lm(formula(SE2.refit), lm.data_2)
summary(SE2.lm)

#SE Aus Group 3
y_3 <- as.numeric(SEresp_new[[3]])

#with OLR
X_3 <- cbind(as.matrix(SEpreds_new[[3]][ ,1:312]))

lm.data_3 <- as.data.frame(cbind(y_3, X_3))
names(lm.data_3)[1] <- "co"

SE3.lm <- lm(formula(SE3.refit), lm.data_3)
summary(SE3.lm)


SE.lms <- list(SE1.lm, SE2.lm, SE3.lm)
```


## LOO Validation

```{r model_fits_validation}

#lists
## full model fit: NErefits
## LOO model w/ constant terms: NE.refit.list
## LOO model w/ varying terms: NE.model.list

#rmse 
#TODO: functionalize this so I can repeat for other setups
NE.rmse <- NULL
NE.cprs <- NULL
NE.ints <- NULL
for (i in 1:length(seasons)) {
  fit.resp <- NEpartial_resp[[i]]
  fit.preds <- NEpartial_preds[[i]]
  
  valid.resp <- NEvalid_resp[[i]]
  valid.preds <- NEvalid_preds[[i]]
  
  #get terms/model for year/season 
  year.constant <- NE.refit.list[[i]]
  year.varying <- NE.model.list[[i]]
  
  #add in lists/matrices
  NErmse.yearly <- matrix(NA, ncol = 3)
  colnames(NErmse.yearly) <- c("base.pred", "const.pred", "vary.pred")
  NEcprs.yearly <- matrix(NA, ncol = 3)
  colnames(NEcprs.yearly) <- c("base.pred", "const.pred", "vary.pred")
  NEis.yearly <- matrix(NA, ncol = 3)
  colnames(NEis.yearly) <- c("base.pred", "const.pred", "vary.pred")
  #groups/clusters below
  for (j in 1:3) {
    #lm fit data setup
    y.fit <- as.numeric(fit.resp[[j]])
    #with OLR
    X.fit <- cbind(as.matrix(fit.preds[[j]][ ,1:312]))
    
    lm.data.fit <- as.data.frame(cbind(y.fit, X.fit))
    names(lm.data.fit)[1] <- "co"

    #fit lm models (w/o year/season)
    temp.lm.constant <- lm(formula(year.constant[[j]]), lm.data.fit)
    temp.lm.varying <- lm(formula(year.varying[[j]]), lm.data.fit)
    
    #predict/rmse
    X.valid <- valid.preds[[j]][ ,1:312]
    y.valid <- valid.resp[[j]]
    
    #prediction
    pred.base <- predict(NE.lms[[j]], X.valid, se.fit = TRUE)
    pred.const <- predict(temp.lm.constant, X.valid, se.fit = TRUE)
    pred.vary <- predict(temp.lm.varying, X.valid, se.fit = TRUE)
    
    #predict( ,se.fit = TRUE)
    y.pred.base <- pred.base$fit 
    y.pred.const <- pred.const$fit
    y.pred.vary <- pred.vary$fit
    
    #rmse test
    rmse.base <-  rmse(y.valid, y.pred.base)
    rmse.const <- rmse(y.valid, y.pred.const)
    rmse.vary <- rmse(y.valid, y.pred.vary)
    
    #cprs
    cprs.base <- mean(CPRS(list(mean = pred.base$fit, sd = pred.base$se.fit), y.valid))
    cprs.const <- mean(CPRS(list(mean = pred.const$fit, sd = pred.const$se.fit), y.valid))
    cprs.vary <- mean(CPRS(list(mean = pred.vary$fit, sd = pred.vary$se.fit), y.valid))
    
    #IS95
    is.base <- mean(intscore(list(mean = pred.base$fit, sd = pred.base$se.fit), y.valid))
    is.const <- mean(intscore(list(mean = pred.const$fit, sd = pred.const$se.fit), y.valid))
    is.vary <- mean(intscore(list(mean = pred.vary$fit, sd = pred.vary$se.fit), y.valid))
    
    #assign data
    RMSE.temp.mat <- cbind(rmse.base, rmse.const, rmse.vary)
    NErmse.yearly <- rbind(NErmse.yearly, RMSE.temp.mat) 
    CPRS.temp.mat <- cbind(cprs.base, cprs.const, cprs.vary)
    NEcprs.yearly <- rbind(NEcprs.yearly, CPRS.temp.mat)
    IS.temp.mat <- cbind(is.base, is.const, is.vary)
    NEis.yearly <- rbind(NEis.yearly, IS.temp.mat)
  }
  #NErmse.yearly <- as.data.frame(NErmse.yearly[-1, ])
  NE.rmse[[seasons[i]]] <- as.data.frame(NErmse.yearly[-1, ])
  NE.cprs[[seasons[i]]] <- as.data.frame(NEcprs.yearly[-1, ])
  NE.ints[[seasons[i]]] <- as.data.frame(NEis.yearly[-1, ])
}


#TODO: add more validation
#rmse 
SE.rmse <- NULL
SE.cprs <- NULL
SE.ints <- NULL
for (i in 1:length(seasons)) {
  fit.resp <- SEpartial_resp[[i]]
  fit.preds <- SEpartial_preds[[i]]
  
  valid.resp <- SEvalid_resp[[i]]
  valid.preds <- SEvalid_preds[[i]]
  
  #get terms/model for year/season 
  year.constant <- SE.refit.list[[i]]
  year.varying <- SE.model.list[[i]]
  
  #add in lists/matrices
  SErmse.yearly <- matrix(NA, ncol = 3)
  colnames(SErmse.yearly) <- c("base.pred", "const.pred", "vary.pred")
  SEcprs.yearly <- matrix(NA, ncol = 3)
  colnames(SEcprs.yearly) <- c("base.pred", "const.pred", "vary.pred")
  SEis.yearly <- matrix(NA, ncol = 3)
  colnames(SEis.yearly) <- c("base.pred", "const.pred", "vary.pred")
  #groups/clusters below
  for (j in 1:3) {
    #lm fit data setup
    y.fit <- as.numeric(fit.resp[[j]])
    #with OLR
    X.fit <- cbind(as.matrix(fit.preds[[j]][ ,1:312]))
    
    lm.data.fit <- as.data.frame(cbind(y.fit, X.fit))
    names(lm.data.fit)[1] <- "co"

    #fit lm models (w/o year/season)
    temp.lm.constant <- lm(formula(year.constant[[j]]), lm.data.fit)
    temp.lm.varying <- lm(formula(year.varying[[j]]), lm.data.fit)
    
    #predict/rmse
    X.valid <- valid.preds[[j]][ ,1:312]
    y.valid <- valid.resp[[j]]
    
    #prediction
    pred.base <- predict(SE.lms[[j]], X.valid, se.fit = TRUE)
    pred.const <- predict(temp.lm.constant, X.valid, se.fit = TRUE)
    pred.vary <- predict(temp.lm.varying, X.valid, se.fit = TRUE)
    
    y.pred.base <- pred.base$fit 
    y.pred.const <- pred.const$fit
    y.pred.vary <- pred.vary$fit
    
    #rmse test
    rmse.base <-  rmse(y.valid, y.pred.base)
    rmse.const <- rmse(y.valid, y.pred.const)
    rmse.vary <- rmse(y.valid, y.pred.vary)
    
    #cprs
    cprs.base <- mean(CPRS(list(mean = pred.base$fit, sd = pred.base$se.fit), y.valid))
    cprs.const <- mean(CPRS(list(mean = pred.const$fit, sd = pred.const$se.fit), y.valid))
    cprs.vary <- mean(CPRS(list(mean = pred.vary$fit, sd = pred.vary$se.fit), y.valid))
    
    #IS95
    is.base <- mean(intscore(list(mean = pred.base$fit, sd = pred.base$se.fit), y.valid))
    is.const <- mean(intscore(list(mean = pred.const$fit, sd = pred.const$se.fit), y.valid))
    is.vary <- mean(intscore(list(mean = pred.vary$fit, sd = pred.vary$se.fit), y.valid))
    
    temp.mat <- cbind(rmse.base, rmse.const, rmse.vary)
    SErmse.yearly <- rbind(SErmse.yearly, temp.mat) 
    CPRS.temp.mat <- cbind(cprs.base, cprs.const, cprs.vary)
    SEcprs.yearly <- rbind(SEcprs.yearly, CPRS.temp.mat)
    IS.temp.mat <- cbind(is.base, is.const, is.vary)
    SEis.yearly <- rbind(SEis.yearly, IS.temp.mat)
    
  }
  #NErmse.yearly <- as.data.frame(NErmse.yearly[-1, ])
  SE.rmse[[seasons[i]]] <- as.data.frame(SErmse.yearly[-1, ])
  SE.cprs[[seasons[i]]] <- as.data.frame(SEcprs.yearly[-1, ])
  SE.ints[[seasons[i]]] <- as.data.frame(SEis.yearly[-1, ])
}

```

## K-Fold

```{r kfold}
k <- 10

#NE aus
NE.kcv <- NULL
for(j in 1:3){ 
  temp.pred <- NEpreds_new[[j]]
  temp.resp <- NEresp_new[[j]]
  
  
  nrow(temp.pred)
  length(temp.resp)
  
  n <- nrow(temp.pred)
  set.seed(156)
  folds <- sample(rep(1:k, length.out = n))
  # Store errors
  mse <- numeric(k)
  for (i in 1:k) {
    # Split into training and test sets
    test.id <- which(folds == i)
    train.preds <- temp.pred[-test.id, ]
    train.resp <- temp.resp[-test.id]
    test.preds <- temp.pred[test.id, ]
    test.resp <- temp.resp[test.id]
    
    # Fit model
    train.data.fit <- as.data.frame(cbind(train.resp, train.preds))
    names(train.data.fit)[1] <- "co"
  
    temp.model <- lm(formula(NErefits[[j]]), train.data.fit)
    
    # Predict
    preds <- predict(temp.model, newdata = test.preds)
    
    # Compute Mean Squared Error
    mse[i] <- mean((test.resp - preds)^2)
  }
  NE.kcv[[j]] <- mean(mse)
}




#SE aus
SE.kcv <- NULL
for(j in 1:3){ 
  temp.pred <- SEpreds_new[[j]]
  temp.resp <- SEresp_new[[j]]
  
  
  nrow(temp.pred)
  length(temp.resp)
  
  n <- nrow(temp.pred)
  set.seed(157)
  folds <- sample(rep(1:k, length.out = n))
  # Store errors
  mse <- numeric(k)
  for (i in 1:k) {
    # Split into training and test sets
    test.id <- which(folds == i)
    train.preds <- temp.pred[-test.id, ]
    train.resp <- temp.resp[-test.id]
    test.preds <- temp.pred[test.id, ]
    test.resp <- temp.resp[test.id]
    
    # Fit model
    train.data.fit <- as.data.frame(cbind(train.resp, train.preds))
    names(train.data.fit)[1] <- "co"
  
    temp.model <- lm(formula(SErefits[[j]]), train.data.fit)
    
    # Predict
    preds <- predict(temp.model, newdata = test.preds)
    
    # Compute Mean Squared Error
    mse[i] <- mean((test.resp - preds)^2)
  }
  SE.kcv[[j]] <- mean(mse)
}

NE.kcv
SE.kcv
```

```{r kfold_noOLR}
k <- 10

#NE aus
NE.kcv.noOLR <- NULL
for(j in 1:3){ 
  temp.pred <- NEpreds_new[[j]][ ,1:260]
  temp.resp <- NEresp_new[[j]]
  
  
  nrow(temp.pred)
  length(temp.resp)
  
  n <- nrow(temp.pred)
  set.seed(156)
  folds <- sample(rep(1:k, length.out = n))
  # Store errors
  mse <- numeric(k)
  for (i in 1:k) {
    # Split into training and test sets
    test.id <- which(folds == i)
    train.preds <- temp.pred[-test.id, ]
    train.resp <- temp.resp[-test.id]
    test.preds <- temp.pred[test.id, ]
    test.resp <- temp.resp[test.id]
    
    # Fit model
    train.data.fit <- as.data.frame(cbind(train.resp, train.preds))
    names(train.data.fit)[1] <- "co"
  
    temp.model <- lm(formula(NErefit.noOLR[[j]]), train.data.fit)
    
    # Predict
    preds <- predict(temp.model, newdata = test.preds)
    
    # Compute Mean Squared Error
    mse[i] <- mean((test.resp - preds)^2)
  }
  NE.kcv.noOLR[[j]] <- mean(mse)
}




#SE aus
SE.kcv.noOLR <- NULL
for(j in 1:3){ 
  temp.pred <- SEpreds_new[[j]][ ,1:260]
  temp.resp <- SEresp_new[[j]]
  
  
  nrow(temp.pred)
  length(temp.resp)
  
  n <- nrow(temp.pred)
  set.seed(157)
  folds <- sample(rep(1:k, length.out = n))
  # Store errors
  mse <- numeric(k)
  for (i in 1:k) {
    # Split into training and test sets
    test.id <- which(folds == i)
    train.preds <- temp.pred[-test.id, ]
    train.resp <- temp.resp[-test.id]
    test.preds <- temp.pred[test.id, ]
    test.resp <- temp.resp[test.id]
    
    # Fit model
    train.data.fit <- as.data.frame(cbind(train.resp, train.preds))
    names(train.data.fit)[1] <- "co"
  
    temp.model <- lm(formula(SErefit.noOLR[[j]]), train.data.fit)
    
    # Predict
    preds <- predict(temp.model, newdata = test.preds)
    
    # Compute Mean Squared Error
    mse[i] <- mean((test.resp - preds)^2)
  }
  SE.kcv.noOLR[[j]] <- mean(mse)
}

NE.kcv.noOLR
SE.kcv.noOLR

```


```{r validation_extract}
#rmse
NEbase.rmse <- unlist(lapply(NE.rmse, function(x) x[[1]]))
NEconst.rmse <- unlist(lapply(NE.rmse, function(x) x[[2]]))
NEvary.rmse <- unlist(lapply(NE.rmse, function(x) x[[3]]))

SEbase.rmse <- unlist(lapply(SE.rmse, function(x) x[[1]]))
SEconst.rmse <- unlist(lapply(SE.rmse, function(x) x[[2]]))
SEvary.rmse <- unlist(lapply(SE.rmse, function(x) x[[3]]))

#cprs
NEbase.cprs <- unlist(lapply(NE.cprs, function(x) x[[1]]))
NEconst.cprs <- unlist(lapply(NE.cprs, function(x) x[[2]]))
NEvary.cprs <- unlist(lapply(NE.cprs, function(x) x[[3]]))

SEbase.cprs <- unlist(lapply(SE.cprs, function(x) x[[1]]))
SEconst.cprs <- unlist(lapply(SE.cprs, function(x) x[[2]]))
SEvary.cprs <- unlist(lapply(SE.cprs, function(x) x[[3]]))

#int score
NEbase.int <- unlist(lapply(NE.ints, function(x) x[[1]]))
NEconst.int <- unlist(lapply(NE.ints, function(x) x[[2]]))
NEvary.int <- unlist(lapply(NE.ints, function(x) x[[3]]))

SEbase.int <- unlist(lapply(SE.ints, function(x) x[[1]]))
SEconst.int <- unlist(lapply(SE.ints, function(x) x[[2]]))
SEvary.int <- unlist(lapply(SE.ints, function(x) x[[3]]))


```


```{r extract_byGroup}


NEgroup1.rmse <- unlist(lapply(NE.rmse, function(x) x[[2]][1]))
NEgroup2.rmse <- unlist(lapply(NE.rmse, function(x) x[[2]][2]))
NEgroup3.rmse <- unlist(lapply(NE.rmse, function(x) x[[2]][3]))

SEgroup1.rmse <- unlist(lapply(SE.rmse, function(x) x[[2]][1]))
SEgroup2.rmse <- unlist(lapply(SE.rmse, function(x) x[[2]][2]))
SEgroup3.rmse <- unlist(lapply(SE.rmse, function(x) x[[2]][3]))


```


# ANOVAs

Use to show the effect of including or excluding OLR

```{r }
anova(NE1.lm.noOLR, NE1.lm )
anova(NE2.lm.noOLR, NE2.lm )
anova(NE3.lm.noOLR, NE3.lm )



anova(SE1.lm.noOLR, SE1.lm )
anova(SE2.lm.noOLR, SE2.lm )
anova(SE3.lm.noOLR, SE3.lm )
```




# Figures


## RMSE Plots

```{r}
#get yearly lines
year.div <- seq(0.5, 57.5, by = 3)
year.mid <- seq(2, 56, by = 3)

NErmse.range <- range(NE.rmse)
SErmse.range <- range(SE.rmse)

colors.group <- rep(c("firebrick", "forestgreen", "royalblue3"), 19)

setwd("~/CO_AUS/Aus_CO-main/Interactions_New/Figures")


png(filename = "NErmse.png", width = 3600, height = 1500, res = 300)
par(mar = c(5, 5, 3, 7))
plot(1:57, NEbase.rmse, pch = 16, col = colors.group, 
     ylab = "RMSE", ylim = c(0, max(NErmse.range)), xlab = "Year", axes = FALSE)
box()
axis(2)
axis(1, at = year.mid, labels = c(season_years[1:19]), tick = FALSE )
points(1:57, NEconst.rmse, pch = 15, col = colors.group)
points(1:57, NEvary.rmse, pch = 17, col = alpha(colors.group, 0.75) )
abline(v= year.div, lty = 2)
title("NE Aus: RMSE", adj = 0)
legend("topright", inset = c(-0.12, 0), xpd = TRUE,
       legend = c("Group 1", "Group 2", "Group 3"), col = colors.group, pch = 16 )
dev.off()


png(filename = "SErmse.png", width = 3600, height = 1500, res = 300)
par(mar = c(5, 5, 3, 7))
plot(1:57, SEbase.rmse, pch = 16, col = colors.group,
     ylab = "RMSE", ylim = c(0, max(SErmse.range)), xlab = "Year", axes = FALSE)
box()
axis(2)
axis(1, at = year.mid, labels = c(season_years[1:19]), tick = FALSE )
points(1:57, SEconst.rmse, pch = 15, col = colors.group,)
points(1:57, SEvary.rmse, pch = 17, col = alpha(colors.group, 0.75),)
abline(v= year.div, lty = 2)
title("SE Aus: RMSE", adj = 0)
legend("topright", inset = c(-0.12, 0), xpd = TRUE,
       legend = c("Group 1", "Group 2", "Group 3"), col = colors.group, pch = 16 )
dev.off()

```


## CRPS Plots

```{r}
NEcprs.range <- range(NE.cprs)
SEcprs.range <- range(SE.cprs)

plot(1:57, NEconst.cprs, pch = 16,
     ylim = NEcprs.range)
plot(1:57, SEconst.cprs, pch = 16,
     ylim = SEcprs.range)
```

```{r boxplots}
#TODO: finalize these plots into a single plot (as before)
boxplot(NEgroup1.rmse, NEgroup2.rmse, NEgroup3.rmse)
boxplot(SEgroup1.rmse, SEgroup2.rmse, SEgroup3.rmse)
```



## Interval Score Plots

```{r}
NEints.range <- range(NE.ints)
SEints.range <- range(SE.ints)

plot(1:57, NEconst.int, pch = 16,
     ylim = NEints.range)
plot(1:57, SEconst.int, pch = 16,
     ylim = SEints.range)
```



## Model Fits

```{r base_fits}
#NE base fits
plot(NE.lms[[1]])
plot(NE.lms[[2]])
plot(NE.lms[[3]])

#SE base fits
plot(SE.lms[[1]])
plot(SE.lms[[2]])
plot(SE.lms[[3]])
```



## Constant Structure


# Test Code

```{r}
lm.data.matrix <- as.data.frame(cbind(y_1, X_1))
names(lm.data.matrix)[1] <- "co"

test.lm <- lm(formula(model.ramp), lm.data.matrix)
summary(test.lm)




y_1 <- as.numeric(NEresp_new[[1]])

#with OLR
X_1 <- cbind(as.matrix(NEpreds_new[[1]][ ,1:312]))
#without OLR
#X_1 <- cbind(as.matrix(NEpreds_new[[1]][ ,1:260]))

negroup1 <- RAMP(X = X_1, y = y_1,
                             penalty = "LASSO",
                             tune = "BIC",
                             n.lambda = 500)

#terms only
NE1.terms <- terms_only(negroup1, X_1)


```

```{r woOLR_anovatest}
#check on OLR

#NE Aus 1
NE1.temp <- NE1.terms[-c(7, 9)]
NE1.model.string <- paste0("co ~ ", paste(NE1.temp, collapse = " + "))
#NE Aus Group 1
y_1 <- as.numeric(NEresp_new[[1]])
#with OLR
X_1 <- cbind(as.matrix(NEpreds_new[[1]][ ,1:312]))
lm.data_1 <- as.data.frame(cbind(y_1, X_1))
names(lm.data_1)[1] <- "co"

NE1.lm.refit <- lm(formula(NE1.model.string), lm.data_1)
#summary(NE1.lm.refit)

anova(NE1.lm.refit, NE1.lm)
anova(NE1.lm.noOLR, NE1.lm )

#NE Aus 2
NE2.temp <- NE2.terms[-c(9, 10)]


NE3.terms[-c(8, 10, 17)]

SE1.terms[-c(12:15)]
SE2.terms[-c(6:8)]
SE3.terms[-c(8:12)]
```

