---
title: "residual_work"
author: "Ryan Peterson"
date: "2024-11-13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library}
suppressMessages(library(glmnet)) #base lasso (elastic net, etc.)

suppressMessages(library(lubridate))
suppressMessages(library(forecast))
suppressMessages(library(tseries))
```


```{r data_load}
setwd("~/CO_AUS/Aus_CO-main")

load("ne_data.rda")
load("se_data.rda")
load("bounded_data.rda")
load("data_matrix.rda")
load("lag_list.rda")

load("base_preds.rda")


source("group_functions.R")
```




```{r}
#set up season years/weeks
season_weeks <- c(35:52, 1:14)
season_years <- unique(bounded_resp_df$year)

seasons <- c()
for (i in 1:(length(season_years)-1)) {
  temp_season <- paste0(season_years[i], "-", season_years[i+1])
  #print(temp_season)  
  seasons <- c(seasons, temp_season)
}
rm(i, temp_season)

```





# Residual modeling attempts

```{r}
#TODO: add in olr data to see if anything there seems to make sense

hist(NEgroup_list$Week_38$Resid, breaks = 10)

NEgroup_list$Week_38$True[11]

#get maximum residual for a given week
index_resid <- which.max(NEgroup_list$Week_38$Resid)

seasons[index_resid]

NEfull_coefs <- c(NE_coefs$Group_2$nino_coef, NE_coefs$Group_2$dmi_coef ,
                      NE_coefs$Group_2$tsa_coef , NE_coefs$Group_2$aao_coef)
NEGroup2_index <- which(NEfull_coefs!= 0)

NEfull_coefs[NEGroup2_index]
NEweek38_preds <-  NE_laglist_std$`Week  38`[,3:210]
NEweek38_olrd <- NE_laglist_std$`Week  38`[,211:262]


temp_preds <- NEweek38_preds[-19 ,NEGroup2_index]
temp_olr <- NEweek38_olrd[-19, ]

#TODO: just use a quantile instead
col_upper <- sapply(temp_preds, quantile, probs = 0.9)
#col_mean <- sapply(temp_preds, mean, na.rm = TRUE)
#col_sd <- sapply(temp_preds, sd, na.rm = TRUE)

#c <- 1.5
#col_upper <- col_mean + c*col_sd

exceed_matrix <- matrix(0, ncol = 98, nrow = 18)
colnames(exceed_matrix) <- colnames(temp_preds)

#TODO: fix this since it doesn't quite do what I want (create for loop)
for(k in 1:length(NEGroup2_index)){
  ind_upper <- which(temp_preds[ ,k] >= col_upper[k])
  exceed_matrix[ind_upper,k] <- 1
}

temp_matrix <- matrix(NA, ncol = 98)
new_term <- NEfull_coefs[NEGroup2_index] * temp_preds[11,]
temp_matrix <- rbind(NEfull_coefs[NEGroup2_index], temp_preds[11,], new_term, exceed_matrix[11,] )
colnames(temp_matrix) <- colnames(temp_preds)
rownames(temp_matrix) <- c("coef", "data", "new", "exceed")



#NEweek38_preds[index_resid ,NEGroup2_index] 

```


```{r resid38}
#plot NE week 38 resids
NE38_resids <- NEgroup_list$Week_38$Resid
NE38_true <- NEgroup_list$Week_38$True
NE38_pred  <- NEgroup_list$Week_38$Pred
years_resids <- season_years[1:18]

y_lim <- range(NE38_true,NE38_pred )

plot(years_resids, NE38_resids, ylim = y_lim,  type = "b", xlab = "",
        main = "NE Aus Week 38", axes = FALSE, pch = 20)
box()
axis(2)
axis(1, at = years_resids, labels = c(season_years[1:18]),
     las = 3)
lines(years_resids, NE38_true, col = "darkgreen")
lines(years_resids, NE38_pred, col = "magenta")
abline(v = c(2007, 2011), lty = 2, col = "red")


#plot SE week 38 resids
SE38_resids <- SEgroup_list$Week_38$Resid
SE38_true <- SEgroup_list$Week_38$True
SE38_pred  <- SEgroup_list$Week_38$Pred

y_lim <- range(SE38_true, SE38_pred )

plot(years_resids, SE38_resids, ylim = y_lim,  type = "b", xlab = "",
        main = "SE Aus Week 38", axes = FALSE, pch = 20)
box()
axis(2)
axis(1, at = years_resids, labels = c(season_years[1:18]),
     las = 3)
lines(years_resids, SE38_true, col = "darkgreen")
lines(years_resids, SE38_pred, col = "magenta")
abline(v = c(2007), lty = 2, col = "red")
```


```{r resid42}
#plot NE week 43 resids
NE43_resids <- NEgroup_list$Week_43$Resid
NE43_true <- NEgroup_list$Week_43$True
NE43_pred  <- NEgroup_list$Week_43$Pred
years_resids <- season_years[1:18]

y_lim <- range(NE43_true, NE43_pred )

plot(years_resids, NE43_resids, ylim = y_lim,  type = "b", xlab = "",
        main = "NE Aus Week 43", axes = FALSE, pch = 20)
box()
axis(2)
axis(1, at = years_resids, labels = c(season_years[1:18]),
     las = 3)
lines(years_resids, NE43_true, col = "darkgreen")
lines(years_resids, NE43_pred, col = "magenta")


#plot SE week 42 resids
SE42_resids <- SEgroup_list$Week_42$Resid
SE42_true <- SEgroup_list$Week_42$True
SE42_pred  <- SEgroup_list$Week_42$Pred

y_lim <- range(SE42_true, SE42_pred )

plot(years_resids, SE42_resids, ylim = y_lim,  type = "b", xlab = "",
        main = "SE Aus Week 42", axes = FALSE, pch = 20)
box()
axis(2)
axis(1, at = years_resids, labels = c(season_years[1:18]),
     las = 3)
lines(years_resids, SE42_true, col = "darkgreen")
lines(years_resids, SE42_pred, col = "magenta")
abline(v = c(2007), lty = 2, col = "red")
```

Let's try some dumb shit

```{r fit_2019}
#fit SE Aus 2019 data
#(test fit from week 42-52, 1-2)

SEcoefs_1 <- c(SE_coefs$Group_1$nino_coef, SE_coefs$Group_1$dmi_coef,
                      SE_coefs$Group_1$tsa_coef, SE_coefs$Group_1$aao_coef)
SEGroup1_index <- which(SEcoefs_1!= 0)

SEcoefs_2 <- c(SE_coefs$Group_2$nino_coef, SE_coefs$Group_2$dmi_coef,
                      SE_coefs$Group_2$tsa_coef, SE_coefs$Group_2$aao_coef)
SEGroup2_index <- which(SEcoefs_2!= 0)

SEcoefs_3 <- c(SE_coefs$Group_3$nino_coef, SE_coefs$Group_3$dmi_coef,
                      SE_coefs$Group_3$tsa_coef, SE_coefs$Group_3$aao_coef)
SEGroup3_index <- which(SEcoefs_3!= 0)

SEcoefs_4 <- c(SE_coefs$Group_4$nino_coef, SE_coefs$Group_4$dmi_coef,
                      SE_coefs$Group_4$tsa_coef, SE_coefs$Group_4$aao_coef)
SEGroup4_index <- which(SEcoefs_4!= 0)


se_resid1 <-  as.data.frame(matrix(NA, ncol = 4))
colnames(se_resid1) <- c("Week", "True", "Pred", "Resid")

for (k in 1:3) {
  se_week <- SE_laglist_std[[k]]
  temp_preds <- as.matrix(se_week[19, 3:210])
  temp_resp <- se_week[19, 2]
    
  pred_temp <- temp_preds %*% SEcoefs_1
  temp_resid <- temp_resp - pred_temp
  se_resid1 <- rbind(se_resid1, c(season_weeks[k], temp_resp, pred_temp, temp_resid))
}
se_resid1 <- se_resid1[-1, ]

se_resid2 <-  as.data.frame(matrix(NA, ncol = 4))
colnames(se_resid2) <- c("Week", "True", "Pred", "Resid")

for (k in 4:7) {
  se_week <- SE_laglist_std[[k]]
  temp_preds <- as.matrix(se_week[19, 3:210])
  temp_resp <- se_week[19, 2]
    
  pred_temp <- temp_preds %*% SEcoefs_2
  temp_resid <- temp_resp - pred_temp
  se_resid2 <- rbind(se_resid2, c(season_weeks[k], temp_resp, pred_temp, temp_resid))
}
se_resid2 <- se_resid2[-1, ]


se_resid3 <-  as.data.frame(matrix(NA, ncol = 4))
colnames(se_resid3) <- c("Week", "True", "Pred", "Resid")

for (k in 8:16) {
  se_week <- SE_laglist_std[[k]]
  temp_preds <- as.matrix(se_week[19, 3:210])
  temp_resp <- se_week[19, 2]
    
  pred_temp <- temp_preds %*% SEcoefs_3
  temp_resid <- temp_resp - pred_temp
  se_resid3 <- rbind(se_resid3, c(season_weeks[k], temp_resp, pred_temp, temp_resid))
}

se_resid3 <- se_resid3[-1, ]

se_resid4 <-  as.data.frame(matrix(NA, ncol = 4))
colnames(se_resid4) <- c("Week", "True", "Pred", "Resid")

for (k in 17:20) {
  se_week <- SE_laglist_std[[k]]
  temp_preds <- as.matrix(se_week[19, 3:210])
  temp_resp <- se_week[19, 2]
    
  pred_temp <- temp_preds %*% SEcoefs_4
  temp_resid <- temp_resp - pred_temp
  se_resid4 <- rbind(se_resid4, c(season_weeks[k], temp_resp, pred_temp, temp_resid))
}

se_resid4 <- se_resid4[-1, ]


```

```{r}
se_resid <- rbind(se_resid3, se_resid4)

y_lim <- range(se_resid$Resid, se_resid$True, se_resid$Pred)

plot(1:13, se_resid$Resid, ylim = y_lim,  type = "b", xlab = "", ylab = "Atmospheric CO",
        main = "SE Aus 2019/2020", axes = FALSE, pch = 20)
box()
axis(2)
axis(1, at = 1:13, labels = c( paste0("Week ", season_weeks[8:20])),
     las = 3)
lines(1:13, se_resid$True, col = "darkgreen")
lines(1:13, se_resid$Pred, col = "magenta")
abline(v = 8.5, lty = 2, col = "red")




```

```{r SE group 3:4}
#group 3 weeks 8-16
#SE_laglist_std[[8]]

SEGroup3_index <- which(SEcoefs_3!= 0)

#technically only need a single week in the group to get the matrix (we can compare with others)
k <- 8
SEweek_preds <-  SE_laglist_std[[k]][,3:210]
SEweek_olr <- SE_laglist_std[[k]][,211:262]


temp_preds <- SEweek_preds[ ,SEGroup3_index]
temp_olr <- SEweek_olr

#TODO: just use a quantile instead
col_upper <- sapply(temp_preds, quantile, probs = 0.9)
olr_upper <- sapply(temp_olr, quantile, probs = 0.9)


SEGroup3_exceed <- matrix(0, ncol = 128, nrow = 19)
colnames(SEGroup3_exceed) <- colnames(temp_preds)

for(k in 1:length(SEGroup3_index)){
  ind_upper <- which(temp_preds[ ,k] >= col_upper[k])
  SEGroup3_exceed[ind_upper,k] <- 1
}

#group 4 weeks 17-20
#SE_laglist_std[[8]]

SEGroup4_index <- which(SEcoefs_4!= 0)
SEweek_preds <-  SE_laglist_std[[17]][,3:210]

temp_preds <- SEweek_preds[ ,SEGroup4_index]
#technically only need a single week in the group to get the matrix (we can compare with others)
SEGroup4_exceed <- matrix(NA, ncol = 84)
colnames(SEGroup4_exceed) <- colnames(temp_preds)

#build a matrix of 1/0 
for (k in 17:20) {
  SEweek_preds <-  SE_laglist_std[[k]][,3:210]
  SEweek_olr <- SE_laglist_std[[k]][,211:262]

  temp_preds <- SEweek_preds[ -19, SEGroup4_index]
  #temp_olr <- SEweek_olr
  
  #TODO: change the range of the temp preds to be all lags (and all years)? 
  col_upper <- sapply(temp_preds, quantile, probs = 0.9)
  #olr_upper <- sapply(temp_olr, quantile, probs = 0.9)
  
  temp_exceed <- matrix(0, ncol = 84, nrow = 18)
  colnames(SEGroup4_exceed) <- colnames(temp_preds)
  
  for(k in 1:length(SEGroup4_index)){
    ind_upper <- which(temp_preds[ ,k] >= col_upper[k])
    temp_exceed[ind_upper,k] <- 1
  }
  SEGroup4_exceed <- rbind(SEGroup4_exceed, temp_exceed)
}

SEGroup4_exceed <- SEGroup4_exceed[-1, ]

#olr data
SEGroup4_olr <- matrix(NA, ncol = 52)
colnames(SEGroup4_olr) <- colnames(SE_laglist_std[[1]][,211:262])

for (j in 17:20) {
  SEweek_olr <- SE_laglist_std[[j]][-19, 211:262]
  SEGroup4_olr <- rbind(SEGroup4_olr, SEweek_olr)
}

SEGroup4_olr <- SEGroup4_olr[-1, ]


#TODO get this working and try quadratics again.

SEGroup4_quad <- matrix(NA, ncol = 82)
colnames(SEGroup4_quad) <- colnames(temp_preds)

for (k in 17:20) {
  SEweek_preds <-  SE_laglist_std[[k]][,3:210]
  temp_preds <- SEweek_preds[ -19,SEGroup4_index]
  SEGroup4_quad <- rbind(SEGroup4_quad, temp_preds)
}

SEGroup4_quad <- SEGroup4_quad[-1, ]
SEGroup4_quad <- SEGroup4_quad^2
SEGroup4_quad <- as.matrix(SEGroup4_quad)
```


```{r quantiles}
  #olr_upper <- sapply(temp_olr, quantile, probs = 0.9)
low <- 0.1
upp <- 0.9

nino_matrix <- pred_matrix[ ,1:52]
nino_quantiles  <- quantile(nino_matrix, probs = c(low, upp))

dmi_matrix <- pred_matrix[ ,53:104]
dmi_quantiles <- quantile(dmi_matrix, probs = c(low, upp))

tsa_matrix <- pred_matrix[ ,105:156]
tsa_quantiles <- quantile(tsa_matrix, probs = c(low, upp))

aao_matrix <- pred_matrix[ ,157:208]
aao_quantiles <- quantile(aao_matrix, probs = c(low, upp))


```


```{r}
#group 4 weeks 17-20

SEGroup4_index <- which(SEcoefs_4!= 0)
#TODO: funtionalize this
nino_group <- SEGroup4_index[SEGroup4_index <= 52]
dmi_group <- SEGroup4_index[SEGroup4_index > 52 & SEGroup4_index <= 104]
tsa_group <- SEGroup4_index[SEGroup4_index > 104 & SEGroup4_index <= 156]
aao_group <- SEGroup4_index[SEGroup4_index > 156 & SEGroup4_index <= 208]

SEGroup4_upper <- c(rep(nino_quantiles[2], length(nino_group)),
                    rep(dmi_quantiles[2], length(dmi_group)),
                    rep(tsa_quantiles[2], length(tsa_group)),
                    rep(aao_quantiles[2], length(aao_group)))

SEGroup4_lower <- c(rep(nino_quantiles[1], length(nino_group)),
                    rep(dmi_quantiles[1], length(dmi_group)),
                    rep(tsa_quantiles[1], length(tsa_group)),
                    rep(aao_quantiles[1], length(aao_group)))



SEweek_preds <-  SE_laglist_std[[17]][,3:210]

temp_preds <- SEweek_preds[ ,SEGroup4_index]
#technically only need a single week in the group to get the matrix (we can compare with others)
SEGroup4_exceed <- matrix(NA, ncol = length(temp_preds))
colnames(SEGroup4_exceed) <- colnames(temp_preds)

#build a matrix of 1/0 
for (k in 17:20) {
  SEweek_preds <-  SE_laglist_std[[k]][,3:210]
  SEweek_olr <- SE_laglist_std[[k]][,211:262]

  temp_preds <- SEweek_preds[ -19, SEGroup4_index]

  temp_exceed <- matrix(0, nrow(temp_preds), ncol(temp_preds))
  colnames(SEGroup4_exceed) <- colnames(temp_preds)
  
  for(j in 1:length(SEGroup4_index)){
    
    ind_upper <- which(temp_preds[ ,j] >= SEGroup4_upper[j])
    temp_exceed[ind_upper,j] <- 1
  }
  
  SEGroup4_exceed <- rbind(SEGroup4_exceed, temp_exceed)
}

SEGroup4_exceed <- SEGroup4_exceed[-1, ]


SEGroup4_under<- matrix(NA, ncol = length(temp_preds))
colnames(SEGroup4_under) <- colnames(temp_preds)

#build a matrix of 1/0 
for (k in 17:20) {
  SEweek_preds <-  SE_laglist_std[[k]][,3:210]
  SEweek_olr <- SE_laglist_std[[k]][,211:262]

  temp_preds <- SEweek_preds[ -19, SEGroup4_index]

  temp_under <- matrix(0, nrow(temp_preds), ncol(temp_preds))
  colnames(SEGroup4_under) <- colnames(temp_preds)
  
  for(j in 1:length(SEGroup4_index)){
    
    ind_lower <- which(temp_preds[ ,j] >= SEGroup4_lower[j])
    temp_under[ind_lower,j] <- 1
  }
  
  SEGroup4_under <- rbind(SEGroup4_under, temp_under)
}

SEGroup4_under <- SEGroup4_under[-1, ]



SEGroup4_quad <- matrix(NA, ncol = 82)
colnames(SEGroup4_quad) <- colnames(temp_preds)

for (k in 17:20) {
  SEweek_preds <-  SE_laglist_std[[k]][,3:210]
  temp_preds <- SEweek_preds[ -19,SEGroup4_index]
  SEGroup4_quad <- rbind(SEGroup4_quad, temp_preds)
}

SEGroup4_quad <- SEGroup4_quad[-1, ]
SEGroup4_quad <- SEGroup4_quad^2
SEGroup4_quad <- as.matrix(SEGroup4_quad)
```

```{r}
SEgroup4_resid <- c()
for (j in 17:20) {
  SEgroup4_resid <- c(SEgroup4_resid, c(SEgroup_list[[j]]$Resid)) #, se_resid4$Resid[j-16]))
}

nino_upper <- SEGroup4_exceed[,1:29]
dmi_upper <- SEGroup4_exceed[ ,30:54]
tsa_upper <- SEGroup4_exceed[ ,55:68]
aao_upper <- SEGroup4_exceed[ ,69:84]

SE4upper_fit <- lm(SEgroup4_resid ~  nino_upper)
summary(SE4upper_fit)

nino_lower <- SEGroup4_under[,1:29]
dmi_lower <- SEGroup4_under[ ,30:54]
tsa_lower <- SEGroup4_under[ ,55:68]
aao_lower <- SEGroup4_under[ ,69:84]

SE4lower_fit <- lm(SEgroup4_resid ~  tsa_lower)
summary(SE4lower_fit)

nino_quad <- SEGroup4_quad[,1:29]
dmi_quad <- SEGroup4_quad[ ,30:54]
tsa_quad <- SEGroup4_quad[ ,55:68]
aao_quad <- SEGroup4_quad[ ,69:84]

SE4quad_fit <- lm(SEgroup4_resid ~ tsa_quad)
summary(SE4quad_fit)

#NE_preds <- NElag_grouping(NE_laglist = NE_laglist_std, j = -19)
SE_preds <- SElag_grouping(SE_laglist = SE_laglist_std, j = -19)
SE_quad <- as.data.frame(SEGroup4_quad)

olr_lag2 <- SEGroup4_olr$SEolr_lag2


quad_dmilag2 <- SE_quad$dmi_lag2
pred_dmilag2 <- SE_preds[[4]]$dmi_lag2

quad_ninolag29 <- SE_quad$nino_lag29
pred_ninolag29 <-  SE_preds[[4]]$nino_lag29

quad_dmilag3 <- SE_quad$dmi_lag3
pred_dmilag4 <- SE_preds[[4]]$dmi_lag4

quad_tsa8 <- SE_quad$tsa_lag8
pred_tsa8 <- SE_preds[[4]]$tsa_lag8
pred_ninolag23 <- SE_preds[[4]]$nino_lag23

SEGroup4_exceeddf <- as.data.frame(SEGroup4_exceed)
dmilag2 <- SEGroup4_exceeddf$dmi_lag2
nino_lag29 <- SEGroup4_exceeddf$nino_lag29

SEGroup4_underdf <- as.data.frame(SEGroup4_under)
tsa_lag8 <- SEGroup4_underdf$tsa_lag8

SE4_fit <- lm(SEgroup4_resid ~ quad_dmilag2*dmilag2)
summary(SE4_fit)
```


```{r glmnet_exceedence}
set.seed(300)
cv_fit <- cv.glmnet(SEGroup4_quad, SEgroup4_resid, alpha = 0.05, nfolds = 5, family = "gaussian")
plot(cv_fit)

best_lambda <- cv_fit$lambda.min

test_model <- glmnet(SEGroup4_quad, SEgroup4_resid, alpha = 0.05, family = "gaussian")
test_pred <- predict(test_model, s = best_lambda, type = "coefficients")

#predicted coefficients
preds <- test_pred@i+1
test_pred[preds, ]
```

```{r test_residfit}
new_preds <- matrix(NA, ncol = 2)
colnames(new_preds) <- c("quad_dmilag2", "dmilag2")

for (k in 17:20) {
  se_week <- SE_laglist_std[[k]]$dmi_lag2
  temp_preds <- c(se_week[19]^2)
  
  if (se_week[19] >= dmi_quantiles[2]) {
    temp_preds <- c(temp_preds, 1)
  } else  {
    temp_preds <- c(temp_preds, 0)
  }
 new_preds <- rbind(new_preds, temp_preds) 
}  
  
new_preds <- new_preds[-1, ]
```

```{r}
preds_2019 <- predict(SE4_fit, as.data.frame(new_preds), interval = "prediction")
se_resid4$Resid
preds_2019

nino_quantiles
dmi_quantiles
se_2019 <- SE_laglist_std$`Week  2`[19,]
```

```{r}
se_resid4$Pred
new_preds4 <- preds_2019[,1]+se_resid4$Pred
new_resid4 <- se_resid4$True - new_preds4


new_resid <- c(se_resid3$Resid, new_resid4)
new_preds <- c(se_resid3$Pred, new_preds4)

se_resid <- rbind(se_resid3, se_resid4)


y_lim <- range(se_resid$Resid, se_resid$True, se_resid$Pred)

png(filename = "SE_newpreds.png", width = 2500, height = 1500, res = 300)
par(mar = c(5, 4, 4, 9.5) + 0.2, xpd = TRUE)
plot(1:13, new_resid, ylim = y_lim,  type = "l", xlab = "", 
     ylab = "Atmospheric CO",
        main = "SE Aus 2019-2020", axes = FALSE, lwd = 2)
box()
axis(2)
axis(1, at = 1:13, labels = c( paste0("Week ", season_weeks[8:20])),
     las = 3)
lines(1:13, se_resid$True, col = "darkgreen")
lines(1:13, se_resid$Pred, col = "magenta", lwd = 1.5)
#lines(1:13, se_resid$Pred, col = "magenta")
lines(9:13, new_preds[9:13], col = "darkmagenta", lwd = 1.75)
segments(x0 = 9.5, y0 = -20, x1 = 9.5, y1 = 53, lty = 2, col = "red")
#abline(v = 9.5, lty = 2, col = "red")
legend("topright", inset = c(-0.32, 0),
       legend = c("Residual", "True", "Lasso Pred", "w/ Residual Fit"),
       col = c("black", "darkgreen", "magenta", "darkmagenta"), 
       lty = 1, lwd = 2, bty = "o") #, bg = "white")
text(5, 50, "Group 3", col = "red", cex = 0.75)
text(10.5, 50, "Group 4", col = "red", cex = 0.75)
dev.off()




```


```{r}
nino_group <- SEGroup4_index[SEGroup4_index <= 52]
dmi_group <- SEGroup4_index[SEGroup4_index > 52 & SEGroup4_index <= 104]
tsa_group <- SEGroup4_index[SEGroup4_index > 104 & SEGroup4_index <= 156]
aao_group <- SEGroup4_index[SEGroup4_index > 156 & SEGroup4_index <= 208]
SE_laglist_std$`Week  50`[ ,SEGroup4_index+2]

updated_se50 <- SE_laglist_std$`Week  50`[,-c(1:2)]

nino_int <- updated_se50[ ,c(nino_group)]

dmi_int <- updated_se50[ ,dmi_group]

tsa_int <- updated_se50[ ,tsa_group]

aao_int <- updated_se50[ ,aao_group]
```

```{r olr_smooth}
#smooth the olr data
ksmooth(x = predictors[[i]]$time,
                                    y = predictors[[i]]$anomaly,
                                    kernel = "normal",
                                    bandwidth = mult.seq[j]*x.dist)
```


```{r resid_vector}
SEgroup4_resid <- c()
for (j in 17:20) {
  SEgroup4_resid <- c(SEgroup4_resid, c(SEgroup_list[[j]]$Resid)) #, se_resid4$Resid[j-16]))
}



olr_fit <- lm(SEgroup4_resid ~ as.matrix(SEGroup4_olr))
summary(olr_fit)

#TODO: try this again with SEGroup4_exceed and after shifting where we perform our quantile checks,
## That is group predictor data then do a quantile check across all of that data, or use a full year (lag 1-52) for quantile. 

#length(c(SEgroup_list[[17]]$Resid, se_resid4$Resid[1]))
#j -16
```



```{r test_glm}
set.seed(300)
cv_fit <- cv.glmnet(as.matrix(SEGroup4_olr), SEgroup4_resid, alpha = 0.75, nfolds = 5, family = "gaussian")
plot(cv_fit)

best_lambda <- cv_fit$lambda.min

test_model <- glmnet(SEGroup4_olr, SEgroup4_resid, alpha = 0.5, family = "gaussian")
test_pred <- predict(test_model, s = best_lambda, type = "coefficients")

#predicted coefficients
preds <- test_pred@i+1
test_pred[preds, ]
```

```{r}
#example glmnet

reduced_preds <- as.matrix(NE1_preds[,1:208])
reduced_preds <- scale(reduced_preds, center = TRUE, scale = TRUE)
row.names(NEAus_1) <- 1:19

set.seed(300)
cv_fit <- cv.glmnet(reduced_preds, NEAus_1, alpha = 0.815, nfolds = 5, family = "mgaussian")
plot(cv_fit)

best_lambda <- cv_fit$lambda.min

test_model <- glmnet(reduced_preds, NEAus_1, alpha = 0.815, family = "mgaussian")
test_pred <- predict(test_model, s = best_lambda, type = "coefficients")
```


TODO: next try some more EDA on these residuals
check on the CV-loo properties of model selection
see we can fit a var/varma on the residuals.

# Time Series Residuals

Building AR, ARMA, ARIMA models on the model residuals.

```{r ts_setup}

NE_resids <- matrix(NA, nrow = 18)
for (k in 1:length(season_weeks)) {
  NE_resids <- cbind(NE_resids, NEgroup_list[[k]]$Resid)
}

NE_resids <- NE_resids[,-1]
colnames(NE_resids) <- season_weeks

plot(1:32, NE_resids[1,], type = "l")
#lines(1:32, NE_resids[2,])

#SEgroup_list
SE_resids <- matrix(NA, nrow = 18)
for (k in 1:length(season_weeks)) {
  SE_resids <- cbind(SE_resids, SEgroup_list[[k]]$Resid)
}

SE_resids <- SE_resids[,-1]
colnames(SE_resids) <- season_weeks

plot(1:32, SE_resids[2,], type = "l")
```

## TS set-up

```{r}

weekly_dates <- c()


#TODO: add in 2019/2020
for (year in 2001:2018) {
  
  temp1 <- bounded_resp_df[which(bounded_resp_df$year == year), ]
  start1 <- as.Date(temp1[which(temp1$week == 35), 1])
  end1 <- as.Date(temp1[which(temp1$week == 52), 1])
  
  #temp2 <- bounded_resp_df[which(bounded_resp_df$year == year+1), ]
  #start2 <- as.Date(temp2[which(temp2$week == 1), 1])
  #end2 <- as.Date(temp2[which(temp2$week == 14), 1])
  
  weekly1 <- seq(from = start1, to = end1, by = "week")
  #weekly2 <- seq(from = start2, to = end2, by = "week")
  
  weekly_dates <- c(weekly_dates, weekly1)#, weekly2)
}

asWeek <- as.Date(weekly_dates)

#asWeek
#update with part of 2019 season data
temp1 <- bounded_resp_df[which(bounded_resp_df$year == 2019), ]
start1 <- as.Date(temp1[which(temp1$week == 35), 1])
end1 <- as.Date(temp1[which(temp1$week == 52), 1])
weeklynew <- seq(from = start1, to = end1, by = "week")

asWeek_new <- as.Date(weeklynew)

fullweekly_dates <- c(weekly_dates, weeklynew)
FullasWeek <- as.Date(fullweekly_dates)
max(FullasWeek)


```

```{r}
NE_ts_df <- data.frame(
  Date = asWeek,
  Residuals = as.vector(t(NE_resids[,1:18]))
)


SE_ts_df <- data.frame(
  Date = asWeek,
  Residuals = as.vector(t(SE_resids[,1:18]))
)

#TODO: account for the large gaps
#example code (adjust accordingly)
# Create a complete sequence of weeks
NEall_weeks <- seq(min(NE_ts_df$Date), max(NE_ts_df$Date), by = "week")

# Merge original data with all weeks
NEfull_data <- merge(data.frame(Date = NEall_weeks), NE_ts_df, by = "Date", all.x = TRUE)

# Fill missing weeks with NA
NEfull_ts <- ts(NEfull_data$Residuals, frequency = 52)


# Create a complete sequence of weeks
SEall_weeks <- seq(min(SE_ts_df$Date), max(SE_ts_df$Date), by = "week")

# Merge original data with all weeks
SEfull_data <- merge(data.frame(Date = SEall_weeks), SE_ts_df, by = "Date", all.x = TRUE)

# Fill missing weeks with NA
SEfull_ts <- ts(SEfull_data$Residuals, frequency = 52)

# ACF and PACF on the padded time series

acf(NEfull_ts, na.action = na.pass, main = "NE ACF with Missing Weeks")
pacf(NEfull_ts, na.action = na.pass, main = "NE PACF with Missing Weeks")

acf(SEfull_ts, na.action = na.pass, main = "SE ACF with Missing Weeks")
pacf(SEfull_ts, na.action = na.pass, main = "SE PACF with Missing Weeks")



acf(NE_ts_df$Residuals, main = "NE ACF without Regular Frequency")


pacf(NE_ts_df$Residuals, main = "NE PACF without Regular Frequency")

acf(SE_ts_df$Residuals, main = "SE ACF without Regular Frequency")
pacf(SE_ts_df$Residuals, main = "SE PACF without Regular Frequency")


acf(diff(diff(NE_ts_df$Residuals)), main = "NE ACF without Regular Frequency")
acf(diff(SE_ts_df$Residuals), main = "NE ACF without Regular Frequency")

pacf(diff(diff(NE_ts_df$Residuals)), main = "NE PACF without Regular Frequency")
pacf(diff(diff(SE_ts_df$Residuals)), main = "SE PACF without Regular Frequency")
```

```{r}
auto.arima(NEfull_ts)
auto.arima(SEfull_ts)
```

```{r}

#NE_ar_model <- Arima(NEfull_ts, order = c(4, 1, 0))
#summary(NE_ar_model)

NE_ar_model <- Arima(NEfull_data$Residuals, order = c(4, 1, 0))
summary(NE_ar_model)
NE_ar_model$bic

SE_ar_model <- Arima(SEfull_data$Residuals, order = c(1, 0, 0))
summary(SE_ar_model)
SE_ar_model$bic


NEfull_data$ts_residuals <- residuals(NE_ar_model)
SEfull_data$ts_residuals <- residuals(SE_ar_model)
```


```{r}
#TODO: update week to the full dataframe (that include NAs) then rerun the model 

#until then
new_NEdf <- NEfull_data[!is.na(NEfull_data$Residuals), ]
new_NEdf$new_index <- rep(1:32, length.out = nrow(new_NEdf))

new_SEdf <- SEfull_data[!is.na(SEfull_data$Residuals), ]
new_SEdf$new_index <- rep(1:32, length.out = nrow(new_SEdf))
```


```{r}

residNE_box_df <- data.frame(values = NA, group = NA)
residSE_box_df <- data.frame(values = NA, group = NA)

for (i in 1:32) {
  temp_ne <- new_NEdf[which(new_NEdf$new_index == i), ]
  temp_vals <- temp_ne$ts_residuals
  temp_group <- rep(season_weeks[i], length(temp_ne$ts_residuals))
  residNE_box_df <- rbind(residNE_box_df, list(temp_vals, temp_group))
  
  temp_se <- new_NEdf[which(new_SEdf$new_index == i), ]  
  temp_vals1 <- temp_se$ts_residuals
  temp_group1 <- rep(season_weeks[i], length(temp_se$ts_residuals))
  residSE_box_df <- rbind(residSE_box_df, list(temp_vals1, temp_group1))
}


setwd("~/CO_AUS/Aus_CO-main/Figures_Simple")

#TODO:update using resid_lim from the simplified linear model
resid_lim <- c(-20, 20)

png("NEresid_ts.png", width = 800, height = 600, res = 100)
par(mar = c(8, 4, 4, 2) + 0.1)
boxplot(values ~ group, data = residNE_box_df, ylim = resid_lim, ylab = "Residuals", xlab = "",
        main = "NE Aus Residuals",axes = FALSE, pch = 20)
box()
axis(2)
axis(1, at = 1:32, labels = c(paste0("Week ", season_weeks[1:32])),
     las = 3)
abline(h = 0, lty = 2)
dev.off()


png("SEresid_ts.png", width = 800, height = 600, res = 100)
par(mar = c(8, 4, 4, 2) + 0.1)
boxplot(values ~ group, data = residSE_box_df, ylim = resid_lim, ylab = "Residuals", xlab = "",
        main = "SE Aus Residuals",axes = FALSE, pch = 20)
box()
axis(2)
axis(1, at = 1:32, labels = c(paste0("Week ", season_weeks[1:32])),
     las = 3)
abline(h = 0, lty = 2)
dev.off()
```


```{r 2019-2020 season}
se_residnew <- rbind(se_resid1, se_resid2, se_resid3, se_resid4)

se_resid_pred <- se_residnew[-c(1:16),]
se_residnew1 <- se_residnew[1:16,]


SE_tsnew_df <- data.frame(
  Date = asWeek_new[1:16],
  Residuals = as.vector(t(se_residnew1$Resid))
)

SE_complete <- rbind(SE_ts_df, SE_tsnew_df)

SEall_weeks <- seq(min(SE_ts_df$Date), max(SE_tsnew_df$Date), by = "week")

# Merge original data with all weeks
SEnew_data <- merge(data.frame(Date = SEall_weeks), SE_complete, by = "Date", all.x = TRUE)


#SE_new_model <- arima(SEnew_data$Residuals, order = c(4,0,1), include.mean = FALSE)
SE_new_model <- arma(SEnew_data$Residuals, lag = list(ar = c(3,4,8)), na.action=na.remove)
summary(SE_new_model)


SEnew_data$ts_residuals <- residuals(SE_new_model)

forecast_new <- forecast(SE_new_model, h = 5)
forecast_new

upper_preds <- c()
new_preds <- c()
for (i in 1:5) {
  temp_pred <- forecast_new$mean[i] + se_resid_pred[i,]$Pred
  new_preds <- c(new_preds, temp_pred)
  
  temp_upper <- forecast_new$upper[i,2] + se_resid_pred[i,]$Pred
  upper_preds <- c(upper_preds, temp_upper)
}



plot(forecast_new, xlim = c(939, 965))
lines(940:959,  se_residnew$True , col = "magenta")
lines(940:959,  se_residnew$Pred , col = "darkmagenta")
lines(956:960,  new_preds)
lines(956:960,  upper_preds, lty = 2, col = "red")
 #predict(SE_new_model, n.ahead = 4)
```

