---
title: "results_test.rmd"
author: "Ryan Peterson"
date: "2025-05-04"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
suppressMessages( library( lubridate))

suppressMessages( library( fields))
```

```{r data_functions}
setwd("~/CO_AUS/Aus_CO-main/Interactions")

load( "Data/ne_data.rda")
load( "Data/se_data.rda")
load( "Data/bounded_data.rda")
load( "Data/data_matrix.rda")
load( "Data/lag_list.rda")

source("group_functionsNew.R") #New grouping/clustering
```

Outline:
(Note: order can change)

1. Correlation Plots

# Correlation


```{r setup}
#season years/weeks
season_weeks <- c(35:52, 1:14)
season_years <- unique(bounded_resp_df$year)

seasons <- c()
for (i in 1:(length(season_years)-1)) {
  temp_season <- paste0(season_years[i], "-", season_years[i+1])
  #print(temp_season)  
  seasons <- c(seasons, temp_season)
}
rm(i, temp_season)

#center response data
NEbase_matrix <- scale(resp_matrix[ ,1:32], center = TRUE, scale = FALSE)
SEbase_matrix <- scale(resp_matrix[ ,33:64], center = TRUE, scale = FALSE)

#NEAus
NEAus_1 <- NEbase_matrix[ ,1:12] 
NEAus_2 <- NEbase_matrix[ ,13:17]
NEAus_3 <- NEbase_matrix[ ,18:32]

#NEAus
SEAus_1 <- SEbase_matrix[ ,1:16] 
SEAus_2 <- SEbase_matrix[ ,17:20] 
SEAus_3 <- SEbase_matrix[ ,21:32]

NEAus_mat <- list(NEAus_1, NEAus_2, NEAus_3)
SEAus_mat <- list(SEAus_1, SEAus_2, SEAus_3)

rm(NEAus_1, NEAus_2, NEAus_3, SEAus_1, SEAus_2, SEAus_3)


#full model
NE_preds <- NElag_3group(NE_laglist = NE_laglist_std, j = 1:19)
NE_resp <- NEresp_3group(NEAus_mat = NEAus_mat, j = 1:19)

SE_preds <- SElag_3group(SE_laglist = SE_laglist_std, j = 1:19)
SE_resp <- SEresp_3group(SEAus_mat = SEAus_mat, j = 1:19)
```


```{r Correlation_checks}
NEcor_list <- list()
for (j in 1:3) {
  ne_df <- as.data.frame(cbind(NE_resp[[j]], NE_preds[[j]]))

  nino_cor <- cor(ne_df, method = "pearson")[2:53]
  dmi_cor <- cor(ne_df, method = "pearson")[54:105]
  tsa_cor <- cor(ne_df, method = "pearson")[106:157]
  aao_cor <- cor(ne_df, method = "pearson")[158:209]
  olr_cor <- cor(ne_df, method = "pearson")[210:261]
  
  cor_df <- data.frame(nino_cor, dmi_cor, tsa_cor, aao_cor, olr_cor)
  
  NEcor_list[[paste("NEAus_", j)]] <- cor_df
}

SEcor_list <- list()
for (j in 1:3) {
  se_df <- as.data.frame(cbind(SE_resp[[j]], SE_preds[[j]]))

  nino_cor <- cor(se_df, method = "pearson")[2:53]
  dmi_cor <- cor(se_df, method = "pearson")[54:105]
  tsa_cor <- cor(se_df, method = "pearson")[106:157]
  aao_cor <- cor(se_df, method = "pearson")[158:209]
  olr_cor <- cor(se_df, method = "pearson")[210:261]
  
  cor_df <- data.frame(nino_cor, dmi_cor, tsa_cor, aao_cor, olr_cor)
  
  SEcor_list[[paste("SEAus_", j)]] <- cor_df
}



plot(1:52, nino_cor)
plot(1:52, dmi_cor)
plot(1:52, tsa_cor)
plot(1:52, aao_cor)
plot(1:52, olr_cor)
```


```{r NEAus_cor}
#nino - NE Aus
nino_max1 <- which.max(abs( NEcor_list[[1]]$nino_cor))
nino_max2 <- which.max(abs( NEcor_list[[2]]$nino_cor))
nino_max3 <- which.max(abs( NEcor_list[[3]]$nino_cor))
#DMI - NE Aus
dmi_max1 <- which.max(abs( NEcor_list[[1]]$dmi_cor))
dmi_max2 <- which.max(abs( NEcor_list[[2]]$dmi_cor))
dmi_max3 <- which.max(abs( NEcor_list[[3]]$dmi_cor))
#TSA - NE Aus
tsa_max1 <- which.max(abs( NEcor_list[[1]]$tsa_cor))
tsa_max2 <- which.max(abs( NEcor_list[[2]]$tsa_cor))
tsa_max3 <- which.max(abs( NEcor_list[[3]]$tsa_cor))
#AAO - NE Aus
aao_max1 <- which.max(abs( NEcor_list[[1]]$aao_cor))
aao_max2 <- which.max(abs( NEcor_list[[2]]$aao_cor))
aao_max3 <- which.max(abs( NEcor_list[[3]]$aao_cor))
# OLR - NE Aus
olr_max1 <- which.max(abs( NEcor_list[[1]]$olr_cor))
olr_max2 <- which.max(abs( NEcor_list[[2]]$olr_cor))
olr_max3 <- which.max(abs( NEcor_list[[3]]$olr_cor))


setwd("~/CO_AUS/Aus_CO-main/Interactions/Figures")

png(filename = "NE_corr.png", width = 2600, height = 1800, res = 200)

set.panel(2,3)
plot(1:52, NEcor_list[[1]]$nino_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = rgb(1, 0, 0, 0.95))
abline(h = 0, lty = 2)
points(nino_max1, NEcor_list[[1]]$nino_cor[nino_max1], pch = 16, col = rgb(1, 0, 0, 0.95), cex = 1.33)
lines(1:52, NEcor_list[[2]]$nino_cor, col = rgb(0, 1, 0, 0.95))
points(nino_max2, NEcor_list[[2]]$nino_cor[nino_max2], pch = 17, col ="green4", cex = 1.33)
lines(1:52, NEcor_list[[3]]$nino_cor, col = rgb(0, 0, 1, 0.95))
points(nino_max3, NEcor_list[[3]]$nino_cor[nino_max3], pch = 19, col = rgb(0, 0, 1, 0.95), cex = 1.33)
title("Nino", adj = 0)


plot(1:52, NEcor_list[[1]]$dmi_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag", col = rgb(1, 0, 0, 0.95))
abline(h = 0, lty = 2)
points(dmi_max1, NEcor_list[[1]]$dmi_cor[dmi_max1], pch = , col = rgb(1, 0, 0, 0.95), cex = 1.33)
lines(1:52, NEcor_list[[2]]$dmi_cor, col = rgb(0, 1, 0, 0.95))
points(dmi_max2, NEcor_list[[2]]$dmi_cor[dmi_max2], pch = 17, col = "green4", cex = 1.33)
lines(1:52, NEcor_list[[3]]$dmi_cor, col = rgb(0, 0, 1, 0.95))
points(dmi_max3, NEcor_list[[3]]$dmi_cor[dmi_max3], pch = 19, col = rgb(0, 0, 1, 0.95), cex = 1.33)
title("DMI", adj = 0)




plot(1:52, NEcor_list[[1]]$tsa_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag", col = rgb(1, 0, 0, 0.95), lwd = 0.75)
abline(h = 0, lty = 2)
points(tsa_max1, NEcor_list[[1]]$tsa_cor[tsa_max1], pch = 16, col = rgb(1, 0, 0, 0.95), cex = 1.33)
lines(1:52, NEcor_list[[2]]$tsa_cor, col = rgb(0, 1, 0, 0.95))
points(tsa_max2, NEcor_list[[2]]$tsa_cor[tsa_max2], pch = 17, col = "green4", cex = 1.33)
lines(1:52, NEcor_list[[3]]$tsa_cor, col = rgb(0, 0, 1, 0.95))
points(tsa_max3, NEcor_list[[3]]$tsa_cor[tsa_max3], pch = 19, col = rgb(0, 0, 1, 0.95), cex = 1.33)
title("TSA", adj = 0)



plot(1:52, NEcor_list[[1]]$aao_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = rgb(1, 0, 0, 0.95))
abline(h = 0, lty = 2)
points(aao_max1, NEcor_list[[1]]$aao_cor[aao_max1], pch = 16, col = rgb(1, 0, 0, 0.95), cex = 1.33)
lines(1:52, NEcor_list[[2]]$aao_cor, col = rgb(0, 1, 0, 0.95))
points(aao_max2, NEcor_list[[2]]$aao_cor[aao_max2], pch = 17, col = "green4", cex = 1.33)
lines(1:52, NEcor_list[[3]]$tsa_cor, col = rgb(0, 0, 1, 0.95))
points(aao_max3, NEcor_list[[3]]$aao_cor[aao_max3], pch = 19, col = rgb(0, 0, 1, 0.95), cex = 1.33)
title("SAM (AAO)", adj = 0)


plot(1:52, NEcor_list[[1]]$olr_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag", col = rgb(1, 0, 0, 0.95))
abline(h = 0, lty = 2)
points(olr_max1, NEcor_list[[1]]$olr_cor[olr_max1], pch = 16, col = rgb(1, 0, 0, 0.95), cex = 1.33)
lines(1:52, NEcor_list[[2]]$olr_cor, col = rgb(0, 1, 0, 0.95))
points(olr_max2, NEcor_list[[2]]$olr_cor[olr_max2], pch = 17, col = "green4", cex = 1.33)
lines(1:52, NEcor_list[[3]]$olr_cor, col = rgb(0, 0, 1, 0.95))
points(olr_max3, NEcor_list[[3]]$olr_cor[olr_max3], pch = 19, col = rgb(0, 0, 1, 0.95), cex = 1.33)
title("OLR", adj = 0)

par(xpd = NA)
legend("topright", inset = c(-0.50, 0.00),
       legend = c("Group 1", "Group 2",  "Group 3"),
       pch = c(16, 17, 19),
       col = c( rgb(1, 0, 0, 0.95), 
                "green4",
                rgb(0, 0, 1, 0.95)),
       pt.cex = c(1.33, 1.33, 1.33),
       cex = 1.5)
mtext("NE Aus : Correlation", side = 3, outer = TRUE, line = -1.5, cex = 1.5)

dev.off()
```


```{r SEAus_cor}
#nino - SE Aus

#nino - NE Aus
nino_max1 <- which.max(abs( SEcor_list[[1]]$nino_cor))
nino_max2 <- which.max(abs( SEcor_list[[2]]$nino_cor))
nino_max3 <- which.max(abs( SEcor_list[[3]]$nino_cor))
#DMI - NE Aus
dmi_max1 <- which.max(abs( SEcor_list[[1]]$dmi_cor))
dmi_max2 <- which.max(abs( SEcor_list[[2]]$dmi_cor))
dmi_max3 <- which.max(abs( SEcor_list[[3]]$dmi_cor))
#TSA - NE Aus
tsa_max1 <- which.max(abs( SEcor_list[[1]]$tsa_cor))
tsa_max2 <- which.max(abs( SEcor_list[[2]]$tsa_cor))
tsa_max3 <- which.max(abs( SEcor_list[[3]]$tsa_cor))
#AAO - NE Aus
aao_max1 <- which.max(abs( SEcor_list[[1]]$aao_cor))
aao_max2 <- which.max(abs( SEcor_list[[2]]$aao_cor))
aao_max3 <- which.max(abs( SEcor_list[[3]]$aao_cor))
# OLR - NE Aus
olr_max1 <- which.max(abs( SEcor_list[[1]]$olr_cor))
olr_max2 <- which.max(abs( SEcor_list[[2]]$olr_cor))
olr_max3 <- which.max(abs( SEcor_list[[3]]$olr_cor))


setwd("~/CO_AUS/Aus_CO-main/Interactions/Figures")

png(filename = "sE_corr.png", width = 2600, height = 1800, res = 200)

set.panel(2,3)
plot(1:52, SEcor_list[[1]]$nino_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = rgb(1, 0, 0, 0.95))
abline(h = 0, lty = 2)
points(nino_max1, SEcor_list[[1]]$nino_cor[nino_max1], pch = 16, col = rgb(1, 0, 0, 0.95), cex = 1.33)
lines(1:52, SEcor_list[[2]]$nino_cor, col = rgb(0, 1, 0, 0.95))
points(nino_max2, SEcor_list[[2]]$nino_cor[nino_max2], pch = 17, col ="green4", cex = 1.33)
lines(1:52, SEcor_list[[3]]$nino_cor, col = rgb(0, 0, 1, 0.95))
points(nino_max3, SEcor_list[[3]]$nino_cor[nino_max3], pch = 19, col = rgb(0, 0, 1, 0.95), cex = 1.33)
title("Nino", adj = 0)


plot(1:52, SEcor_list[[1]]$dmi_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag", col = rgb(1, 0, 0, 0.95))
abline(h = 0, lty = 2)
points(dmi_max1, SEcor_list[[1]]$dmi_cor[dmi_max1], pch = , col = rgb(1, 0, 0, 0.95), cex = 1.33)
lines(1:52, SEcor_list[[2]]$dmi_cor, col = rgb(0, 1, 0, 0.95))
points(dmi_max2, SEcor_list[[2]]$dmi_cor[dmi_max2], pch = 17, col = "green4", cex = 1.33)
lines(1:52, SEcor_list[[3]]$dmi_cor, col = rgb(0, 0, 1, 0.95))
points(dmi_max3, SEcor_list[[3]]$dmi_cor[dmi_max3], pch = 19, col = rgb(0, 0, 1, 0.95), cex = 1.33)
title("DMI", adj = 0)




plot(1:52, SEcor_list[[1]]$tsa_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag", col = rgb(1, 0, 0, 0.95), lwd = 0.75)
abline(h = 0, lty = 2)
points(tsa_max1, SEcor_list[[1]]$tsa_cor[tsa_max1], pch = 16, col = rgb(1, 0, 0, 0.95), cex = 1.33)
lines(1:52, SEcor_list[[2]]$tsa_cor, col = rgb(0, 1, 0, 0.95))
points(tsa_max2, SEcor_list[[2]]$tsa_cor[tsa_max2], pch = 17, col = "green4", cex = 1.33)
lines(1:52, SEcor_list[[3]]$tsa_cor, col = rgb(0, 0, 1, 0.95))
points(tsa_max3, SEcor_list[[3]]$tsa_cor[tsa_max3], pch = 19, col = rgb(0, 0, 1, 0.95), cex = 1.33)
title("TSA", adj = 0)



plot(1:52, SEcor_list[[1]]$aao_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag", col = rgb(1, 0, 0, 0.95))
abline(h = 0, lty = 2)
points(aao_max1, SEcor_list[[1]]$aao_cor[aao_max1], pch = 16, col = rgb(1, 0, 0, 0.95), cex = 1.33)
lines(1:52, SEcor_list[[2]]$aao_cor, col = rgb(0, 1, 0, 0.95))
points(aao_max2, SEcor_list[[2]]$aao_cor[aao_max2], pch = 17, col = "green4", cex = 1.33)
lines(1:52, SEcor_list[[3]]$tsa_cor, col = rgb(0, 0, 1, 0.95))
points(aao_max3, SEcor_list[[3]]$aao_cor[aao_max3], pch = 19, col = rgb(0, 0, 1, 0.95), cex = 1.33)
title("SAM (AAO)", adj = 0)


plot(1:52, SEcor_list[[1]]$olr_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag", col = rgb(1, 0, 0, 0.95))
abline(h = 0, lty = 2)
points(olr_max1, SEcor_list[[1]]$olr_cor[olr_max1], pch = 16, col = rgb(1, 0, 0, 0.95), cex = 1.33)
lines(1:52, SEcor_list[[2]]$olr_cor, col = rgb(0, 1, 0, 0.95))
points(olr_max2, SEcor_list[[2]]$olr_cor[olr_max2], pch = 17, col = "green4", cex = 1.33)
lines(1:52, SEcor_list[[3]]$olr_cor, col = rgb(0, 0, 1, 0.95))
points(olr_max3, SEcor_list[[3]]$olr_cor[olr_max3], pch = 19, col = rgb(0, 0, 1, 0.95), cex = 1.33)
title("OLR", adj = 0)

par(xpd = NA)
legend("topright", inset = c(-0.50, 0.00),
       legend = c("Group 1", "Group 2",  "Group 3"),
       pch = c(16, 17, 19),
       col = c( rgb(1, 0, 0, 0.95), 
                "green4",
                rgb(0, 0, 1, 0.95)),
       pt.cex = c(1.33, 1.33, 1.33),
       cex = 1.5)
mtext("SE Aus : Correlation", side = 3, outer = TRUE, line = -1.5, cex = 1.5)

dev.off()

```



```{r NEAus_plots}
#NE Aus 1
setwd("~/CO_AUS/Aus_CO-main/Interactions/Figures")

png(filename = "NE1_cor.png", width = 4000, height = 3000, res = 400)

par(oma = c(1, 1, 4, 1))

set.panel(2,3)
nino_max <- which.max(abs( NEcor_list[[1]]$nino_cor))
plot(1:52, NEcor_list[[1]]$nino_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag")
abline(h = 0, lty = 2)
points(nino_max, NEcor_list[[1]]$nino_cor[nino_max], pch = 16, col = "green4", cex = 1.33)
title("Nino", adj = 0)

dmi_max <- which.max(abs( NEcor_list[[1]]$dmi_cor))
plot(1:52, NEcor_list[[1]]$dmi_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag")
abline(h = 0, lty = 2)
points(dmi_max, NEcor_list[[1]]$dmi_cor[dmi_max], pch = 16, col = "magenta4", cex = 1.33)
title("DMI", adj = 0)

tsa_max <- which.max(abs( NEcor_list[[1]]$tsa_cor))
plot(1:52, NEcor_list[[1]]$tsa_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag")
abline(h = 0, lty = 2)
points(tsa_max, NEcor_list[[1]]$tsa_cor[tsa_max], pch = 16, col = "darkorange3", cex = 1.33)
title("TSA", adj = 0)

aao_max <- which.max(abs( NEcor_list[[1]]$aao_cor))
plot(1:52, NEcor_list[[1]]$aao_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag")
abline(h = 0, lty = 2)
points(aao_max, NEcor_list[[1]]$aao_cor[aao_max], pch = 16, col = "red3", cex = 1.33)
title("SAM (AAO)", adj = 0)

olr_max <- which.max(abs( NEcor_list[[1]]$olr_cor))
plot(1:52, NEcor_list[[1]]$olr_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag")
abline(h = 0, lty = 2)
points(olr_max, NEcor_list[[1]]$olr_cor[olr_max], pch = 16, col = "turquoise4", cex = 1.33)
title("OLR", adj = 0)

mtext("NE Aus Group 1 (Weeks 35-37, 47-52, 1-14)", outer = TRUE, cex = 1.25, font = 1, adj = 0)

dev.off()

# NE Aus 2
setwd("~/CO_AUS/Aus_CO-main/Interactions/Figures")

png(filename = "NE2_cor.png", width = 4000, height = 3000, res = 400)

par(oma = c(1, 1, 4, 1))

set.panel(2, 3)
nino_max <- which.max(abs( NEcor_list[[2]]$nino_cor))
plot(1:52, NEcor_list[[2]]$nino_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag")
abline(h = 0, lty = 2)
points(nino_max, NEcor_list[[2]]$nino_cor[nino_max], pch = 16, col = "green4", cex = 1.33)
title("Nino", adj = 0)

dmi_max <- which.max(abs( NEcor_list[[2]]$dmi_cor))
plot(1:52, NEcor_list[[2]]$dmi_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag")
abline(h = 0, lty = 2)
points(dmi_max, NEcor_list[[2]]$dmi_cor[dmi_max], pch = 16, col = "magenta4", cex = 1.33)
title("DMI", adj = 0)

tsa_max <- which.max(abs( NEcor_list[[2]]$tsa_cor))
plot(1:52, NEcor_list[[2]]$tsa_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag")
abline(h = 0, lty = 2)
points(tsa_max, NEcor_list[[2]]$tsa_cor[tsa_max], pch = 16, col = "darkorange3", cex = 1.33)
title("TSA", adj = 0)

aao_max <- which.max(abs( NEcor_list[[2]]$aao_cor))
plot(1:52, NEcor_list[[2]]$aao_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag")
abline(h = 0, lty = 2)
points(aao_max, NEcor_list[[2]]$aao_cor[aao_max], pch = 16, col = "red3", cex = 1.33)
title("SAM (AAO)", adj = 0)

olr_max <- which.max(abs( NEcor_list[[2]]$olr_cor))
plot(1:52, NEcor_list[[2]]$olr_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag")
abline(h = 0, lty = 2)
points(olr_max, NEcor_list[[2]]$olr_cor[olr_max], pch = 16, col = "turquoise4", cex = 1.33)
title("OLR", adj = 0)

mtext("NE Aus Group 2 (Weeks 38-46)", outer = TRUE, cex = 1.25, font = 1, adj = 0)

dev.off()

```



```{r SEAus_plots}
#SE Aus 1
setwd("~/CO_AUS/Aus_CO-main/Interactions/Figures")

png(filename = "SE1_cor.png",  width = 4000, height = 3000, res = 400)

par(oma = c(1, 1, 4, 1))

set.panel(2,3)
nino_max <- which.max(abs( SEcor_list[[1]]$nino_cor))
plot(1:52, SEcor_list[[1]]$nino_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag")
abline(h = 0, lty = 2)
points(nino_max, SEcor_list[[1]]$nino_cor[nino_max], pch = 16, col = "green4", cex = 1.33)
title("Nino", adj = 0)

dmi_max <- which.max(abs( SEcor_list[[1]]$dmi_cor))
plot(1:52, SEcor_list[[1]]$dmi_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag")
abline(h = 0, lty = 2)
points(dmi_max, SEcor_list[[1]]$dmi_cor[dmi_max], pch = 16, col = "magenta4", cex = 1.33)
title("DMI", adj = 0)

tsa_max <- which.max(abs( SEcor_list[[1]]$tsa_cor))
plot(1:52, SEcor_list[[1]]$tsa_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag")
abline(h = 0, lty = 2)
points(tsa_max, SEcor_list[[1]]$tsa_cor[tsa_max], pch = 16, col = "darkorange3", cex = 1.33)
title("TSA", adj = 0)

aao_max <- which.max(abs( SEcor_list[[1]]$aao_cor))
plot(1:52, SEcor_list[[1]]$aao_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag")
abline(h = 0, lty = 2)
points(aao_max, SEcor_list[[1]]$aao_cor[aao_max], pch = 16, col = "red3", cex = 1.33)
title("SAM (AAO)", adj = 0)

olr_max <- which.max(abs( SEcor_list[[1]]$olr_cor))
plot(1:52, SEcor_list[[1]]$olr_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag")
abline(h = 0, lty = 2)
points(olr_max, SEcor_list[[1]]$olr_cor[olr_max], pch = 16, col = "turquoise4", cex = 1.33)
title("OLR", adj = 0)

mtext("SE Aus Group 1 (Weeks 35-37, 51-52, 1-14)", outer = TRUE, cex = 1.25, font = 1, adj = 0)

dev.off()

# SE Aus 2
set.panel(1,5)
setwd("~/CO_AUS/Aus_CO-main/Interactions/Figures")

png(filename = "SE2_cor.png",  width = 4000, height = 3000, res = 400)

par(oma = c(1, 1, 4, 1))
set.panel(2,3)
nino_max <- which.max(abs( SEcor_list[[2]]$nino_cor))
plot(1:52, SEcor_list[[2]]$nino_cor, type = "l", ylim = c(-1,1),
     ylab = "Correlation", xlab = "Lag")
abline(h = 0, lty = 2)
points(nino_max, SEcor_list[[2]]$nino_cor[nino_max], pch = 16, col = "green4", cex = 1.33)
title("Nino", adj = 0)

dmi_max <- which.max(abs( SEcor_list[[2]]$dmi_cor))
plot(1:52, SEcor_list[[2]]$dmi_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag")
abline(h = 0, lty = 2)
points(dmi_max, SEcor_list[[2]]$dmi_cor[dmi_max], pch = 16, col = "magenta4", cex = 1.33)
title("DMI", adj = 0)

tsa_max <- which.max(abs( SEcor_list[[2]]$tsa_cor))
plot(1:52, SEcor_list[[2]]$tsa_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag")
abline(h = 0, lty = 2)
points(tsa_max, SEcor_list[[2]]$tsa_cor[tsa_max], pch = 16, col = "darkorange3", cex = 1.33)
title("TSA", adj = 0)

aao_max <- which.max(abs( SEcor_list[[2]]$aao_cor))
plot(1:52, SEcor_list[[2]]$aao_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag")
abline(h = 0, lty = 2)
points(aao_max, SEcor_list[[2]]$aao_cor[aao_max], pch = 16, col = "red3", cex = 1.33)
title("SAM (AAO)", adj = 0)

olr_max <- which.max(abs( SEcor_list[[2]]$olr_cor))
plot(1:52, SEcor_list[[2]]$olr_cor, type = "l", ylim = c(-1,1),
     ylab = "", xlab = "Lag")
abline(h = 0, lty = 2)
points(olr_max, SEcor_list[[2]]$olr_cor[olr_max], pch = 16, col = "turquoise4", cex = 1.33)
title("OLR", adj = 0)

mtext("SE Aus Group 2 (Weeks 38-50)", outer = TRUE, cex = 1.25, font = 1, adj = 0)

dev.off()

```


