---
title: "test_ssdf"
author: "Ryan Peterson"
date: "2025-03-04"
output: pdf_document
---


```{r library}
suppressMessages( library(LatticeKrig))

#parallel packages for integration
suppressMessages(library(foreach))
suppressMessages(library(parallel))
suppressMessages(library(doParallel))

#color
suppressMessages(library(scales))

#timing
suppressMessages( library(tictoc))
```


```{r functions}
setwd("~/COS_LK")

#functions (new)
source("CubicBSpline/R/CubicBSpline.R")
source("CubicBSpline/R/new_basisintegral.R") #WIP functions

#(old - linear)
source("CubicBSpline/R/integralPolyFunction.R")

# patch in newer version of LK functions
source("CubicBSpline/R/LatticeKrig.R")
source("CubicBSpline/R/LKrigFindLambda.R")
source("CubicBSpline/R/print.LatticeKrig.R" )

# patch in updates to integral functions
source("DF_LK/R/basisIntegralNew.R")
source("DF_LK/R/integralPolyFunctionNew.R")

#old integral funcionts
source("COSExample/R/basisIntegral.R")
source("COSExample/R/integralPolyFunction.R")
```


```{r data}
setwd("~/COS_LK/CubicBSpline")

load("Data/integration_testdata.rda")

load("Data/COSExampleData.rda") #load separately from integration test data
```


```{r}
#updated domain
sDomain <- rbind( c( -1, 0), c( 1 ,2))

N<- length(polyGroupsRandom)
cScale<- alpha(turbo(256),.5)
cTab<- color.scale(yTrueRandom, cScale)
layout<-setupLegend()
plot( sDomain, type="n")
for ( k in 1:N){
  polyTmp<- polyGroupsRandom[[k]]
  polygon(polyTmp, col=cTab[k], border="black", lwd=.2)
}
addLegend(layout, col=alpha(turbo(256),.75), zlim= range(yTrueRandom ))
```


